# Phase 1 requirements whose recorded status or note changed because of Phase 2. Assessed on 2026-09-27.
#
# Each record replaces the Phase 1 record of the same number in scripts/status_map.py.
# Requirements of the Phase 1 PARTIAL list that are not named here are unchanged.
# "Phase 1" inside a note means: as recorded at the end of Phase 1 and not re-assessed here.
#
# Brought up to date on 2026-09-27 after the review corrections (scripts/_assess/CORRECTIONS.md):
# 4, 10, 13, 21, 40, 42, 165, 420, 422, 624, 625, 664, 717, 830, 1291, 1753 and 1754 were rewritten;
# 35 and 498 were added after each example question of the requirement was put to NUMI on the sample data.
# Third review, same day (migration 0013): 4, 498 and 830 were rewritten and 158 was added.
UPDATES = [
    # (status, requirement number, evidence, notes)
    ("PARTIAL", 4, "custom_field_defs · src/pages/Genesis.tsx › Custom fields · src/ui/ops.tsx CustomFields · src/ui/PartyOperations.tsx · numero_private.save_custom_values · tests/sql/phase2_payroll.sql T127 T128 · tests/ops.test.ts › a task cannot be closed without its outcome; required custom fields are enforced · supabase/migrations/0013_review_corrections_2.sql record_scopes · tests/sql/phase2_corrections_2.sql T150 T151 T154 · tests/ops.test.ts › a required field of one sub-type does not block a record of another",
     "Built: 27 field types can be defined and versioned in Genesis (Phase 1), for the whole group or for one company, mandatory or optional, and limited to a sub-type where wanted (a register kind, a document type, a party type), in which case a required field is asked only of records of that sub-type (T150, T151, T154); values are stored against defined fields only and required fields are enforced by the database (T127, T128); a field defined for invoices and bills, register items, fixed assets or parties appears on those records under 'Additional information' (for a party, on its Operations tab), where its value is entered and saved, with inputs for text, number, money, percentage, date, yes/no and a choice from options. Not built: value panels on journals, payments, organisation units and companies (Genesis accepts a definition for them and labels it 'not yet shown on its screen'), and on claims, advances and purchase documents (no field can be defined for them); drag-and-drop form builder; conditional, formula, lookup, attachment and signature behaviour; hidden, read-only, role-restricted, industry-specific and approval-dependent fields. No automated test goes from a field defined on the Genesis screen to its panel on a record: the tests define the field through the data layer."),

    ("PARTIAL", 6, "tests/sql/engine_invariants.sql · tests/engine.test.ts · tests/sql/phase2_flow.sql T30–T41 · tests/sql/phase2_treasury_purchasing.sql T84–T93 · tests/ops.test.ts · src/pages/Assets.tsx · src/pages/Treasury.tsx",
     "Built: double entry, journals, contra, receipts, payments, purchases, sales, notes, cash/bank book, day book, TB, P&L, BS, cash flow, control accounts, advances, loans, intercompany, suspense (Phase 1, tested). Phase 2 adds depreciation by straight-line or written-down value, calculated for a month when a person starts the run and posted on approval (T30–T38); asset disposal (T39–T41) and impairment; loan disbursement and instalments (T84–T90); fixed deposit placement and closure (T91–T93); entries for advances, expense claims, fund transfers and payroll. Every one is proposed by the operation and reaches the ledger only on approval. Not built: fund flow; accrual and prepayment schedules; runs that start by themselves (a person starts each depreciation run); impairment has no dedicated test."),

    ("PARTIAL", 10, "src/pages/Cash.tsx · src/pages/Expenses.tsx · tests/sql/phase2_flow.sql T42–T54 T62–T64 · tests/sql/phase2_corrections.sql T136 T137 · tests/ops.test.ts › a cash count records the difference and cannot be altered · cash ledgers, cash book report",
     "Built: cash ledgers and cash book report (Phase 1); cash and petty cash boxes tied to a cash ledger, with custodian, unit (branch, office or site), float, minimum balance and a limit for a single payment, above which a payment proposed by an operation is recorded and raised for review (T136, T137); physical cash count by notes and coins, compared with the book balance on the date of the count, unalterable, with a factual alert when it differs (T62, T63); register of employee advances with ageing (T42–T54); cash withdrawals, cash deposits, petty cash top-ups and transfers recorded as fund transfers that post on approval (T64). Not built: a daily reconciliation routine — a count is recorded when a person chooses to, nothing requires or schedules one each day, and there is no day-end cash statement."),

    ("PARTIAL", 11, "Documents, DocumentEditor, Owed, ReportView › Ageing · src/ui/records.tsx Promises · src/pages/DocumentEditor.tsx · numero_private.save_promise · tests/forward.test.ts › early warnings state facts, rules and assumptions · tests/sql/phase2_flow.sql T74",
     "Built: customer master, invoices, partial payments, credit terms, ageing, overdue (Phase 1); promises to pay recorded against an invoice or a customer with amount, date, person and channel, closed with an outcome, shown in Forward as PROMISED and raised as a warning when the date passes; an invoice that takes a customer beyond the configured credit limit is recorded and flagged, not blocked (T74). Not built: recurring invoices, payment schedules, reminders sent through any channel. Saving a promise has no dedicated automated test."),

    ("PARTIAL", 12, "Documents, DocumentEditor, Payments · src/pages/Purchasing.tsx · src/pages/PurchaseDetail.tsx · src/ui/records.tsx BillOrder · tests/sql/phase2_treasury_purchasing.sql T94–T106 · tests/ops.test.ts › requisition → order → receipt → bill, with a three-way comparison",
     "Built: bills, terms, partial payments, advances, duplicate-bill detection (Phase 1); purchase requisitions, requests for quotation, vendor quotations with a recorded selection, purchase orders, goods and service receipts, a bill linked to its order, and the three-way comparison of ordered, received and billed, which shows quantity differences, the price difference between a bill and its order, and charges that are not on the order (T94–T106). Not built: detection of a price change against earlier purchases (only a bill against its own order is compared); missing-documentation detection for bills."),

    ("PARTIAL", 13, "src/pages/Entry.tsx · src/pages/ClaimEditor.tsx · src/pages/Expenses.tsx · src/ui/ops.tsx Attachments · src/ui/ApprovalRuleEditor.tsx · src/App.tsx · tests/sql/phase2_flow.sql T48–T60 · tests/ops.test.ts",
     "Built: guided expense entry with approval (Phase 1); expense claims with lines, categories and policy flags; receipts attached to the claim as photographs, PDF or other files (upload to the live storage not exercised); approval line by line, with a lower amount and a reason where needed; on approval an accounting entry is proposed and approved by a second person; reimbursement recorded separately (T48–T58); approval steps chosen by company and amount, by rules that are added and changed on the Approvals page; a person with the Employee role can prepare claims and sees only their own (T59, T60), and the Expenses screen and its menu entry open for a person who may only prepare claims. Not built: OCR or any extraction from a receipt; email ingestion; approval rules by department or expense type. Submission by an employee has not been exercised against the live system."),

    ("PARTIAL", 15, "Documents, DocumentEditor · src/pages/Registers.tsx · src/engine/registerKinds.json",
     "Built: invoice → receipt, credit notes (Phase 1); a quotation sent to a customer and a sales order can be recorded as register items, with party, amount, dates and certainty, and appear in Forward. Not built: quotation, proforma and sales order as documents that convert into an invoice; recurring, subscription, milestone, project, commission, rental and brokerage billing."),

    ("PARTIAL", 16, "tax_codes, tax_code_components · Genesis › Tax codes · ReportView › Registers · src/ui/AccountMapping.tsx · tests/sql/phase2_treasury_purchasing.sql T93 · tests/sql/phase2_payroll.sql T115",
     "Built: CGST/SGST/IGST codes with effective dates, HSN/SAC, sales and purchase registers (Phase 1); tax deducted at source is recorded as an amount entered by a person — on the closure of a fixed deposit, to the ledger mapped as tax deducted receivable (T93), and as a salary deduction, to the ledger mapped as tax deducted payable (T115); tax and compliance deadlines can be recorded in the registers and are raised as warnings in Forward. Not built: TDS/TCS sections, rates and calculation; reverse charge; ITC reconciliation; return workflows."),

    ("PARTIAL", 18, "intercompany ledgers · ReportView › Consolidation · src/pages/Cash.tsx · numero_private.propose_fund_transfer · tests/sql/phase2_flow.sql T65 · tests/ops.test.ts › an intercompany transfer has two entries; a one-sided outcome raises an alert",
     "Built: due-to/due-from ledgers, mismatch detection, balance elimination (Phase 1); a transfer of money between two group companies proposes both entries, one in each company's books, each approved separately, and a priority alert is raised when only one side stands (T65). Not built: the mirror entry for an expense one company pays for another, and for intercompany revenue, management fees and asset transfers; shared-cost and employee-cost allocation."),

    ("PARTIAL", 21, "src/pages/Forward.tsx · src/engine/forward.ts · src/lib/forwardData.ts · tests/forward.test.ts",
     "Built: projected cash from open invoices and bills, approved purchase orders not yet billed, register items (subscriptions, rent, insurance, contracts and other recurring obligations), loan instalments, maturing deposits, payroll (posted and unpaid, and a labelled FORECAST that repeats the last run), claims and advances, with a scheduled occurrence left out when a bill from the same party is already recorded for its period, over horizons that include 7, 30, 60 and 90 days, 6 and 12 months; firm amounts are kept apart from expected and forecast amounts; a customer's usual payment delay is shown as an ESTIMATE beside the due date. Not built: forecasts from historical patterns other than that payment delay (no statistical forecasting); tax worked out from the books — a tax appears only when a person records the deadline with an amount; conversion of register items, loans, deposits, advances and claims held in another currency (Forward states how many such items it counts at face value, and in which currencies)."),

    ("IMPLEMENTED", 35, "src/numi/engine.ts · src/numi/NumiPanel.tsx · tests/numiOps.test.ts › cash, receivables and approvals answer as before",
     "Each of the 14 example questions was put to NUMI on the sample data on 2026-09-27, and each received an answer on its subject, from recorded data, with its scope and period and with links to the records behind it: spending this month, the movement in the marketing expense of Jamin Bazaar, who owes the most, payments due this week, expenses above ₹1 lakh, cash across the group, customers 60 days overdue, this quarter against the last, unusual transactions, gross margin, duplicates, the company that consumed the most cash, intercompany balances, and the balance sheet in plain words. Limits: 'GHL' is taken as the whole group; 'What changed in gross margin?' gives the margin of both periods and the main lines of the profit and loss, not the cause; 'Find duplicate invoices' lists every possible duplicate on record (invoice references, payments and files); an answer to 'Why did …' names the ledgers that moved and states that it does not know the business reason. The engine is deterministic and matches fixed patterns; no external model is used. Automated tests ask two of the 14 ('How much cash do we have across the group?', 'Which company owes us the most money?'); the other twelve have no test, so the status is IMPLEMENTED and not TESTED."),

    ("PARTIAL", 36, "src/engine/nlp.ts · Sentinel · src/numi/ops.ts · tests/numiOps.test.ts",
     "Built: classification, ledger and journal suggestions, duplicate and anomaly detection, variance explanation (Phase 1); answers on cash ahead from recorded documents and registers, labelled FORECAST, and on advances, claims, commitments, debt, deposits, assets and payroll totals. Not built: invoice and receipt extraction; statistical forecasting; missing-document detection across the books (only an expense-claim line without a receipt is flagged, by the claim engine)."),

    ("PARTIAL", 40, "run_sentinel · src/pages/Sentinel.tsx · tests/sql/phase2_flow.sql T63 T65 T74 · tests/sql/phase2_treasury_purchasing.sql T100 T102 · tests/sql/phase2_corrections.sql T136 · tests/forward.test.ts › dependence on one vendor is stated beside dependence on one customer · tests/ops.test.ts › a missing asset raises a factual alert and changes nothing in the books",
     "Built: 8 Sentinel rules, run on demand (Phase 1); since Phase 2 further factual alerts are raised by the engine at the moment of the event and appear in the same list — a cash count that differs from the books, a bill above its order or ahead of its receipt, one side of an intercompany transfer standing alone, a customer beyond the credit limit, an identical file uploaded twice, an asset reported missing or damaged, a payment from a cash box above its limit for a single payment (T136); Forward raises a cash shortfall, a large share of receivables with one customer and a large share of payables with one vendor when it is opened. Not built: continuous evaluation of the Sentinel rules; expense-spike, revenue-decline and unusual-vendor rules."),

    ("PARTIAL", 42, "approval_rules · numero_private.open_request · src/pages/Approvals.tsx · src/ui/ApprovalRuleEditor.tsx · tests/sql/phase2_corrections.sql T139 T140 T141 · tests/ops.test.ts › in an approval of several steps a later approver may lower the amount, not raise it",
     "Built: the approval engine chooses a multi-step rule by company, amount and kind of record, and since Phase 2 applies it to journals, entries proposed by operations, advances, expense claims, requisitions and purchase orders; the configured rules are listed on the Approvals screen, where a Group Super Admin or a holder of the permission approval.configure adds and changes them in a form (name, kind of record, company, amount from and to, steps by role in order, in force or not); a rule of two steps is tested on an advance, where a later step may lower the amount authorised and may not raise it (T139 to T141). Not built: a visual builder (the editor is a form); rules on account, department, project, vendor or risk score. The rule editor has no automated test: the tests save their rule through the data layer."),

    ("PARTIAL", 43, "tests/sql/engine_invariants.sql T11-T13 · tests/sql/phase2_flow.sql T29 T59–T61 · tests/sql/phase2_payroll.sql T117–T119",
     "Built: group, company and module level (Phase 1); since Phase 2 record level in three places — a person without the expense permissions sees only the advances and claims they created (T59), payroll records are visible only with a payroll permission (T117, T118), and a confidential entry is hidden from a person without clearance (T119); permissions for registers, documents, assets, purchasing, expenses, treasury and payroll, with the roles Payroll Officer and Employee (T29). Not built: branch, department, account and field level."),

    ("PARTIAL", 49, "src/pages/Forward.tsx › Calendar · src/engine/forward.ts · tests/forward.test.ts",
     "Built: a month calendar in Forward that places on their dates the collections and payments due on invoices and bills, loan instalments, payroll, subscriptions, rent, insurance premiums, contract amounts, purchase commitments and maturing deposits, each with its certainty and a link to its record. Not built: a date is placed on the calendar only when it carries an amount, so tax and audit deadlines, renewals and expiries recorded without an amount are raised as early warnings and are not on the calendar; budgets; invoice dates (a document is placed on its due date, not its issue date)."),

    ("PARTIAL", 51, "src/pages/ReportView.tsx · src/pages/Assets.tsx",
     "Built: 17 of the 23 listed reports in the report library (Phase 1); the asset register — cost, accumulated depreciation and book value of every asset, with export — on the Fixed assets screen (Phase 2), not in the report library. Not built: inventory valuation, project profitability, cost-centre report, tax returns, fund flow."),

    ("PARTIAL", 57, "src/pages/Owed.tsx · Party360 · src/pages/Expenses.tsx · src/pages/Registers.tsx · tests/forward.test.ts › advance ageing and advance memory",
     "Built: sundry debtors and creditors with ageing, advances per party (Phase 1); a register of advances to employees, vendors and others, with the unsettled balance aged in six bands and the advances past their settlement date (Phase 2); security deposits paid and received can be recorded in the registers. Not built: one command centre that brings these together; ageing of deposits; customer advances as a register (they remain a ledger balance shown per party)."),

    ("PARTIAL", 92, "docs/NUMERO_TEST_MATRIX.md · tests/sql/phase2_flow.sql T30–T38 · tests/ops.test.ts › written-down value and part-month depreciation",
     "Built: automated tests for the listed subjects as recorded in Phase 1, and since Phase 2 for depreciation — straight-line, written-down value, part month, order of months and reversal (T30–T38). Not built: a test of currency translation."),

    ("PARTIAL", 98, "src/pages/Party360.tsx · src/ui/PartyOperations.tsx",
     "Built: overview, contact, roles by company, invoices and bills, payments and receipts, ledger statement, bank details, timeline and the figures at the top (Phase 1); an Operations tab (Phase 2) with the party's advances, expense claims, purchasing documents, loans, contracts and other register items that name the party, promises to pay and files held for the party, each list shown only to a viewer who holds the permission for it. Not built: projects, properties, tasks, communication history, and a current contract value at the top."),

    ("PARTIAL", 106, "Parties · src/ui/PartyOperations.tsx · src/pages/Registers.tsx · src/pages/Inbox.tsx",
     "Built: the vendor master as recorded in Phase 1; since Phase 2 contracts with a vendor can be recorded in the registers and appear on the vendor's page, and files such as licences and insurance policies can be held against the vendor with an expiry date that Forward warns about. Not built: pricing and rate lists per vendor; certifications and insurance as structured records (they are files with a kind and an expiry date); ledger mappings and approvals per vendor and company."),

    ("PARTIAL", 107, "Party360 · src/ui/PartyOperations.tsx",
     "Built: the figures and lists recorded in Phase 1; since Phase 2 the vendor's page lists its purchasing documents, among them purchase orders with their status, the contracts and disputes recorded against it in the registers, the advances paid to it through the advance register and the files held for it. Not built: price history; a list limited to open purchase orders (every purchasing document of the vendor is listed, with its status)."),

    ("PARTIAL", 120, "Party360 · src/ui/PartyOperations.tsx · src/ui/records.tsx Promises",
     "Built: the figures and lists recorded in Phase 1; since Phase 2 the customer's page lists the contracts, sales orders and other register items recorded against the customer, the promises to pay and the files held for the customer. Not built: projects and properties; communication history (a promise records who promised and through which channel, nothing more); sales orders as documents."),

    ("PARTIAL", 127, "src/pages/Owed.tsx · src/pages/Forward.tsx · src/pages/Expenses.tsx · src/pages/Treasury.tsx",
     "Built: the one-click screen, from supplier bills, grouped by due date (Phase 1); since Phase 2 what is owed to employees as approved reimbursements and unpaid net salaries, to lenders as loan instalments and under recorded obligations is shown in Forward (payment priority, the next 60 days) and on the Expenses, Payroll and Treasury screens. Not built: those amounts inside the one-click screen, which still reads supplier bills only; amounts owed to government, to customers awaiting refunds and to group companies as groups of their own."),

    ("PARTIAL", 128, "src/pages/Owed.tsx · src/pages/Expenses.tsx · src/pages/Treasury.tsx",
     "Built: the one-click screen, from customer invoices, with ageing (Phase 1); since Phase 2 money held by employees and others as unsettled advances is listed with its age on Expenses › Unsettled advances, and loans given are listed in Treasury. Not built: those amounts inside the one-click screen, which still reads customer invoices only; tenants, agents, borrowers and group companies as groups of their own."),

    ("PARTIAL", 129, "src/pages/Expenses.tsx · src/pages/Advance360.tsx · tests/sql/phase2_flow.sql T42–T55 · tests/sql/phase2_payroll.sql T121 · tests/forward.test.ts › advance ageing and advance memory · tests/numiOps.test.ts",
     "Built: a register of advances with request, approval (a lower amount may be approved), release, settlement by approved claims, return and recovery through payroll; recipient types employee, travel, vendor, project, site, department, procurement, petty cash, emergency and other; unsettled balances aged in six bands, advances past their settlement date listed, follow-ups recorded, facts already on record about the person shown before approval, and a Forward warning for an advance unsettled past its date. Not built: customer advances (money received in advance) and intercompany advances are not in this register and remain ledger balances; types of their own for contractor, broker and salary advances (a salary advance is recorded as an employee advance and recovered through payroll)."),

    ("PARTIAL", 165, "src/engine/forward.ts earlyWarnings · src/pages/Forward.tsx › Early warnings · tests/forward.test.ts › dependence on one vendor is stated beside dependence on one customer",
     "Built: two factual statements in Forward, each raised when the share is 30% or more, with the amounts behind it and a link to the party: the share of open receivables held by the largest customer, and the share of open payables owed to the largest vendor (the vendor statement is tested). Not built: the two measures the requirement gives as examples — a vendor's share of expenditure in a category during a period, and a customer's share of recorded revenue during the selected period; both statements measure what is outstanding today, not what was bought or sold in a period, and below 30% nothing is stated."),

    ("PARTIAL", 171, "JournalDetail › responsibility chain · src/pages/JournalDetail.tsx · src/pages/Approvals.tsx · src/ui/ops.tsx ApprovalTrail · numero_private.open_request",
     "Built: created, submitted, approved and posted on every entry (Phase 1); since Phase 2 a request that goes through the approval engine records who requested it and who decided each step, and an entry proposed by an operation links to its source record — the advance, claim, requisition or order — where the request and its approval are kept. Not built: one chain that joins request, review, approval, accounting, authorisation, payment and receipt; paid-by and received-by as recorded steps."),

    ("PARTIAL", 240, "Entry › Deposit paid · src/pages/Registers.tsx · src/engine/registerKinds.json",
     "Built: a deposit paid is recorded in a deposit ledger, not as an expense (Phase 1); since Phase 2 a security deposit paid or received can be recorded in the registers with the holder, the refund conditions, the amount and the expected date, and rent and lease items carry the deposit paid. Not built: a link between a register item and the deposit ledger — a security deposit item has no cost-tracking dimension, so the register is not reconciled with the books; ageing of deposits."),

    ("PARTIAL", 274, "src/pages/Entry.tsx · src/pages/JournalDetail.tsx · src/pages/ClaimEditor.tsx · src/ui/ops.tsx Attachments",
     "Built: the simple entry form with the accounting suggestion (Phase 1); since Phase 2 a receipt can be attached to the entry on its own page, which opens after saving, and an expense can instead be entered as a claim with receipts attached; an identical file is kept and flagged as a possible duplicate. Not built: receipt upload inside the quick-entry form itself. File upload to the live storage has not been exercised."),

    ("PARTIAL", 275, "src/pages/JournalDetail.tsx · src/pages/ClaimEditor.tsx",
     "Built: the entry page shows the debit and credit ledgers, party, tags (department, project and other dimensions), voucher number, date, the source record and, since Phase 2, the evidence attached; an expense claim is shown to finance with category, ledger, who paid, receipt and policy flags. Not built: tax and accounting period as fields of their own (tax appears only as ledger lines, the period only as the date)."),

    ("PARTIAL", 288, "Accounts · src/pages/Expenses.tsx › Policy · numero_private.save_expense_category · tests/sql/phase2_flow.sql T48 T49",
     "Built: expense categories created by an authorised person, each mapped to a ledger, with limits per item and per day, a receipt requirement, a maximum age and guidance; the limits raise flags for the approver and never reject (T48, T49); a change is recorded with its reason. Not built: subcategories; tax treatment, cost-centre rules, required fields, approval rules, confidentiality and budget rules per category; categories for revenue."),

    ("PARTIAL", 348, "Budgets › overrun alerts · src/pages/PurchaseDetail.tsx › Budget context · src/pages/Purchasing.tsx › Commitments · tests/forward.test.ts › an approved purchase order is COMMITTED for what has not been billed",
     "Built: overrun alerts from actual spending (Phase 1); committed spending is now tracked, as approved purchase orders not yet billed, and a purchase order shows the budget, the actual and what would remain for its ledgers, for information only. Not built: alerts at 70, 80, 90 and 100% on actual plus committed spending; commitments on the Budgets screen. A budget-exhaustion calculation exists in the engine with a test, but no screen uses it."),

    ("PARTIAL", 373, "tests/engine.test.ts · src/pages/Assets.tsx › Reconciliation · tests/ops.test.ts › the asset register agrees with the general ledger · src/pages/Treasury.tsx · src/pages/Expenses.tsx",
     "Built: the party subledger, reconciled with its control accounts (Phase 1); since Phase 2 a fixed asset register compared with its ledgers, ledger by ledger, with any difference shown; a loan register with its schedule; advances held, person by person. Not built: subledgers for inventory, investors, projects and properties; a comparison of the loan register with the loan ledger."),

    ("PARTIAL", 389, "Banking · src/pages/Cash.tsx · src/pages/Assets.tsx › Reconciliation · tests/sql/phase2_flow.sql T62 · tests/ops.test.ts › the asset register agrees with the general ledger",
     "Built: bank (Phase 1); cash, as a physical count compared with the book balance (T62); fixed assets, as the register compared with its ledgers. Intercompany differences are shown in the consolidation report. Not built: credit cards, payment gateways, receivables, payables, inventory, loans, payroll, taxes, advances and deposits as reconciliations of their own."),

    ("PARTIAL", 396, "tests/engine.test.ts · src/pages/Assets.tsx › Reconciliation · tests/ops.test.ts › the asset register agrees with the general ledger",
     "Built: receivable and payable control accounts compared with the party subledger in a test, with no screen (Phase 1); fixed asset ledgers compared with the asset register on screen and in a test (Phase 2). Not built: a screen for the receivable and payable comparison; payroll control and inventory control."),

    ("TESTED", 420, "tests/forward.test.ts › a cash shortfall names its causes and assumptions · tests/forward.test.ts › contingent amounts are reported beside the projection, never inside it · src/engine/forward.ts earlyWarnings · src/pages/Forward.tsx",
     "Forward warns when projected cash would fall below the chosen threshold within 90 days: it names the day, the projected cash, the largest outflows before it and the assumptions. Expected inflows and outflows are shown with their firm part apart, everything after today's cash is labelled FORECAST, and contingent amounts are kept outside the projection. The projection now draws on documents, purchase commitments, registers, loans, deposits, payroll, claims and advances. Limits: the threshold is kept in the browser only; amounts of register items, loans, deposits, advances and claims held in another currency are not converted, and Forward states how many such items it counts at face value, and in which currencies; nothing that is not recorded is projected."),

    ("PARTIAL", 422, "src/pages/Forward.tsx · src/engine/forward.ts cashHorizon · tests/forward.test.ts › contingent amounts are reported beside the projection, never inside it",
     "Built: outflows for the horizons today, 7, 14, 30, 60 and 90 days and longer, split into firm and other, from bills, purchase commitments, register items, loan instalments, payroll, claims and advances; a payment priority list of what falls due in the next 60 days. Not built: a horizon for tomorrow; obligations recorded without an amount; conversion of register items, loans, advances and claims held in another currency (Forward states how many such items it counts at face value, and in which currencies)."),

    ("PARTIAL", 444, "Budgets · src/pages/PurchaseDetail.tsx › Budget context · src/pages/Purchasing.tsx › Commitments",
     "Built: budget, actual and variance on the Budgets screen (Phase 1); since Phase 2 a purchase order shows, for its ledgers, the budget, the actual, the unbilled part of the order and the budget left after it, and open commitments are totalled in Purchasing. Not built: committed, remaining and forecast columns on the Budgets screen."),

    ("PARTIAL", 498, "src/numi/engine.ts · src/numi/ops.ts · tests/numiOps.test.ts › the wording of the specification's own example questions · tests/numiOps.test.ts › cash, receivables and approvals answer as before · tests/numiOps.test.ts › whole words only",
     "Built: each of the 18 example questions was put to NUMI on the sample data on 2026-09-27. Sixteen were answered on their subject, from recorded data: whether we are profitable; the money we actually have; what people owe us; what we owe (supplier bills only); which expenses increased; the cash needed next month (a projection over the next 61 days, labelled FORECAST); payments due this week; which companies consume cash; the profit and loss of the whole group (company figures before intercompany eliminations, and the answer says so); the balance sheet of the whole group; actual against budget (the lines that are over budget); unreconciled transactions (a count of unreconciled bank lines inside the answer on the integrity of the books, not a list); audit exceptions; working capital (a figure inside the answer on the balance sheet); where the money went (total expense by company); why profit moved (the two periods side by side — revenue, gross profit, operating expenses, profit after tax — with no business reason claimed). Eight of these wordings are covered by a test, and a further test confirms that 'Why did profit fall?' is no longer read as a question about technology: patterns match whole words. Not built: 'Which department overspent?' is answered with the budget lines that are over budget, by ledger and company (tested for its subject); budgets are kept by ledger, so nothing compares the spending of a department with a budget; 'Which invoices are overdue?' is answered with the customers who owe the most and the total overdue, not with the overdue invoices; 'Show me where ₹10 crore went' does not follow the amount named."),

    ("PARTIAL", 595, "privacy mode, masked account numbers · tests/sql/phase2_payroll.sql T113 T117–T119 · tests/numiOps.test.ts › declines to state what an individual is paid, even for a person who may see payroll",
     "Built: privacy mode and masked bank account numbers (Phase 1); since Phase 2 salary records are visible only to a person with a payroll permission, the payroll entry is confidential and carries no individual salary (only the recovery of an advance names the person), and NUMI never states what an individual is paid (T113, T117–T119). Not built: masking by permission of PAN, tax identifiers, investor data and other personal information — the party page shows PAN and GSTIN in full to anyone who may open the party."),

    ("PARTIAL", 624, "src/pages/Forward.tsx › Calendar · src/engine/forward.ts · tests/forward.test.ts",
     "Built: the Forward calendar places on their dates vendor payments (open bills and purchase commitments), payroll, rent, loan instalments, subscriptions, insurance premiums, contract amounts and other recorded obligations, each with its certainty and a link to its record. Not built: a tax deadline, or any other obligation, recorded without an amount is not placed on the calendar (it is raised as an early warning instead) — the tax deadlines of the sample data are of this kind; amounts of register items held in another currency are not converted (Forward states how many such items it counts at face value, and in which currencies)."),

    ("PARTIAL", 625, "src/pages/Forward.tsx › Calendar · src/engine/forward.ts · tests/forward.test.ts › an estimate never replaces the contractual date",
     "Built: the Forward calendar places on their dates the expected customer collections (the promised or estimated date is shown beside the due date), tenant rent, contracted inflows, maturing deposits, capital calls, advances to be returned and other recorded inflows. Not built: a register kind for commission receivable or for investment income — they can be recorded only under another kind; an inflow recorded without an amount is not placed; amounts of register items, loans, deposits and advances held in another currency are not converted (Forward states how many such items it counts at face value, and in which currencies)."),

    ("PARTIAL", 664, "src/engine/forward.ts · src/pages/Forward.tsx · src/lib/forwardData.ts · tests/forward.test.ts · tests/numiOps.test.ts",
     "Built: a dedicated engine that builds every known future money event from open invoices and bills, promises to pay, approved purchase orders, the registers (50 kinds, and any the administrator adds), loans, deposits, payroll, claims and advances, each with its source, certainty and basis; cash horizons, calendar, early warnings, commitments and payment priority on the Forward screen; a source the viewer may not read is named on screen, not silently left out. Not built: monitoring that runs by itself and notifies anyone — Forward is calculated when it is opened or asked; statistical forecasts and scenarios; tax worked out from the books; conversion of register items, loans, deposits, advances and claims held in another currency (Forward states how many such items it counts at face value, and in which currencies)."),

    ("IMPLEMENTED", 716, "src/engine/forward.ts earlyWarnings · src/pages/Forward.tsx › Early warnings",
     "Forward states, as an early warning, the share of open receivables held by the largest customer when it is 30% or more, with the amounts behind it and a link to the customer (in the sample data: 49%). Below 30% nothing is stated; the Phase 1 panel that always showed the largest customer's share was removed when Forward was rewritten. No automated test asserts this warning, so the status is IMPLEMENTED and not TESTED."),

    ("PARTIAL", 717, "src/engine/forward.ts earlyWarnings · src/pages/Forward.tsx › Early warnings · tests/forward.test.ts › dependence on one vendor is stated beside dependence on one customer",
     "Built: Forward states, as an early warning for review, the share of open payables owed to the largest vendor when it is 30% or more, with the amounts behind it and a link to the vendor, in factual words (tested: '90% of recorded payables are owed to Steelmax'). Not built: the measure the requirement gives — a vendor's share of recorded purchases in a category during a selected period; the warning counts what is owed today on open purchase bills and credit notes of every category, and states nothing below 30%."),

    ("PARTIAL", 721, "src/pages/Forward.tsx › Calendar · src/engine/forward.ts calendarMonth · tests/forward.test.ts",
     "Built: a visual month calendar in Forward with collections, payments, payroll, rent, loan instalments, subscriptions, insurance premiums, capital calls, distributions and project payments under work orders, each day showing inflow, outflow and the number of contingent items, and each event opening its record. Not built: dates that carry no amount are not on the calendar — guarantee expiry, renewals and tax deadlines recorded without an amount are raised as early warnings instead; contract milestones as dated events (a contract carries its milestones as text and an amount by frequency)."),

    ("PARTIAL", 830, "src/numi/engine.ts · src/numi/ops.ts · tests/numiOps.test.ts › the wording of the specification's own example questions · tests/numiOps.test.ts › whole words only",
     "Built: the example of the requirement, 'How much money did we make this week?', is answered with the profit and the revenue of the current week, Monday to Sunday (tested, with its period); 'today', 'yesterday', 'this week' and 'last week' are recognised as periods beside month, quarter and year; plain wordings such as 'the money we actually have', 'what do people owe us' and 'where the money went' are recognised. Not built: open understanding of plain language — a question is matched to a fixed set of patterns, and one that matches none receives the honest reply that it cannot be answered from the books yet; patterns match whole words (tested: 'profit' is not read as 'IT', nor 'loads' as 'ads'), but a question can still be answered more broadly than it was asked: put to NUMI on the sample data on 2026-09-27, 'Which department overspent?' was answered with the budget lines that are over budget, by ledger and company, and 'How much did each vehicle cost us this year?' with total expense by company."),

    ("PARTIAL", 923, "tests/commands.test.ts › an instruction embedded in dictated text cannot trigger an action · src/pages/Inbox.tsx · src/numi/ops.ts",
     "Built: documents can now be uploaded and stored (Phase 2) and nothing reads their contents — NUMI answers from records only, the inbox suggests a kind from the file name alone and labels it SUGGESTION for a person to accept or ignore, and an instruction inside a typed or dictated command is never executed (tests/commands.test.ts). Not built: reading of document contents, so a defence against instructions embedded in a document has not been exercised or tested."),

    ("PARTIAL", 1290, "src/pages/Approvals.tsx · src/lib/workflow.ts · tests/sql/phase2_flow.sql T32 T43 T50 · tests/sql/phase2_treasury_purchasing.sql T96 T97",
     "Built: one inbox for journals, accounting entries proposed by operations, advance requests, expense claims, requisitions and purchase orders, with the steps of each request, the facts of the record and the approve and reject actions. Not built: it lists every request of the selected companies, not only those waiting for the signed-in person; approvals that are made on other screens and do not appear in it — invoices and bills, payments and receipts, salaries, the bank details of a party and the selection of a quotation."),

    ("PARTIAL", 1291, "src/pages/Sentinel.tsx · tests/sql/phase2_flow.sql T63 T65 T74 · tests/sql/phase2_treasury_purchasing.sql T100 T102 · tests/sql/phase2_corrections.sql T136 · tests/ops.test.ts › a missing asset raises a factual alert and changes nothing in the books",
     "Built: the Sentinel list now also receives the factual alerts raised by operations — a cash count that differs from the books, a bill above its order or ahead of its receipt, one side of an intercompany transfer standing alone, a customer beyond the credit limit, an identical file uploaded twice, an asset reported missing or damaged, a payment from a cash box above its limit for a single payment — beside the Sentinel rules of Phase 1. Not built: bank reconciliation differences, missing documents and data issues in the same inbox; policy flags on expense claims are shown on the claim, not here."),

    ("PARTIAL", 1330, "intercompany ledgers · src/pages/Cash.tsx · numero_private.propose_fund_transfer · tests/sql/phase2_flow.sql T65",
     "Built: intercompany ledgers (Phase 1); since Phase 2 a transfer of money between two group companies, with an entry in each company's books, each approved separately, and an alert when only one side stands (T65). Not built: flows of their own for intercompany loans, advances, sales, purchases, management fees, shared costs, employee costs, asset transfers, expense recharges and central procurement."),

    ("PARTIAL", 1520, "tests/sql/engine_invariants.sql · tests/sql/phase2_flow.sql T59–T61 T79 · tests/sql/phase2_payroll.sql T116–T119 · tests/sql/phase2_treasury_purchasing.sql T107",
     "Built: tests acting as owner, accountant, outsider and anonymous (Phase 1); since Phase 2 also as finance head, payroll officer and employee, and as a person without clearance — the employee sees only their own claims and advances and cannot approve (T59–T61), the finance head without a payroll permission sees no payroll and cannot approve a confidential entry (T116–T119), the payroll officer cannot approve a salary they entered (T107). Not built: tests acting as auditor and as company administrator."),

    ("PARTIAL", 1523, "tests/commands.test.ts › an instruction embedded in dictated text cannot trigger an action · src/pages/Inbox.tsx",
     "Built: uploaded files are stored, fingerprinted, classified and linked by a person; no part of the system reads their contents, and only the file name is used, for a suggestion a person may ignore; an instruction inside a typed or dictated command cannot trigger an action (tests/commands.test.ts). Not built: reading of documents, invoices or emails, so resistance to instructions embedded in them has not been exercised or tested."),

    ("PARTIAL", 1547, "scripts/build_requirement_ledger.py · scripts/check_status_part.py",
     "Built: generation of the requirement ledger from the status records; a check of each status file — every requirement recorded once, a TESTED record names a test, a PARTIAL note says what is built and what is not, and every file named as evidence exists. Not built: comparison of the ledger with the code, database, APIs, screens and tests themselves; the outputs MISSING, CONFLICT and UNTESTED; a single command that runs the whole audit."),

    ("PARTIAL", 1576, "suspense ledger · src/pages/JournalDetail.tsx · src/ui/ops.tsx Attachments",
     "Built: an item parked in suspense is a journal with its date, narration and purpose; since Phase 2 evidence can be attached to the journal. Not built: owner, expected resolution, age and follow-up recorded for each suspense item; a list of suspense items that shows them."),

    ("PARTIAL", 1600, "src/voice/commands.ts · tests/commands.test.ts · tests/numiOps.test.ts › commands on operations",
     "Built: a spoken or typed command opens a screen, including the Phase 2 operations screens, sets the period or puts a question to NUMI; a command that would release, pay, approve, post or otherwise change records is recognised and never executed — it opens the screen where a person does it (tested). Not built: performing a finance action by voice; microphone capture has not been exercised."),

    ("PARTIAL", 1718, "contextualPrompts · src/numi/engine.ts · src/numi/ops.ts opsPrompts · tests/numiOps.test.ts › the operations screens suggest their own questions",
     "Built: the questions NUMI suggests depend on the screen that is open, including the operations screens (expenses, purchasing, treasury, cash, assets, payroll, registers, follow-ups, inbox). Not built: answering about the record on screen — asked 'What's wrong here?' while an advance is open, NUMI replies that it cannot answer; the record being viewed is not passed to it."),

    ("PARTIAL", 1753, "custom_field_defs · numero_private.save_custom_values · src/pages/Genesis.tsx › Custom fields · src/ui/ops.tsx CustomFields · src/ui/PartyOperations.tsx · src/pages/Registers.tsx › Register kinds · tests/sql/phase2_payroll.sql T127 T128 · tests/sql/phase2_flow.sql T70",
     "Built: any number of fields can be defined in Genesis (Phase 1); since Phase 2 values are stored against defined fields with required fields enforced (T127, T128), a field defined for invoices and bills, register items, fixed assets or parties appears on those records, where its value is entered and saved, and each kind of register item carries its own fields, defined as data and editable by the Group Super Admin (T70). Not built: a field defined for a journal, a payment, an organisation unit or a company reaches no screen (Genesis labels it 'not yet shown on its screen'); no field can be defined for claims, advances or purchase documents."),

    ("PARTIAL", 1754, "27 field types · src/pages/Genesis.tsx › Custom fields · src/ui/ops.tsx CustomFields · src/pages/Registers.tsx",
     "Built: 27 field types can be chosen when a field is defined (Phase 1); on invoices and bills, register items, fixed assets and parties a defined field is shown with an input for text, number, money, percentage, date, yes/no or a single choice from options, and every other type is entered as plain text; the fields of a register kind use six types (text, number, money, date, choice, yes/no). Not built: working inputs for the other listed types, among them time, date-time, multi-select (shown as a single choice), lookup and relationship, formula and calculated, attachment, image, signature, address and location, barcode and QR, rating; the listed types beyond the 27."),
    ("PARTIAL", 158, "custom_field_defs scope_key · src/pages/Genesis.tsx › Custom fields · src/ui/PartyOperations.tsx · src/ui/ops.tsx CustomFields · supabase/migrations/0013_review_corrections_2.sql record_scopes · tests/sql/phase2_corrections_2.sql T154 · tests/ops.test.ts › a field required of one party type is asked of that type only",
     "Built: a field can be defined for one party type (broker, transporter, contractor and the others, including types the group adds); it appears under 'Additional information' on the Operations tab of a party that holds that type, where its value is entered and saved; a field marked required is asked of parties of that type and of no other (tested, T154). Not built: the fields named in the requirement are not preloaded — the group defines its own; a field does not appear on the form that creates the party, only on its page afterwards; conditional, formula and lookup fields. No automated test goes from the Genesis screen to the panel on the party: the tests define the field through the data layer."),
]


# Phase 1 records that are withdrawn: nothing of the requirement is built, so it is PLANNED again
# (scripts/status_map.py removes the Phase 1 record of each number listed here).
# Empty on 2026-09-27. Requirement 717 was recorded in this file as PARTIAL with "Built: nothing" while Forward had no
# statement about vendors; the warning on payables owed to one vendor has since been restored and tested
# (src/engine/forward.ts, kind payable_concentration), so a part of 717 is built and its record stays in UPDATES.
# Requirement 165 was re-assessed with it and also stays PARTIAL.
REVERT_TO_PLANNED = []


if __name__ == "__main__":
    counts = {}
    for status, _no, _evidence, _notes in UPDATES:
        counts[status] = counts.get(status, 0) + 1
    print(len(UPDATES), "phase 1 records updated:", counts)
