# Requirement status — phase 3 — Digital Twin (scenario lab, sandbox, scenario studio, rule simulation). Assessed against the code on 2026-09-27.
# Brought up to date on 2026-09-27 after the corrections listed in scripts/_assess/P3_CORRECTIONS.md (part B), each read in the code.
# Brought up to date again on 2026-09-27 after the section "Found when the records were read a second time" of the
# same file. R1, R2, R3 and R4 touch this part (entries 54, 634, 1296, 1798, 1901 and the facts below); each was read
# in the code. R5 to R15 and the limits recorded with them touch no entry of this part. No status changed.
#
# How to read this file
#   TESTED       engine + screen + a named automated test that asserts the behaviour
#   IMPLEMENTED  engine + screen, workflow works end to end, no test for this specific requirement
#   PARTIAL      some of it works; the note says "Built: ... Not built: ..."
#   PLANNED      not built; listed in PLANNED with the reason
#
# Facts that apply to many entries below (verified in the code):
#   * The word "scenario" has two meanings in the specification. A SIMULATION (Digital Twin: 54, 89, 427, 428,
#     508, 815, 1285, 1295-1297, 1358, 1359, 1425, 1901) is kept in the tables scenarios, scenario_runs and
#     twin_drivers. A WAY OF WORKING (Scenario Studio: 1768-1772, 1809, 1820, 1828) is kept in flow_defs,
#     flow_cases and flow_case_steps. Neither can be taken for the other.
#   * The digital twin is arithmetic on monthly rates averaged over the last 3, 6 or 12 complete months of
#     posted entries (src/lib/twinData.ts, src/engine/twin.ts). It is not a forecast and learns nothing.
#     Several companies are added as they stand: charges between them are not eliminated and currencies are
#     not converted; the model says so in its notes.
#   * The model runs in the browser. Nothing is written unless a person saves a scenario, a run or a driver.
#   * Sixteen kinds of assumption exist (SHOCK_KINDS). The engine tests assert the effect of nine of them:
#     revenue_pct, collection_delay_days, new_borrowing, capex, category_pct, payroll_pct, lose_customer,
#     new_project and, through a driver, payroll_pct and revenue_pct. No test asserts the effect of margin_pts,
#     expense_pct, new_hires, payment_delay_days, interest_rate_pts, fx_pct, project_overrun_pct or one_off in
#     the model, and no test asserts payment coverage. The optimistic and the conservative case are tested for
#     revenue_pct, collection_delay_days and payment_delay_days: a longer delay in paying suppliers is taken
#     to help cash (tests/p3app.test.ts 'paying suppliers later helps cash, so the conservative case shortens
#     the delay'). A delay may be a negative number of days: customers who pay sooner free cash, and the model
#     says "sooner" and "falls" (tests/p3control.test.ts 'customers who pay sooner free cash, and the model says
#     sooner'); of suppliers paid sooner that test asserts the wording only, not the effect on cash.
#   * The sandbox is the in-browser engine filled with a copy of the configuration and with the figures of the
#     books: per company, the balances of a year ago as one entry, what moved in each ledger since as one
#     entry a month, and what each party owes or is owed today (src/lib/sandbox.ts). It copies no transaction
#     (journal, invoice, bill, payment, stock movement), no employee, salary, document, bank statement or
#     confidential record, and no role or permission of the group: every person of the sandbox holds every
#     permission. The rows its own build writes to the trail are counted and set apart; the trail on the
#     screen lists what the person did afterwards: it reads the latest 500 rows and says so when it holds that
#     many (src/pages/Sandbox.tsx; no test). For a person who works on the live books, the sandbox runs
#     the in-browser mirror of the rules, not the database functions, and the screen says so. No integration
#     can be tried in it, because none is connected.
#   * A workflow of the Scenario Studio is a straight line of steps. It is started by a person, posts nothing
#     and releases nothing; a step that releases money or recognises cost points to the record that does.
#   * No screen test exists: the tests exercise the engines, the loaders and the database functions. The
#     screens were read in the code and exercised in the demo only, never against the live database.
#     A gate on a screen (who may open, start or complete) cannot be observed in the sample data, where every
#     person holds every permission, and the live data layer (src/api/supabase*.ts) has no automated test.
#   * The migration files were extracted again from the database. supabase/migrations/0017_scenarios_flows.sql
#     now holds p3_19_driver_superseded_on_approval, p3_20_flow_approval_maker_checker,
#     p3_22_flow_own_request_step and p3_23_flow_own_step_null_safe. The checks T269, T270 and T271 rest on them.
ENTRIES = [
    # (status, requirement number, evidence, notes)
    ("IMPLEMENTED", 54, "src/pages/Twin.tsx · src/pages/TwinParts.tsx · src/engine/twin.ts · src/lib/twinData.ts · supabase/migrations/0017_scenarios_flows.sql · numero_private.save_scenario, save_scenario_run · tests/sql/phase3_platform.sql T242 T243 T244 T245 · tests/p3control.test.ts 'a saved simulation is labelled SIMULATION, touches no entry, and cannot be relabelled' 'revenue falls 20%: cost of sales falls with it, payroll does not' 'customers pay 30 days later: profit is unchanged, cash is not' 'a loan and an asset: cash in, cash out, interest and depreciation follow' 'side by side: the base and the scenarios, with the change from the base' · tests/p3app.test.ts 'a simulation leaves the base and the books as they were' 'paying suppliers later helps cash, so the conservative case shortens the delay' 'the questions of the specification are read as they are asked' 'what could not be read is said, not dropped' 'a fall of sales says nothing about interest rates' 'sooner is not later' 'a number of days that points neither way is not read, and is named as not read' · src/numi/p3.ts shocksFrom, unread",
     "A person with scenario.view builds a scenario on the Digital Twin screen; saving needs scenario.manage (tested, T242). The five examples exist as assumptions: revenue changes, operating expenses change, customers pay later, an asset is bought, interest rates change. A scenario is saved as Base, Optimistic, Conservative or Custom, and the lab derives an optimistic and a conservative case from the assumptions typed; in them a longer delay in paying suppliers counts as helping cash (tested). Every result, table, chart and export carries the word SIMULATION; a saved run cannot be relabelled (tested, T245) and saving touches no entry (tested, T244). The status is IMPLEMENTED and not TESTED because the effect of 'expenses rise 15%' and of 'interest rates rise' has no test of its own. The questions are built with controls on the screen. Asked in words to NUMI, three of the five examples are read: 'revenue drops 20%', 'expenses rise 15%' and 'collections are delayed 30 days' (tested: 'collections are delayed 30 days' in these words, and a fall in revenue in the words 'revenue falls by 20%'; the reading of a rise in expenses has no test). 'We purchase 5 crore of equipment' is not read, because NUMI reads no purchase of an asset, and 'interest rates rise' is not read without a figure: asked alone, NUMI says that it could not read an assumption; asked beside an assumption it reads, it names the part it could not read and says that it is not in the result (tested). Which way a figure points is read in the part of the sentence the figure stands in, not in the whole question: a fall of sales in one part does not lower the interest rates of another (tested). A number of days is read as later or as sooner where the words say so; where they say neither it is not read and is named as not read (tested)."),
    ("PARTIAL", 89, "src/pages/Twin.tsx · src/pages/TwinParts.tsx · src/engine/twin.ts · src/lib/twinData.ts · tests/p3app.test.ts 'the twin starts from the books: cash and receivables are those of the balance sheet' 'a simulation leaves the base and the books as they were' · tests/p3control.test.ts 'an approved driver supplies the value; one that is not approved does not' 'a loan and an asset: cash in, cash out, interest and depreciation follow' 'a customer lost without a name changes nothing, and the model says so' · tests/sql/phase3_platform.sql T244 T245 T246",
     "Built: a model of one company or of several together, read from posted entries, invoices, bills, employees, the loan register and open orders for assets, with assumptions that a second person has approved (drivers); decisions tried without touching the books: an asset or a property is bought (capex), people are hired, money is borrowed, one kind of expense such as marketing rises, a customer is lost, a project starts; the base figures are marked ACTUAL and every result SIMULATION. Not built: 'open a new branch' and 'delay a project' as decisions of their own (a branch can only be put together by hand from an asset, hires and expenses; projects are not in the model, so an existing project cannot be delayed); 'increase marketing' works only where an expense ledger of that name carries a balance in the months the model rests on; hiring has no test of its own."),
    ("IMPLEMENTED", 427, "src/pages/Twin.tsx · src/pages/TwinParts.tsx · src/engine/twin.ts · tests/p3control.test.ts 'revenue falls 20%: cost of sales falls with it, payroll does not' 'customers pay 30 days later: profit is unchanged, cash is not' 'several shocks at once, and a named expense that doubles' 'a project without a stated duration lasts twelve months, not for as long as the model looks ahead'",
     "All eight examples can be entered: revenue falls or grows by a percentage, customers pay a number of days later, a named expense ledger such as fuel rises or marketing doubles, payroll rises, interest rates move by points, a project of a stated value starts. Tested: revenue, payment delay of customers, a named expense that doubles, payroll +15%, a new project. Not covered by a test: the effect of a change in interest rates. A named expense can be changed only where a ledger of that name carries a balance; the quick buttons for fuel and marketing appear only then. The screen has no automated test."),
    ("TESTED", 428, "src/pages/Twin.tsx · src/engine/twin.ts compare, standardCases · tests/p3control.test.ts 'side by side: the base and the scenarios, with the change from the base'",
     "The Compare tab sets a reference and up to three scenarios side by side (the base case, the scenario in the lab, its optimistic and conservative cases, saved scenarios), all run on the same books over the same months. Rows: revenue, operating profit, profit after tax, cash at the end, lowest cash, borrowing needed, borrowings at the end, working capital at the end, lowest payment coverage, months before cash falls below zero, each with the difference against the reference. The test asserts the values and the differences of revenue for three columns and the presence of the rows for profit, cash, debt and working capital; the figures of those four rows are not asserted one by one, and the screen itself has no test."),
    ("PARTIAL", 508, "src/lib/twinData.ts · src/engine/twin.ts · src/pages/Twin.tsx · tests/p3app.test.ts 'the twin starts from the books: cash and receivables are those of the balance sheet' 'the twin names what it may not read' · tests/sql/phase3_platform.sql T244 T245 · tests/p3control.test.ts 'a saved simulation is labelled SIMULATION, touches no entry, and cannot be relabelled'",
     "Built: the model of a company or of several companies combines actual accounting (posted entries as monthly rates and ledger balances as the position), loans (the repayment schedule of the loan register; borrowings without a schedule are named), payroll (employee cost and headcount) and open purchase orders for fixed assets as firm one-off payments; simulated figures are never mixed with actuals: they are marked, a saved run is labelled SIMULATION and cannot be relabelled (tested). Not built: the budget, commitments other than orders for assets, contracts, sales orders, subscriptions and other register items, projects and the forecasts of Forward are not read into the model; open orders for goods and services are assumed to be inside the monthly rates."),
    ("PARTIAL", 634, "src/lib/sandbox.ts · src/pages/Sandbox.tsx · src/store/app.ts · src/ui/Shell.tsx · src/ui/AccountMapping.tsx · tests/p3app.test.ts 'is built from the configuration and the balances, and writes nothing to the books' 'what is done in the sandbox stays in the sandbox, and changes no object of the books' 'a person who may not read the ledger of a company gets that company empty, and is told' 'the twin of the sandbox rests on the same months as the twin of the books'",
     "Built: a sandbox in the memory of the browser, built from the configuration and the figures of the books — the balances of a year ago as one entry, what moved in each ledger since as one entry a month, and what each party owes or is owed today — in which every screen works on the copy; the balance of every ledger, and what each customer owes and each vendor is owed, equal those of the books, balances by party in another kind of ledger that several ledgers carry are left out and named, and the books are not written to (tested); an entry is prepared by one person of the sandbox and approved by another (tested); approval rules and account mapping are copied and can be changed there; the Imports screen and the reports work on the copy, and the reports show the last twelve months month by month; the trail of the sandbox lists what the person did, apart from the rows of its own build: it reads the latest 500 rows and says so when it holds that many (the count that sets the rows of the build apart is tested, the list on the screen and its sentence are not); exports are marked SANDBOX; it is discarded on leaving or reloading. Not built: integrations cannot be tried (none is connected and the register of integrations is not copied); automation cannot be tried (nothing in NUMERO runs by itself); a month arrives as one entry without parties, documents, departments or projects, and what parties owe arrives as one entry dated today, so a report on a period before the twelve months, a report by department or project, and an ageing by original date cannot be tried; nothing proved in the sandbox is carried to the books, a person repeats it by hand. Tested: the building of the sandbox, the months its twin rests on, and one entry. Changing a rule or a mapping, an import, and a report over a period inside the sandbox have no test."),
    ("IMPLEMENTED", 815, "src/pages/Twin.tsx · src/pages/TwinParts.tsx · src/engine/twin.ts · tests/p3control.test.ts '\"the top three customers pay 60 days late\" delays only their share' 'several shocks at once, and a named expense that doubles' 'customers pay 30 days later: profit is unchanged, cash is not' · src/numi/p3.ts shocksFrom · tests/p3app.test.ts 'the questions of the specification are read as they are asked'",
     "The lab has a panel 'What if this goes wrong?' with five adverse assumptions, among them 'The three largest customers pay 60 days late', and a button that adds four of them together. The result shows cash month by month, working capital, the borrowing requirement and payment coverage, all marked SIMULATION. Tested: the delay applies to the share of the three largest customers only; the borrowing requirement equals the lowest cash below zero. Not covered by a test: payment coverage, and the figure of working capital. Asked in words, NUMI reads 'the top 3 customers pay 60 days late' as a delay of 60 days for the three largest customers only (the reading is tested). Its answer states cash after twelve months, the lowest cash on the way and what would have to be found; it does not state working capital or payment coverage, which the screen shows."),
    ("TESTED", 1285, "src/pages/TwinParts.tsx · src/pages/Twin.tsx · src/engine/twin.ts dcf, freeCashFlows, byMultiples, byAssets · tests/p3control.test.ts 'valuation: every assumption is stated, and what cannot be valued is refused'",
     "The Valuation lab offers discounted cash flow on the cash flows of a simulation (the books continuing, or the scenario in the lab), multiples typed by a person with their source, and net assets from the balance sheet with adjustments that state their basis. Every input can be changed, every formula and assumption is shown, a figure from the books is marked ACTUAL and a typed one TYPED, and the result is a range marked ESTIMATE. The test asserts the discounted cash flow, its nine sensitivities, the refusal when the discount rate does not exceed growth, the refusal of a multiple without a source, and net assets with an adjustment left out for want of a basis. It runs the cash flows of the base case, not of a scenario with assumptions, and does not assert the value a multiple gives. NUMERO holds no market data: comparable inputs are what a person types."),
    ("PARTIAL", 1295, "src/lib/twinData.ts · src/engine/twin.ts · src/pages/Twin.tsx · src/pages/TwinParts.tsx · tests/p3app.test.ts 'the twin starts from the books: cash and receivables are those of the balance sheet' 'the twin names what it may not read'",
     "Built: the twin represents companies (one, or several added together), cash, people as a headcount, payroll, fixed assets at net book value, borrowings with their repayment schedule, inventory as a balance, receivables, payables, customers by what they were billed, open orders for assets as commitments, and tax as the rate the books show. Not built: contracts, projects, properties and investments are not in the model; liabilities other than payables and borrowings are not; commitments other than orders for assets are not; taxes payable and tax deadlines are not; the forecasts of Forward are not; the twin is read from the books each time the screen is opened or the basis is changed, it is not updated continuously."),
    ("PARTIAL", 1296, "src/pages/Twin.tsx · src/engine/twin.ts · src/numi/p3.ts · tests/p3control.test.ts 'several shocks at once, and a named expense that doubles' · tests/p3app.test.ts 'a simulation leaves the base and the books as they were' 'a what-if is a SIMULATION, says what it assumed, and writes nothing' 'the questions of the specification are read as they are asked' 'what could not be read is said, not dropped' 'a fall of sales says nothing about interest rates' · tests/sql/phase3_platform.sql T244",
     "Built: on the Digital Twin screen the three assumptions of the example — sales fall 25%, customers pay 45 days later, an asset is bought — are entered together and the model runs as they are typed (the engine is tested with these three); nothing is written to the books (tested). Asked in words, NUMI reads two of the three, 'sales fall 25%' and 'collections are delayed 45 days', runs the simulation on them, and names in its answer the part it could not read, saying that it is not in the result (the reading of these two, with their size and the way each points, is tested on a question of three parts, 'sales fall 25%, collections are delayed 45 days and interest rates rise 2%', in which the fall of sales does not lower the rates; the naming of what was not read is tested on a question of the same form). Not built: the whole question asked in words. An investment or the purchase of an asset is not among the assumptions NUMI reads, so 'we invest 5 crore' is left out of the answer in words and is tried only on the screen. No test asks NUMI the question of the example as it stands."),
    ("PARTIAL", 1297, "src/engine/twin.ts · src/pages/Twin.tsx · src/pages/TwinParts.tsx · tests/p3control.test.ts 'several shocks at once, and a named expense that doubles'",
     "Built: up to 24 assumptions are combined in one scenario, each with its size, its first month and its duration: revenue, gross margin, interest rate, exchange rate, payroll, operating expenses or one named expense, delay in collection, purchase of an asset, overrun of the cost of sales; a combination of revenue, collection delay, asset purchase, a named expense and payroll is tested. Not built: the overrun of one named project (the assumption raises the whole cost of sales, because projects are not in the model); the exchange rate acts on the imported share of the cost of sales only, not on revenue, receivables, payables or borrowings in a foreign currency. The effect of the margin, interest, exchange rate and overrun assumptions has no test."),
    ("IMPLEMENTED", 1358, "src/pages/Twin.tsx · src/lib/twinData.ts · src/engine/twin.ts · tests/p3app.test.ts 'the twin starts from the books: cash and receivables are those of the balance sheet' 'a simulation leaves the base and the books as they were' · tests/p3control.test.ts 'customers pay 30 days later: profit is unchanged, cash is not'",
     "With several companies selected the screen is a group twin: their figures are added and a scenario is saved for the group. The example, customers of the group paying 30 days later, is one assumption. The companies are added, not consolidated: charges between them stay inside both revenue and expense, and books in different currencies are added without conversion; the model states both. The loader is tested on all the companies of the sample together: the test asserts that cash, receivables and payables of the twin are the balances of their ledgers, to the rupee; of revenue it asserts only that it exceeds a floor, and no test runs a delay in collection on the figures of the group. A scenario belongs to one company or to the group, so a scenario built on some of the companies is still kept for the group; the dialog says so and names the companies, and every saved run records the companies it ran on (the dialog has no test). A scenario cannot be kept for a set of companies."),
    ("IMPLEMENTED", 1359, "src/pages/Twin.tsx · src/lib/twinData.ts · src/pages/TwinParts.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T243 T244",
     "With one company selected the screen is a company twin: the model is read from the books of that company alone, the scenario is saved for that company, and drivers of that company are read before those of the group. The database tests save a scenario and a run for one company. No test loads the twin for a single company."),
    ("PARTIAL", 1423, "src/lib/sandbox.ts · src/pages/Sandbox.tsx · src/store/app.ts · src/ui/Shell.tsx · tests/p3app.test.ts 'what is done in the sandbox stays in the sandbox, and changes no object of the books' 'is built from the configuration and the balances, and writes nothing to the books'",
     "Built: a person with scenario.manage enters the sandbox and prepares, approves and posts entries, invoices, bills and other records on a copy that starts with the chart, the parties, the rules and the figures of the books (the balances of a year ago and the movement of each month since, as entries of the build); the rule that a second person approves applies there, and the person chooses whom to act as; the books are not touched (tested with an entry). Not built: an accounting scenario that needs a record of the books cannot be tried, because the transactions themselves are not copied: settling an open invoice, reversing a posted entry, depreciating an asset, running payroll, moving stock that exists. The sandbox is lost on reload and cannot be kept or shared."),
    ("PARTIAL", 1424, "src/lib/sandbox.ts · src/pages/Sandbox.tsx · src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/ui/AccountMapping.tsx · tests/p3app.test.ts 'is built from the configuration and the balances, and writes nothing to the books'",
     "Built: the workflows of the Scenario Studio, the approval rules and the account mapping are copied into the sandbox and can be changed and tried there on the same screens as in the books (the copy of approval rules is tested; trying a changed rule, mapping or workflow has no test). Not built: automation (nothing in NUMERO runs by itself, so there is nothing to try); integration (none is connected); the roles of the group are not copied, so a workflow step or an approval step for a role the group added itself cannot be tried; a change proved in the sandbox is not carried to the books, a person repeats it there."),
    ("TESTED", 1425, "src/pages/Twin.tsx · src/engine/twin.ts · src/lib/twinData.ts · supabase/migrations/0017_scenarios_flows.sql · src/lib/sandbox.ts · tests/p3app.test.ts 'a simulation leaves the base and the books as they were' 'the twin of the sandbox rests on the same months as the twin of the books' · tests/sql/phase3_platform.sql T244 T245 · tests/p3control.test.ts 'a saved simulation is labelled SIMULATION, touches no entry, and cannot be relabelled'",
     "A simulation is a calculation beside the books: it reads them and writes nothing, however often it is run (tested: the base and the books are unchanged after a run; a saved run adds no entry and keeps the label SIMULATION). The code sets no limit on the number of scenarios or runs; a scenario holds up to 24 assumptions, the model looks up to 60 months ahead, and the list of runs of a scenario shows the 50 most recent. Inside the sandbox the twin rests on the same months as in the books: the movement of each month is brought in, and the monthly rates, cash, receivables, payables and borrowings of the twin of the sandbox equal those of the twin of the books (tested). Invoices, employees, loans and purchase orders are not copied, so in the sandbox the twin names no customer and holds no headcount, no repayment schedule and no open order for an asset."),
    ("TESTED", 1543, "supabase/migrations/0018_platform.sql · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T257 · tests/p3control.test.ts 'the register of integrations holds no secret, and guards what can move money'",
     "An integration recorded as able to move money is marked HIGH RISK, is refused in production unless the date of a test in a sandbox is recorded, and is made active only by a Group Super Admin (tested in the database and in the demo engine). No integration is connected: the register records intent, and the date of the test is what a person states; NUMERO cannot check that the test took place. NUMERO itself moves no money."),
    ("TESTED", 1768, "src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T248 T249 T250 T251 T252 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "The Scenario Studio holds ways of working, each with its own path of steps, its form and its required documents, in versions, for one company or for the group, and the cases that follow them. A workflow is checked when designed and enforced when run (tested). The path is a straight line: there is no branch, no condition and no parallel step. A workflow posts nothing and releases nothing, and a person starts every case. The designer and the studio screens have no test of their own."),
    ("IMPLEMENTED", 1769, "src/pages/Studio.tsx FLOW_EXAMPLES · src/pages/FlowDesigner.tsx",
     "The studio offers nineteen examples and an empty canvas. All sixteen named here are among them: employee travel, petty purchase, emergency cash, site advance (site imprest), client entertainment, charitable donation, vendor advance, refund (due from a supplier), insurance claim, accident, asset purchase, project launch, event, seminar, customer refund, and custom (the empty canvas). An example is a starting point held in the screen: it opens the designer filled in, and nothing exists until a person saves it and makes it active. Roles and register kinds the group does not have are replaced and the person is told. No test checks that each example passes the rules of the engine; the sample books hold one active workflow (site imprest) and one draft."),
    ("PARTIAL", 1770, "src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T248 T250 T251 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "Built: 'Design a workflow' opens the designer, where a person with flow.configure defines the trigger, the path of steps, the role that acts at each step, the form and its fields (six kinds of answer, required or not), approval steps that the person who started the case cannot complete, the record each step points to, and the documents each step requires; these are enforced when a case runs (tested). Not built: actors, money flow, accounting, settlement, notifications, NUMI behaviour, Sentinel rules and reports are text that describes the way of working and configures nothing: no permission, due date, notification, alert rule, NUMI rule or report is set up from them, and the screen says so. Of the twelve triggers two start a case (see 1771)."),
    ("PARTIAL", 1771, "src/engine/p3Types.ts FLOW_TRIGGERS, FLOW_TRIGGERS_WORKING · src/pages/FlowDesigner.tsx · src/pages/Studio.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T248",
     "Built: all twelve triggers can be chosen and are stored on the workflow; two start a case: manual, and form (a person fills in the form of the workflow; required fields are enforced, tested). Not built: voice, document upload, e-mail, API, schedule, event, bank transaction, invoice, contract and NUMI detection start nothing; they are recorded as intent and marked so on every screen, and a person starts each case in the studio."),
    ("IMPLEMENTED", 1772, "src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/pages/Studio.tsx · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T249 T250 T251 T271 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "The path of the example can be designed and followed step by step: request, approval, review by finance, release of money, evidence, settlement, accounting, reconciliation (the example 'Employee travel' has these eight steps). Each step is completed in its turn by the role it is for; release, settlement and accounting steps are complete only when they point to the record that did it. Tested on a path of five steps: request, approval, release, evidence, review. Settlement, accounting and reconciliation steps have no test in a running case. The person who started a case completes its own request and evidence steps with the permission flow.view alone and goes no further; every other step needs flow.manage (tested in the database, T271), and so does cancelling a case (no test). The screens follow the same rule, which no test observes, because in the sample data every person holds every permission. 'Manager approval' is an approval by a role or by any second person; the manager of the employee is not worked out. A reconciliation step records that a person compared; the workflow compares nothing."),
    ("PARTIAL", 1798, "src/pages/TwinParts.tsx RulesTab · src/pages/Twin.tsx · src/engine/analysis.ts tryApprovalRule, tryThreshold · tests/p3control.test.ts 'a rule is tried against what is already on record before it is put in force' 'a rule tried on history states its amounts company by company: currencies are not added'",
     "Built: under Digital Twin, 'Try a rule': an approval rule (kind of record, company, amount band, steps) is tried against the approval requests on record, and a Sentinel threshold in money against the alerts on record, with the counts, the examples and what would have changed (the two calculations are tested); the amount of the requests a rule would have applied to is kept company by company (tested) and shown currency by currency, never added across currencies (the screen has no test); a threshold is tried as an amount in one currency: where the alerts on record belong to companies that keep their books in several currencies, the person chooses the currency, and the alerts of companies that keep their books in another are left out of the trial, with their number (on the screen, src/pages/TwinParts.tsx; no test); nothing is changed by a trial. Not built: the trial is a separate screen and is not part of putting a rule in force: a rule is saved and takes effect without it; the roles named in the steps are not compared; no other rule can be tried (expense policy limits, attention rules, materiality, the rules of a workflow); the dynamic NUMI and Sentinel rules of the specification do not exist."),
    ("PARTIAL", 1809, "src/pages/Studio.tsx · src/pages/FlowCase360.tsx",
     "Built: a dashboard for all workflows and for one workflow at a time: open, completed and cancelled cases, the amount stated on open cases, how many cases wait at each kind of step (request, approval, release, evidence, settlement and the others) and for how long, one workflow drawn step by step with the cases waiting at each, and the cases open longest. Not built: the figures of the example for travel: upcoming trips, advances released, expense and settlement as amounts (the dashboard shows the amount stated when the case was started, not the amounts of the advances and claims the steps point to) and overdue evidence (a step has no due date, so nothing is called overdue). The dashboard has no automated test."),
    ("TESTED", 1820, "src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/ui/ops.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T251 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "Each workflow states, step by step, the kinds of document it requires, chosen from the 23 kinds of the document inbox. A step cannot be completed until a document of each required kind is attached to the case (tested); the case shows each kind as attached or missing. The engine checks the kind the person chose for the document, not its content."),
    ("TESTED", 1828, "src/pages/Studio.tsx CloneDialog · src/pages/FlowDesigner.tsx · supabase/migrations/0017_scenarios_flows.sql · numero_private.clone_flow_def · tests/sql/phase3_platform.sql T252 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "A workflow is copied under a new key and name, for a company or the group, as a draft that remembers where it came from; the draft is changed freely in the designer, and the workflow it was copied from is not changed (tested). A workflow in use is changed as its next version. The clone dialog and the designer have no test of their own."),
    ("PARTIAL", 1838, "src/lib/sandbox.ts · src/pages/Sandbox.tsx · src/store/app.ts · tests/p3app.test.ts 'is built from the configuration and the balances, and writes nothing to the books' 'what is done in the sandbox stays in the sandbox, and changes no object of the books'",
     "Built: the sandbox copies companies, ledgers, account mapping, tax codes, units, parties, approval rules, fields of the group's own, periods and their locks, register kinds, expense, asset and stock categories, stock locations and items, workflows, message templates, attention rules, drivers and materiality thresholds; each can be changed and tried on the copy, and the books are not touched (tested: a changed ledger name stays in the sandbox). Not built: roles and permissions are not copied (every person of the sandbox holds every permission), so a change of permissions cannot be tried; capability switches, the register of integrations, salary structures and budgets are not copied; nothing moves a configuration from the sandbox to the books. No test changes an approval rule or a mapping in the sandbox and follows its effect."),
    ("TESTED", 1901, "src/pages/TwinParts.tsx DriversTab · src/pages/Twin.tsx · src/engine/twin.ts · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql · tests/p3control.test.ts 'an approved driver supplies the value; one that is not approved does not' 'an assumption is used only after a second person approves it' 'a driver in use stays in use while its successor awaits approval' 'a driver supplies an assumption only in its own unit' · tests/sql/phase3_platform.sql T246 T269 · tests/p3app.test.ts 'the twin starts from the books: cash and receivables are those of the balance sheet'",
     "The assumptions library holds drivers for a company or the group, each with a key, a unit, a value, what it rests on and whether it is recorded or assumed. An assumption of a simulation may name a driver; the value of the driver then replaces the value typed, only if a second person has approved it, and the result says which was used (tested). A driver supplies the value only where it is stated in the unit of the assumption that names it (percentage points take a percentage or a rate); otherwise the value typed is used and a note of the result says why (tested). The row of the assumption on the screen applies the same rule (driverFits of the engine): a driver stated in another unit is listed as 'not used here', the value typed is not dimmed, and the row says that the driver is not used, that the value typed is, and why. The rule is tested in the engine; the screen has no test. The behaviour asserted by T269 is in the database (migration p3_19, now written in the migration file of the repository) and in the demo engine."),
]
PLANNED = {
    # requirement number: why it is not built
}
