# Requirement status — phase 3 — Reality, General. Assessed against the code on 2026-09-27.
# Brought up to date on 2026-09-27 after the corrections listed in scripts/_assess/P3_CORRECTIONS.md (database
# pieces p3_24 and p3_25, supabase/migrations/0019_corrections_after_assessment.sql). Every correction relied on
# below was read in the code and in the test named for it; none was taken from the list alone.
# Brought up to date a second time on 2026-09-27 after the section "Found when the records were read a second time"
# of the same list (R1 to R21, database piece p3_27, and the paragraphs "Not corrected, recorded" and "Recorded as
# limits, not corrected"). Of these, R5, R6, R8, R9, R10, R11, R17 and R18 and both paragraphs bear on entries of this
# file; each correction was read in the code, and in the test named for it where one is named (R17 has a test of the
# lookup only; R18 and the gates on screens have none). The application tests are reported as 461 of 461 passing, and
# tests/sql/phase3_platform.sql as 36 of 36, T278 and T279 among them. The results of the other database suites after
# the last migration are pending: no entry of this file claims them anew.
#
# How to read this file
#   TESTED       engine + screen + a named automated test that asserts the behaviour
#   IMPLEMENTED  engine + screen, workflow works end to end, no test for this specific requirement
#   PARTIAL      some of it works; the note says "Built: ... Not built: ..."
#   PLANNED      not built; listed in PLANNED with the reason
#
# Facts that apply to many entries below (verified in the code):
#   * The five realities are compared by src/engine/reality.ts over records read through the data layer
#     (src/lib/realityData.ts) each time a person opens Reality or the Command Centre, or asks NUMI.
#     Nothing runs on a schedule. No database function makes the comparison, and no difference is stored
#     unless a person opens a case on it. The database holds the materiality thresholds, the cases, the
#     verifications, the confirmations, the reclassifications and the allocations.
#   * The comparison reads eight chains only: purchase, sale, advance, fixed asset, cash box, stock, bank and
#     verification sheet. What a requirement lists beyond these chains has no reading and is recorded as not built.
#   * The physical reality of Reality health reads the verification written to the history of a fixed asset,
#     the cash counts recorded on the Cash screen, the orders whose goods were received, and the last completed
#     verification sheet of stock and of cash of each place (Reality > Physical verification). The last completed
#     sheet of documents is read in the document reality. A sheet is one check and, where it found items otherwise
#     than the books say, one difference: its amount is the size of the differences of its lines, by the rule of the
#     alert the sheet raises (sheetLineDifference), what is short and what is over being added and not netted. The
#     lines are read for the last sheet of each place where it found differences; where they cannot be read the
#     amount is the book value of the items that differ, and the reading says so. A sheet on which items were left
#     unchecked and none was found otherwise is counted neither as checked nor as agreeing, and is named under what
#     was not looked at. A sheet that is open or was cancelled is not read. A stock count made under Inventory is
#     not read, except to say whether any was made; a completed verification of stock says the same.
#     A sheet of assets is not read as a sheet: its results reach Reality asset by asset.
#   * Where a requirement lists several kinds or statuses and the tests exercise only some of them, the
#     status is IMPLEMENTED and the note names what the tests cover.
#   * The screens were exercised in the sample (in-browser) engine. No screen was driven against the live
#     database. The database functions are tested directly.
#   * The code between the screens and the database (src/api/supabase*.ts) has no automated test; it is
#     type-checked only. In the sample data every person holds every permission, so a gate on a screen cannot be
#     observed there and has no automated test. Where an entry rests on either, its note says so.
ENTRIES = [
    # (status, requirement number, evidence, notes)

    # ------------------------------------------------------------------ Reality
    ("PARTIAL", 575, "src/pages/Reality.tsx · src/pages/Verification360.tsx · src/engine/reality.ts · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql · supabase/migrations/0019_corrections_after_assessment.sql · tests/sql/phase3_control.sql T227 T228 T275 · tests/p3control.test.ts 'verifying assets records what was found and changes nothing in the books' 'a verification opened by mistake is cancelled with a reason; what was completed stays'",
     "Built: a verification of fixed assets started by a person for one company, for every active asset or for one category or one location; the sheet lists the assets from the register with their book value; each asset is recorded as located, transferred, damaged, missing or disposed, or left not checked with a reason given on completion; a note is required for every result other than located; on completion the result is written to the history of each asset checked, each asset not found as the register says raises an alert, and the register is not changed (tested with located and missing, T227, T228); a sheet opened by mistake is cancelled with a reason while it is open, keeps what was entered on it and raises nothing, and a completed sheet cannot be cancelled (the rule is the same for every subject; it is tested with a sheet of cash, T275, not with a sheet of assets); Reality reports an active asset whose last verification was not 'located' as a difference in the physical reality and counts the active assets that were never verified. Not built: anything periodic — no interval, no due date and no reminder for a verification, and nothing starts one; the results transferred, damaged and disposed are not covered by a test."),
    ("IMPLEMENTED", 1385, "src/pages/Reality.tsx · src/pages/Verification360.tsx · src/engine/reality.ts · src/api/demoControl.ts · src/api/supabaseP3.ts · supabase/migrations/0016_reality_control.sql · supabase/migrations/0019_corrections_after_assessment.sql · tests/sql/phase3_control.sql T227 T228 T229 T230 T275 · tests/p3control.test.ts 'verifying assets records what was found and changes nothing in the books' 'verifying cash: a difference above the threshold is raised as a priority, and the books still say what they said' 'a verification opened by mistake is cancelled with a reason; what was completed stays' 'what a verification of stock, cash or documents found reaches Reality; the last sheet of a place stands for it' 'a sheet on which items were left unchecked is not a check that agrees' 'what a sheet found is measured by the size of the difference, not by the value of what was looked at' 'a case opened on a line of a sheet is the case of that sheet in Reality'",
     "Physical verification is a tab of NUMERO Reality; it does not carry the name NUMERO VERIFY. A person starts a verification of fixed assets, of the stock of one location, of cash boxes or of documents on file. The sheet is prepared from what the books say; what was found is entered line by line (a result for assets and documents, a quantity for stock, an amount for cash); items left unchecked need a reason; completion raises an alert for each difference and changes nothing in the books. A sheet opened by mistake is cancelled with a reason while it is open: what was entered stays on it, nothing is raised from it, it cannot be opened again, and a completed sheet cannot be cancelled (tested in the database, T275, and in the sample engine, with a sheet of cash). Verification of assets and of cash is tested in the database and in the sample engine (T227 to T230). Preparing, filling and completing a sheet of stock or of documents has no automated test, so the status is IMPLEMENTED and not TESTED. For a document the verification records whether the document on file was located; the file is not examined. What a verification found reaches Reality: for assets through the history of each asset (see 575); for stock, cash and documents through the last completed sheet of each subject and place, which is counted in Reality health where every item on it was looked at or where it found items otherwise than the books say, and is a difference in the second case, measured by the size of what was found short or over (see 1459). A sheet that left items unchecked and found nothing otherwise is counted as neither and is named under what was not looked at. A case opened on a line of a sheet of stock, cash or documents is shown in Reality against the difference of that sheet, which then offers no second case; a case opened on a line of a sheet of assets is not shown against the difference of the asset, whose key names the asset and not the sheet. The engine is tested with sheets of stock, of cash and of documents made up for the test, and in the sample engine with a sheet of cash completed there and read by the loader of Reality. The call that cancels a sheet through the live data layer has no automated test, and the permission on the button (reality.manage) cannot be observed in the sample data."),
    ("IMPLEMENTED", 1389, "src/pages/Reality.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_control.sql T231 T232 T233 T234 · tests/p3control.test.ts 'a confirmation: NUMERO works out the balance, a person sends it and records the reply' 'between companies of the group the other side is read from its own books'",
     "Confirmations are a tab of NUMERO Reality; it does not carry the name NUMERO CONFIRM. For a bank account, a customer, a vendor, a loan, a fixed deposit, an investment or another company of the group, NUMERO works out the balance in the books as at a date and states its basis. A person records that the request was sent and how, the reply, an explanation or a dispute of a difference, that no reply came, or a cancellation with its reason. A reply that differs from the books raises one alert and can be taken into a case. For an investment the balance confirmed is the quantity held. Between companies of the group the other side is read from its own books where the person may read them. Tested: customer and intercompany (T231 to T234). Bank, vendor, loan, deposit and investment have no automated test, so the status is IMPLEMENTED and not TESTED. NUMERO sends nothing and produces no confirmation letter on this screen."),
    ("PARTIAL", 1454, "src/engine/reality.ts · src/lib/realityData.ts · src/pages/Reality.tsx · src/pages/Case360.tsx · src/ui/HomeBeyond.tsx · src/numi/p3.ts · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'five separate counts, never one score; and what was never checked is said' 'a sale in another currency is stated in the currency of the company' 'what a verification of stock, cash or documents found reaches Reality; the last sheet of a place stands for it' · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written' 'reality names what it may not read, and does not count it as agreeing'",
     "Built: NUMERO Reality sets five realities (document, operation, accounting, cash, physical) against each other in eight chains — purchase (order, receipt, bill, stock taken in, payment), sale (invoice, entry, money received; an invoice in another currency is stated in the currency of the company at the rate of the invoice), advance (approval, release, claims, return), fixed asset (register against the last verification), cash box (books against the last count), stock (stock ledger against general ledger), bank (statement lines unmatched for more than a week) and verification sheet (the last completed sheet of stock, cash or documents of each place against the books); each difference states the readings, the amount at stake and whether it is above the materiality threshold of its company; a person opens a case on it; cases, physical verification and confirmations are tabs of the same screen (the engine and the loader are tested). Not built: readings for what 1455 to 1459 list beyond these chains (contracts, agreements, policies, cards, wallets, payment gateways, work done, goods consumed, stock as counted in a stock count of Inventory, property and equipment outside the fixed asset register); comparison without a person opening a screen (1460); a record of the differences found — the comparison is calculated in the browser from the records read, and a difference is kept only when a person opens a case."),
    ("PARTIAL", 1455, "src/engine/reality.ts · src/lib/realityData.ts · src/pages/Reality.tsx · src/pages/Verification360.tsx · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'an advance: released above what was approved, held past its date, claimed without receipts' 'what a verification of stock, cash or documents found reaches Reality; the last sheet of a place stands for it' 'what a sheet found is measured by the size of the difference, not by the value of what was looked at'",
     "Built: the document reality reads the purchase order and the bills linked to it, the sales invoice, and the amount approved for an advance; whether each expense line claimed against an advance carries a receipt is read under the operational reality (tested for an order and for an advance); the last completed verification of documents of each scope is counted in the document reality where every document on it was looked at or where it found documents otherwise than recorded, and is a difference there in the second case, its amount being what the books carry for the documents not found as recorded, read from the lines of the sheet; a sheet that left documents unchecked and found none otherwise is counted as neither and is named under what was not looked at (tested with a sheet that found every document as recorded, and for the amount of one line of a sheet of documents; a sheet of documents that found differences, or that left documents unchecked, has no test — the rule is tested with sheets of stock and of cash). Not built: contracts, agreements and policies — they are register items and the comparison does not read them; receipts and other documents on file are not read for what they say (a verification of documents records whether a document was located, and Reality reads from its sheet how many were not, and the amount the books carry for them)."),
    ("PARTIAL", 1456, "src/engine/reality.ts · src/pages/Reality.tsx · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'an advance: released above what was approved, held past its date, claimed without receipts'",
     "Built: the operational reality reads what was received (confirmed goods receipts and service receipts against an order, compared in value, with the quantities stated in words), what was claimed as spent against an advance and how much of it carries a receipt, and the value of stock in the stock ledger (tested for receipts and for claims). What was ordered is read as the document reality of the order. Not built: delivered to a customer and sold as an operation — the sale chain reads the invoice, its entry and the money received, not a delivery or an issue of stock; built, worked, consumed and completed — no record of production, of time worked, of consumption or of completion is read, and manufacturing is not built."),
    ("IMPLEMENTED", 1457, "src/engine/reality.ts · src/lib/realityData.ts · src/pages/Reality.tsx · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written' · tests/p3control.test.ts 'a sale in another currency is stated in the currency of the company'",
     "The accounting reality is read in every chain: the bills of an order that carry an entry, the entry of a sales invoice, the amount of an advance recognised as expense through approved claims, the book value of an asset in the register, the book balance of a cash box on the date of its count, the balance of the stock ledger account in the general ledger, and the book value of what was on a verification sheet; for a bank account the reading says that no entry is matched to the statement lines. For bills and invoices the reading is taken from the link between the document and its entry, not from the lines of the ledger. One test builds an invoice without its entry and asserts the key and the amount of the difference it gives, not the reality that differs. No automated test asserts that the accounting reality is named as differing, for a bill or an invoice without its entry or for a stock ledger that differs from the general ledger; the test on the sample books asserts that the stock ledgers agree. The status is therefore IMPLEMENTED and not TESTED."),
    ("PARTIAL", 1458, "src/engine/reality.ts · src/lib/realityData.ts · src/pages/Reality.tsx · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'an advance: released above what was approved, held past its date, claimed without receipts' 'what a sheet found is measured by the size of the difference, not by the value of what was looked at' 'a case opened on a line of a sheet is the case of that sheet in Reality' · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written'",
     "Built: bank — statement lines imported from a file and not matched to the books for more than a week are reported per bank account, and a bank account with no statement imported is named as never checked; cash — the last count of each cash box against its book balance, and the last completed verification of cash of each scope against the books (both reported as a difference in the physical reality, the sheet by the amount found short or over and not by the balance of the box), and a cash box never counted is named; for an order, an invoice and an advance the cash reading is the payment, the receipt, the release and the return as recorded in NUMERO, an invoice in another currency being stated in the currency of the company (tested for an order, an advance, a cash box and a sheet of cash: a box of 5,000 found 200 short is a difference of 200, in the engine and, with a sheet completed in the sample engine, through the loader of Reality). Not built: cards, wallets and payment gateways — they have no reading; the payment of one order or the receipt of one invoice is not traced to its line on the bank statement (the statement is compared per bank account only); no bank is connected."),
    ("PARTIAL", 1459, "src/engine/reality.ts · src/lib/realityData.ts · src/pages/Reality.tsx · src/pages/Verification360.tsx · tests/p3control.test.ts 'goods received but not taken into stock differ in the physical reality' 'five separate counts, never one score; and what was never checked is said' 'physical reality counts what it can find to differ: orders whose goods were received are among those checked' 'what a verification of stock, cash or documents found reaches Reality; the last sheet of a place stands for it' 'a sheet on which items were left unchecked is not a check that agrees' 'what a sheet found is measured by the size of the difference, not by the value of what was looked at' 'stock that a verification looked at is not reported as never counted' 'a case opened on a line of a sheet is the case of that sheet in Reality' · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written'",
     "Built: fixed assets — the result of the last physical verification of each active asset against the register (equipment and property are covered only where they are in the fixed asset register); cash — the last count of each cash box against the books; goods received against an order and not taken into stock, the orders whose goods were received being counted among those checked; stock and cash as verified — the last completed verification sheet of the stock of each location and of cash of each scope is counted as checked where every item on it was looked at or where it found items otherwise than the books say, and is one difference in the second case, with the number of items and the size of the differences: for stock the quantity short or over at the book value of a unit, for cash the amount short or over, by the rule of the alert the sheet raises, and it is that size which is measured against the threshold (tested with sheets of stock and of cash: a cash box of 5,000 found 200 short is a difference of 200; an earlier sheet of the same place, an open sheet and a cancelled sheet are left out); a sheet on which items were left unchecked and none was found otherwise is counted neither as checked nor as agreeing, and is named, with the number of items left, under what was not looked at (tested); active assets never verified, cash boxes never counted and stock never counted are named as not checked, and stock counts as looked at once a stock count of Inventory or a verification of stock has been completed (tested); a case opened on a line of a sheet is shown against the difference of that sheet (tested with a sheet of cash). Not built: inventory as counted in a stock count of Inventory — it records what was found and raises its own alerts, and its differences do not enter Reality; a difference for each item of a verification sheet — a sheet is one difference, in which what is short and what is over are added and not netted, and the items are on the sheet; where the lines of a sheet cannot be read its amount is the book value of the items that differ, and the reading says so; the statement that stock was never counted is made for all the companies read together, so one verification of the stock of one location ends it for every location and company; a case opened on a line of a sheet of assets is not shown against the difference of the asset; property and equipment recorded as register items. The reading of the lines through the live data layer has no automated test."),
    ("PARTIAL", 1460, "src/engine/reality.ts · src/lib/realityData.ts · src/pages/Reality.tsx · src/ui/HomeBeyond.tsx · src/ui/RealityNote.tsx · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written' · tests/p3control.test.ts 'a difference keeps its key while what differs changes, so its case stays with it'",
     "Built: the five realities are compared with each other each time a person opens Reality, the Command Centre or a report of the library, or asks NUMI, from the records as they stand at that moment; a difference carries the key of its record — the order, the invoice, the advance, the bank account, the stock ledger — which stays the same while the realities that differ change, so that a case opened on it is found again the next time (tested for an order). For a fixed asset, a cash box and a verification sheet the key names the verification, the count or the sheet: a later verification, count or sheet that also differs is a new difference, and the case opened on the earlier one is not shown against it. Not built: continuous comparison — nothing runs on a schedule, no difference is stored, raised as an alert or sent as a notice by itself, and a difference that nobody looks at reaches nobody; only a purchase of goods in a company that keeps stock is read in all five realities, the other chains in two to four."),
    ("TESTED", 1461, "tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'when everything agrees there is nothing to report' · tests/sql/phase3_control.sql T223 · src/engine/reality.ts · src/pages/Reality.tsx",
     "An order of 100 units, billed and paid in full, with 82 units received, is reported as one difference: the operational and the cash reality differ, the amount at stake is the value of the 18 units, and the readings of the order, the receipt, the bills posted and the payment are shown side by side with the records linked. The comparison is made on values; the quantities are stated in the words of the reading, and a difference in quantity alone, with equal values, is not reported. The difference is titled 'Order …: the operation, cash do not agree'; the words REALITY DOES NOT RECONCILE do not appear on the screen."),
    ("PARTIAL", 1462, "src/pages/Reality.tsx · src/pages/Case360.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_control.sql T222 T223 T224 T225 · tests/p3control.test.ts 'a case: the same difference is one case; status needs a note, closing needs the resolution; history is kept'",
     "Built: a case opened on a difference copies its readings, its explanation, its amount and its linked records, and the same difference opened again returns the same case (tested, T223); for a purchase the records linked are the order, the receipts (GRN), the bills and the stock documents; a person adds further links by hand (invoice or bill, purchase document, advance, claim, fixed asset, accounting entry, stock document, stock item, bank account, cash box, loan, verification, confirmation, party, ledger) and attaches files to the case; the history of a case cannot be rewritten (T225). Not built: the payment, the accounting entry, the vendor, the approvals and the documents are not linked by NUMERO when the case is opened — the vendor is shown on the difference and is not carried into the case; a payment and an approval request cannot be chosen as a link; a link cannot be removed."),
    ("PARTIAL", 1464, "src/engine/reality.ts · src/pages/Reality.tsx · tests/p3control.test.ts 'five separate counts, never one score; and what was never checked is said' 'physical reality counts what it can find to differ: orders whose goods were received are among those checked' 'what a verification of stock, cash or documents found reaches Reality; the last sheet of a place stands for it' 'a sheet on which items were left unchecked is not a check that agrees' · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written' 'reality names what it may not read, and does not count it as agreeing'",
     "Built: five separate panels — document, operational, accounting, cash and physical match — each with the number checked, agreeing and differing and the method of counting written under it; the same five counts company by company; what was never checked and what the person may not read are listed beside the panels and counted in none of them; no composite score is calculated (tested). The physical match counts as checked the assets verified, the cash boxes counted, the orders whose goods were received and the last verification sheet of stock or cash of each place, and its method names all four; the document match counts the last verification of documents (tested). A verification sheet counts as a check that agrees only where every item on it was looked at and found as the books say; a sheet on which items were left unchecked and none was found otherwise is counted neither as checked nor as agreeing, and is listed, with the number of items left, under what was never checked (tested). Not built: a count that takes each place once — a cash box that was counted on the Cash screen and is also on a verification sheet of cash is counted twice, once as a box and once as a sheet; the method names both kinds of check and does not say that one box can be counted under each."),
    ("IMPLEMENTED", 1465, "src/engine/reality.ts · src/pages/Reality.tsx · src/pages/Control.tsx · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_control.sql T220 T221 · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written'",
     "Every difference belongs to one company and is measured against the materiality threshold of that company (the threshold is tested, T220, T221) — where the company has none set, every difference counts as material, and Reality, the Command Centre and the strip on reports say so (no automated test); Reality health shows the five counts of each company from the records of that company alone; cases, verifications and confirmations belong to a company and are read under the permissions held in it. It is one engine applied to each company: the chains and the tolerance (one unit of currency) are the same for all, and only the threshold is set per company. The counts per company are calculated on the screen and have no test of their own."),
    ("IMPLEMENTED", 1466, "src/lib/realityData.ts · src/pages/Reality.tsx · src/ui/HomeBeyond.tsx · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written' 'reality names what it may not read, and does not count it as agreeing'",
     "Reality reads every company selected in which the person holds reality.view: the differences of all those companies in one list, the largest amount first, with a filter by company; the cases of all those companies in one list; and a line for the whole selection in Reality health, where the counts of the companies are added and never netted. Companies the person may not read are named as left out. A Group Super Admin reads every company. Amounts are listed in the currency of each company and are not converted, so the order of the list mixes currencies where the companies keep their books in different currencies. The loader is tested over all companies of the sample books; no test asserts the list by company."),
    ("TESTED", 1468, "src/engine/reality.ts · src/pages/Reality.tsx · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'when everything agrees there is nothing to report' 'five separate counts, never one score; and what was never checked is said' · tests/p3app.test.ts 'reality names what it may not read, and does not count it as agreeing'",
     "For each chain NUMERO asks the questions it holds records for — does the document agree, the operation, the accounting, the cash, the physical world — and reports where the answers differ, with each reading in words. A reality that was not read is named as not read and is never counted as agreeing; what was never verified or counted is listed (tested). Only a purchase of goods in a company that keeps stock is asked all five questions; the other chains are asked two to four. NUMERO states the difference and does not say what it means: that is recorded by a person in a case."),
    ("TESTED", 1489, "src/engine/reality.ts · src/pages/Reality.tsx · src/pages/Case360.tsx · src/numi/p3.ts · tests/p3control.test.ts 'five separate counts, never one score; and what was never checked is said' · tests/p3app.test.ts 'reality: five separate counts, the differences the sample holds, and nothing written' 'reality: five counts, stated as facts'",
     "Document, operational, accounting, cash and physical reality are kept as five separate dimensions in the engine, on the panels of Reality health, in the readings of each difference, in the readings stored with a case and in the answer of NUMI. They are not added into one figure (tested)."),
    ("PARTIAL", 1557, "src/pages/Cash.tsx · src/pages/Expenses.tsx · src/pages/Control.tsx · supabase/migrations/0008_expenses_advances_cash.sql · supabase/migrations/0016_reality_control.sql · tests/sql/phase2_flow.sql T46 T47 T64 T65 · tests/sql/phase2_corrections.sql T134 · tests/sql/phase3_control.sql T236 T237",
     "Built: bank to bank, bank to petty cash or cash box, cash to bank and cash to cash box as fund transfers between bank and cash ledgers, which touch neither income nor expense (T64); company to company as a transfer with one entry in each company through their intercompany ledgers (T65); advances released from a bank or cash ledger to an employee, a department, a project, a site, for travel, for procurement and to a vendor, held in an advances ledger and not in expenses (T46, T47, T134); department to department, project to project and cost centre to cost centre as an allocation that moves an amount of an income or expense ledger between units of one kind through an approved entry (T237, tested from the part of the ledger that names no unit). Not built: bank to corporate card as a movement of funds (a transfer accepts bank and cash ledgers only); branch to branch and office to office as movements of funds (a transfer names ledgers, not units); kinds of movement that an administrator configures — the kinds are fixed in the engine, and a workflow of the Scenario Studio moves nothing."),
    ("TESTED", 1581, "src/pages/Control.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_control.sql T235 · tests/p3control.test.ts 'a reclassification leaves the original entry as it is and keeps the reason'",
     "A reclassification never changes the posted line. It proposes a new entry that moves the amount to the other ledger, carrying the party and the units of the original line, and that entry is posted only when a second person approves it. The record keeps the original ledger, the new ledger, the amount and its side, the reason (required), who asked and when, the date, and both entries; the approval is kept on the new entry, and the screen states the accounting effect. Bank, cash, party, tax and intercompany ledgers are refused, and no more than the line carries can be moved (tested, T235). The rule is the same for every role. A reclassification changes the ledger only; the department or project of a posted line is changed by an allocation or by a new entry. An amount can also be moved between ledgers by a hand-written journal, which is approved like any entry and carries its narration, not a reclassification record."),
    ("PARTIAL", 1676, "src/engine/reality.ts · src/ui/RealityNote.tsx · src/pages/ReportView.tsx · src/lib/realityData.ts · tests/p3control.test.ts 'a report states the reconciliation of the records it rests on, and of no others' 'the reconciliation of a report is that of its period'",
     "Built: every report of the library — profit and loss, balance sheet, cash flow, trial balance, consolidation, financial health, where the money went and where it came from, ageing, cash and bank book, sales and purchase registers — shows under its heading a strip named Reconciliation. It takes, from the differences NUMERO Reality finds in the companies selected, those of the chains the report rests on (REPORT_REALITY; a report of money also takes every record whose cash reality differs) and of the period of the report — for a report as at a day (balance sheet, ageing, consolidation), every record up to that day — and states how many there are, how many of them are above the threshold of their company (where a company concerned has no threshold set, it says that there every difference counts as above it; this sentence has no automated test), the number by chain, the three largest with the case opened on each, what was never looked at, what the person may not read and the companies left out; it says which records it speaks of and that how many records were checked in each reality is shown in NUMERO Reality, for the books as a whole. It opens NUMERO Reality on those differences, chain by chain, and changes no figure of the report. A person without reality.view is told that the status is not shown; where Reality is switched off the strip is not shown. Which differences belong to which report, and to which period, is tested (realityOfReport). Not built: the status as it stood at the end of the period — the records of the period are compared as they stand on the day the report is read, and the strip says so; a record is placed in a period by one date — an order or an invoice by the date of the document, an advance by its release, a bank account by its oldest statement line unmatched (it is shown on every report that ends on or after that date, since the lines may fall in any later period), a stock ledger that does not agree with the books on every report (it stands, and is dated the day of the comparison) — tested; what was never looked at and what the person may not read are said for the books as a whole, not for the period; the strip is not printed and is not in the CSV export; the reports outside the library (Forward, Analysis with its burn rate and year on year, People Cost, Cockpit, Money Map) do not show it. The strip itself has no automated test: the tests cover the choice of differences, and the loader is tested under 1454. It has not been driven against the live database."),
    ("PARTIAL", 1729, "src/engine/reality.ts · src/pages/Reality.tsx · src/pages/Advance360.tsx · src/pages/FlowCase360.tsx · tests/p3control.test.ts 'an advance: released above what was approved, held past its date, claimed without receipts' 'an advance with no date set for settling it is reported once it has been held thirty days'",
     "Built: for every advance released, Reality sets against each other the amount approved, the money released and returned, the expense lines claimed and how many of them carry a receipt, and the amount recognised as expense through approved claims; it reports more released than approved, claims without a receipt, money still held after the expected settlement date or, where no date was set, more than thirty days after the release, and more settled and returned than released (tested for all but the last). Not built: the release and the return are not compared with the bank statement or with a cash count — they are the amounts recorded in NUMERO; actual use is what was claimed and is compared with nothing else; the thirty days are fixed in the engine and cannot be set; a case of a Scenario Studio workflow shows the record of each step as a link and reconciles nothing."),

    # ------------------------------------------------------------------ General
    ("IMPLEMENTED", 200, "src/pages/ClaimEditor.tsx · src/api/demoOpsB.ts · supabase/migrations/0018_platform.sql · tests/sql/phase3_platform.sql T265 · tests/p3control.test.ts 'a booking on a claim line: its parts must add up to the line'",
     "A line of an expense claim can carry a booking of kind train or bus with the operator (labelled 'Train' for a train), the booking reference, from, to, class, date of travel, booked through, and the amount made up of base fare, taxes, booking charges and cancellation fee (and meals for a train). The parts, where given, must add up to the line (check_travel_detail). All eight fields of the requirement are offered for both kinds; none is required, and the text fields are stored as typed. Tested with a train booking only: T265 stores operator, reference, route, class and the three parts, and asserts the reference and the sum of the parts. A bus booking has no test, so the status is IMPLEMENTED and not TESTED. A booking is recorded on an expense claim only; the bill of a travel agent cannot carry it."),
    ("TESTED", 476, "src/engine/analysis.ts · src/pages/Analysis.tsx · src/numi/p3.ts · tests/p3control.test.ts 'year on year: a year that is not complete is compared as it stands, never scaled up' · tests/p3app.test.ts 'year on year: a year that is not complete is said to be incomplete'",
     "Financial years are set side by side for as many years as the books hold, from the monthly totals of posted entries: revenue, cost of goods sold, gross profit, employee costs, other operating expenses, operating profit, profit before tax, tax and profit after tax, with the change in amount and in per cent on the year before. A year that is not complete is marked with its number of months and is not scaled up. Companies are added together only where they share a currency and a financial year. Limits: lines of the profit and loss only, no balance sheet; other income, depreciation, finance costs and exceptional items are shown as one net line; a figure does not open the ledgers behind it."),
    ("TESTED", 479, "src/engine/analysis.ts · src/pages/Analysis.tsx · src/numi/p3.ts · tests/p3control.test.ts 'burn rate: cash falling is measured, cash rising is said, too little data is refused' · tests/p3app.test.ts 'burn rate is an average of what happened, not a forecast'",
     "Monthly burn = (cash at the start − cash at the end) ÷ months measured, over the last 3, 6 or 12 completed months of the cash and bank ledgers, with the months of cash left at that rate. Where cash rose the screen says that the company is not consuming cash and gives no runway; with fewer than three months of balances no rate is given (tested). It is the net burn; a gross burn is not calculated. The figure is an average of what happened, marked ESTIMATE, and is not a forecast."),
    ("PARTIAL", 608, "src/engine/analysis.ts · src/pages/Analysis.tsx · src/pages/Notifications.tsx · src/pages/Case360.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql · supabase/migrations/0019_corrections_after_assessment.sql · tests/p3control.test.ts 'who attends to what: the rule of the group decides, and the owner is shown only what needs the owner' 'the owner is not told of every approval that waits: only of what the rules class for the owner' 'the class of an alert is worked out from its difference where it carries no amount, whichever way it points' · tests/sql/phase3_platform.sql T253 T276 T277",
     "Built: the five classes — information, finance action, management action, owner action, critical — on every notice and every case, and worked out for every open alert; rules by kind of notice and amount, set by a Group Super Admin under Notifications › Rules; Analysis › For the owner shows in full what is classed owner action or critical and keeps the other classes folded (the classing function is tested); of an approval that waits, a Group Super Admin is sent a notice only when the rules of the group class it as owner action or critical, or when no other person could approve it, while the inbox of approvals still shows every request (tested in the database, T276, and in the sample engine, where a rule is saved and its effect on the notice is asserted); the class of an alert is worked out from its amount or, where it carries none, from its difference, by its size whichever way it points, in the database, in the sample engine and on the owner view alike (tested, T277). Without a rule no alert and no approval is classed as owner action. Not built: holding back what is not an approval newly waiting — a Group Super Admin is sent a notice of every alert of priority or critical seriousness in every company, whatever class the rules give it (the person can switch off the notices of priority alerts, not those of critical ones), and once an approval has waited more than three days the notice of that (management action, not to be switched off) is written for every person who could decide it, the owner among them, whatever its class (both are recorded as limits, not corrected); a rule does not change the class of notices already raised, so after a rule is changed the class on a notice and the class the owner view works out for the same alert can differ; the screen on which a rule is saved has no automated test."),
    ("TESTED", 775, "src/engine/analysis.ts · src/pages/Analysis.tsx · tests/p3control.test.ts 'an unusual entry is measured against its own ledger and explained, not accused'",
     "For each ledger the entries of the chosen period are measured against the median of that ledger, in units of the median distance from it (score = 0.6745 × (amount − median) ÷ spread). An entry at or above the chosen score is listed with the usual amount, the spread, the number of entries compared and a sentence that says why it is unusual and that whether it is in order is for a person to say (tested). Limits: only entries above the usual are listed; the comparison is by ledger, not by party, department or season; at most the latest 5,000 posted lines of the period are examined, and the screen says when some were not; a ledger with too few entries is not judged; the result is shown when a person opens the screen and raises no alert."),
    ("IMPLEMENTED", 780, "src/pages/Reality.tsx · src/pages/Case360.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_control.sql T224 T225 T226 · tests/p3control.test.ts 'a case: the same difference is one case; status needs a note, closing needs the resolution; history is kept' 'an alert under a case follows the case'",
     "A case has the eight statuses open, triage, under review, investigating, substantiated, unsubstantiated, remediated and closed. Every change records what was found or decided; closing needs the resolution; a closed case moved to another status is recorded as reopened; the history cannot be rewritten or removed. Tested: open, investigating, substantiated, unsubstantiated and closed (T224, T226). Triage, under review and remediated pass through the same rule and are set in no test, so the status is IMPLEMENTED and not TESTED. No order of statuses is enforced: a case may move from any status to any other. A case raised from an alert or as an incident is worked under the permission sentinel.review, a case of every other kind under reality.manage, in the database and on the screen alike: the screen of the case enables its controls on the permission of its kind, and the form that opens a case offers the kinds the person may open in the company chosen. These gates on the screen have no automated test: in the sample data every person holds every permission."),
    ("TESTED", 1245, "src/pages/Control.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_control.sql T236 T237 · tests/p3control.test.ts 'an allocation shares out what the ledger holds, explains itself, and leaves the total unchanged'",
     "An allocation made under Control › Allocations records and shows its source (the ledger, and the unit that holds the amount or the part of the ledger that names no unit), the amount and the pool it is taken from, the driver (headcount, revenue, area, usage, equal shares or manual shares) with a note of what it rests on, the formula in words with its figures, each recipient with its driver value, share and amount, and the period. The entry it proposes is posted only after approval and leaves the total of the ledger unchanged (tested, T236, T237). The note on the driver is required for manual shares only. The values of a driver are typed by a person: NUMERO does not read headcount, revenue or area from the books. A cost moved between units by a hand-written journal carries its narration and none of these particulars."),
    ("TESTED", 1354, "src/engine/analysis.ts · src/pages/Analysis.tsx · tests/p3control.test.ts 'deadlines across companies'",
     "Analysis › Compliance deadlines lists the active register items of kind compliance, and of other kinds when ticked, that carry a due date, across every company whose registers the person may read: overdue, this week, this month and later, by company and as one list, each opening its register item (tested). It shows the deadlines that people have recorded; NUMERO holds no calendar of statutory dates. A deadline is recorded as met on the register item, not on this screen. Companies whose registers the person may not read are named, and items without a due date are counted and said to be missing from the list."),
    ("PARTIAL", 1363, "src/pages/Companies.tsx · src/pages/Genesis.tsx · src/pages/Imports.tsx · src/engine/templates.ts · supabase/migrations/0018_platform.sql · tests/sql/phase3_platform.sql T261 T262 T263 · tests/engine.test.ts 'company templates always include the control accounts they map'",
     "Built: a new company enters NUMERO through a wizard of four steps run by a Group Super Admin (identity; what the business does, with a recommended template; review of the chart of accounts, tax codes, units and capabilities; confirmation), or as a clone of the configuration of an existing company; its structure, custom fields, party types and tax codes are then set in the Genesis Builder; opening balances are brought in from a file as one draft entry that goes through approval, and the trial balance of the earlier system is kept beside the books (the import is tested, T261 to T263). Not built: one controlled path named Genesis that takes a new company through opening position, import, validation and readiness in order and records how far each company has come — the wizard ends when the company is created, and opening balances and imports are separate screens that a person opens afterwards; the name Genesis is carried by the configuration screen; the capabilities ticked in the wizard are stored with the company and open or close no screen — the switches are set apart, under System Health › Capabilities."),
    ("TESTED", 1370, "src/engine/analysis.ts · src/pages/Imports.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql · tests/sql/phase3_platform.sql T263 · tests/p3control.test.ts 'the books of the earlier system beside NUMERO: ledger by ledger, and ready only when nothing differs'",
     "While both systems are kept, the trial balance of the earlier system is brought in from a CSV file for a date, kept beside the books without posting anything (T263), and compared with the closing balances of NUMERO at that date, ledger by ledger: agrees, differs, not mapped, only in NUMERO, within a tolerance the person sets (tested). Each committed file is one comparison, so a month end is compared by bringing in its trial balance. Limits: closing balances by ledger only — movements, balances by party, tax, stock and assets are not compared; NUMERO's side is shown to a person who holds report.view; income and expense ledgers carry everything since the first entry, not one financial year."),
    ("PARTIAL", 1513, "src/pages/Features.tsx · src/engine/features.ts · src/voice/gateway.ts · src/pages/Genesis.tsx · src/api/demoInventory.ts · src/pages/Notifications.tsx · src/pages/Control.tsx · src/App.tsx · src/ui/Shell.tsx · src/numi/NumiPanel.tsx · src/pages/Companies.tsx · tests/p3app.test.ts 'a switch governs its screens wherever they are reached from'",
     "Built: a search of src for TODO, FIXME, 'coming soon', 'not implemented' and 'not yet implemented' finds nothing, and a search for empty click handlers finds none; the screens of Phase 3 state what they do not do — Capabilities lists the limits of each capability and marks as partial those whose limits name parts not built, Reality, Inventory, Reports, Sales & Billing, Investments & Funds and the Genesis Builder among them, and the controls that only record (notification channels other than the application itself, the percentage recorded with a materiality threshold, the triggers of a workflow) say so on the screen; the empty method wfStock, which nothing called, is no longer in src/api/demoInventory.ts. The switch of a capability governs its screens whichever way they are reached — menu, address, command or voice — through a lookup of the screen by its address (the lookup is tested; the gate on the screens is not), and the switches of NUMI and of voice hide the button, the key and the orb that open them. Not built: two things found in the source — the Sarvam speech provider in src/voice/gateway.ts is a placeholder that reports itself not connected and is never chosen, with empty speak and cancel methods; custom fields can be defined in the Genesis Builder for journals, payments, organisation units and companies, and no screen shows or saves their values (the screen marks them 'not yet shown', and the Capabilities list says so). Controls that do nothing: the capabilities ticked in the company wizard are stored with the company and switch no screen on or off, and the wizard does not say so (the switches are set under System Health › Capabilities); with NUMI switched off, the questions and buttons that ask NUMI on the Home screen, the Cockpit, the command palette, a party, a journal and a report are still offered; asking says that NUMI is switched off and opens nothing. No automated test searches the source for placeholders."),
    ("TESTED", 1678, "src/engine/analysis.ts · src/pages/Analysis.tsx · src/lib/realityData.ts · src/pages/Reality.tsx · src/ui/p3.tsx · src/pages/ReportView.tsx · src/ui/RealityNote.tsx · src/ui/HomeBeyond.tsx · tests/p3control.test.ts 'burn rate: cash falling is measured, cash rising is said, too little data is refused' 'year on year: a year that is not complete is compared as it stands, never scaled up' · tests/p3app.test.ts 'reality names what it may not read, and does not count it as agreeing' 'the twin names what it may not read'",
     "Where the records are not enough, the screen says so instead of giving a figure: no burn rate from fewer than three months of balances; a part year is marked with its number of months and is not scaled up; a source the person may not read is named and left out of the counts; what was never verified or counted is listed and not counted as agreeing; the unusual-entries screen states how many lines were not examined; figures worked out by a formula are marked ESTIMATE (tested for the burn rate, year on year, Reality and the twin). The reports mark a range with a period that is not locked as PROVISIONAL and state the entries the person is not cleared to see. The reports of the library now carry the reconciliation of the records they rest on (see 1676): it counts among the differences the bank accounts with statement lines unmatched for more than a week, says what was never looked at — bank accounts with no statement imported among it — and what the person may not read, and says that what was never checked is not counted as agreeing; it speaks of the records of the period of the report as they stand on the day it is read, says so, and is not printed. Where a company has no materiality threshold set, the Command Centre, Reality and that strip say that there every difference counts as material, instead of speaking of a threshold that does not exist; these sentences on screens have no automated test. A warning on a report of missing documents or of a stale import belongs to requirement 1677 and is not shown on the reports."),
    ("PARTIAL", 1799, "src/pages/TwinParts.tsx · src/pages/Sentinel.tsx · src/pages/Genesis.tsx · src/engine/analysis.ts · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql · tests/p3control.test.ts 'a rule is tried against what is already on record before it is put in force' 'an alert under a case follows the case' · tests/sql/phase3_control.sql T226",
     "Built: an alert is closed as a false positive by a person, with a note, in Sentinel or when its case is found unsubstantiated (T226); Digital Twin › Rules tries a threshold against the alerts of one kind on record and states how many would still be raised and how many of those closed as not a concern would be spared (tested); the amount of a large payment and the unit of round-number journals are changed by a Group Super Admin in the Genesis Builder › Controls, and the screen of the trial names these places: approval rules under Approvals, the thresholds of Sentinel in the Genesis Builder. Not built: adjustment from the review — the threshold tried is forgotten and changes nothing; the other rules of Sentinel have no setting that an administrator can change; no list of false positives by rule leads to a change of that rule."),
    ("PARTIAL", 1887, "src/pages/Genesis.tsx · src/pages/Companies.tsx · src/pages/Control.tsx · supabase/migrations/0001_core_tenancy_audit.sql · supabase/migrations/0002_ledger_engine.sql · supabase/migrations/0014_inventory.sql",
     "Built: permissions are held company by company, so a person whose role in one company includes orgunit.configure, account.configure, tax.configure or approval.configure sets up the units of that company (branches, departments, cost centres, projects), its chart of accounts, its tax codes and its approval rules, and the database refuses a person without the permission; custom fields and workflows can be made for one company; the materiality threshold is set per company. Not built: a role named Company Admin — the roles that hold these permissions are Owner, Group CFO and Finance Head; a unit can be created and cannot be renamed, moved or switched off on the screen; new levels of structure, party types and capability switches, and creating, cloning or archiving a company, are for the Group Super Admin only. No automated test covers the configuration of units by permission."),
]
PLANNED = {
    # requirement number: why it is not built
    1899: "The comparison reads eight fixed chains (purchase, sale, advance, fixed asset, cash box, stock, bank, verification sheet). A workflow of the Scenario Studio, a custom field or a register kind added by an administrator is not read by it, and the Capabilities list says so. A step of a workflow can point to a case under Reality, and a case of kind 'other' can be opened by hand; neither is a reconciliation.",
    1826: "No department can be cloned. A department is an organisation unit created one at a time in the Genesis Builder › Structure (level, code, name, the unit it reports to, confidentiality); it carries no configuration of its own and cannot be copied or edited there. Cloning a company (Companies › Clone configuration) copies its active units, departments among them, into the new company. The Scenario Studio clones a workflow, not a department.",
    1886: "There is no Department Admin and nothing is configured per department. Roles and permissions are held per company, not per department; the Department Head role reads, requests and approves, and configures nothing. Custom fields, expense categories, approval rules and workflows are defined for the group or for a company.",
}
