# Records of phases 1 and 2 brought up to date after phase 3 — part 5. Assessed against the code on 2026-09-27.
#
# Each record in UPDATES replaces the record of the same number in docs/requirement-status.json (or, for a
# requirement that was PLANNED, its reason in docs/requirement-planned-notes.json). What the earlier record said and
# is still true is carried over; what Phase 3 added is named as such. No status was lowered.
# A record that was PLANNED with no note (Phase 1, never assessed one by one) says what Phase 3 added, and names what
# earlier phases hold only where that was read in the code or is recorded under another requirement.
#
# Facts that apply to many records below (verified in the code):
#   * A workflow of the Scenario Studio (src/pages/Studio.tsx, src/pages/FlowDesigner.tsx, src/pages/FlowCase360.tsx,
#     supabase/migrations/0017_scenarios_flows.sql) is a straight line of steps of nine kinds — request, approval,
#     release of money, evidence, settlement, accounting, reconciliation, review, notice. It is started by a person
#     (triggers manual and form; ten others are recorded as intent). It posts nothing and releases nothing: a release,
#     settlement or accounting step is complete only when it points to the record that did it. Its money flow,
#     accounting, settlement, notifications, NUMI, Sentinel, reports and register kind are text that configures
#     nothing. Nineteen starting points are supplied, each with a form (six kinds of answer). A step raises no notice.
#   * Nothing runs on a schedule, nothing leaves the application, no outside system is connected.
#   * The sandbox (src/lib/sandbox.ts, src/pages/Sandbox.tsx) is the in-browser engine filled with a copy of the
#     configuration and of the balances; it copies no transaction, role or permission.
#   * Cross-cutting rules of the build (1482, 1484, 1497, 1518, 1526, 1551, 1554, 1555, 1916) are left as they were:
#     assessing them would mean assessing every module of every phase, which this reading did not do.
UPDATES = [
    ("PARTIAL", 1579, "src/engine/templates.ts · src/pages/Reality.tsx · src/pages/Case360.tsx · supabase/migrations/0016_reality_control.sql open_case · tests/sql/phase3_control.sql T222 T226",
     "Lowered from IMPLEMENTED on reading the record again after Phase 3. Built: no template holds a ledger or category for fraud (Phase 1); Phase 3 adds cases of the kinds incident and raised from an alert, linked to the entries and records concerned, with a history that can only be added to, opened only with sentinel.review (T222, T226); Sentinel and Reality never call anything fraud. Not built: nothing refuses a ledger or an expense category that a person names 'Fraud', and there is no ledger role for a suspected loss held apart from expense."),

    ("PARTIAL", 1641, "src/pages/Calculators.tsx · src/engine/analysis.ts burnRate · src/pages/Analysis.tsx",
     "Lowered from IMPLEMENTED on reading the record again after Phase 3. Built: break-even, contribution, margin, cash conversion cycle and runway in the Calculator Centre (Phase 1); Phase 3 adds burn rate and runway from the books under Analysis, with their formulas. Not built: a working-capital calculator, unit economics and pricing."),

    ("PARTIAL", 1640, "src/pages/Calculators.tsx · src/pages/TwinParts.tsx valuation lab · src/engine/twin.ts dcf",
     "Lowered from IMPLEMENTED on reading the record again after Phase 3. Built: the Calculator Centre computes ROI, CAGR and percentage change (Phase 1); Phase 3 adds, in the valuation lab of the Digital Twin, a discounted cash flow with its discount rate and terminal value, and scenario returns through the comparison of scenarios. Not built: IRR, XIRR, NPV of a stream typed by a person, payback and yield as calculators."),

    # (status, requirement number, evidence, notes)

    # ------------------------------------------------------------------ principles that Phase 3 extended
    ("PARTIAL", 1488, "src/pages/Sentinel.tsx · src/pages/Reality.tsx · src/pages/Case360.tsx · src/pages/Verification360.tsx · src/pages/Control.tsx · src/engine/analysis.ts unusualEntries · src/pages/Analysis.tsx · supabase/migrations/0016_reality_control.sql cases, case_events, verification_runs, confirmations, materiality · tests/sql/phase3_control.sql T220 T221 T224 T225 T226 T227 T228 T230 T232 · tests/p3control.test.ts 'a case: the same difference is one case; status needs a note, closing needs the resolution; history is kept' 'an alert under a case follows the case' 'an unusual entry is measured against its own ledger and explained, not accused'",
     "Built: Sentinel is more than duplicate detection since Phase 1 (eight rules run on demand, among them a reference used twice, a manual journal posted at a weekend or just below an approval threshold; since Phase 2 factual alerts raised at the moment of an event — recorded under requirement 40). Phase 3 adds the investigation and control parts: a case, opened on an alert, a difference or as an incident, with eight statuses, a note for every change, the resolution to close, a history that cannot be rewritten, linked records and attached files, and the alert under it following the case (T224 to T226); verifications of assets, stock, cash and documents and confirmations of balances from outside, each difference raising an alert (T227, T228, T230, T232); a materiality threshold per company that marks a difference as a priority (T220, T221); and, under Analysis, entries unusual for their own ledger found by the median and spread of that ledger and explained in a sentence that says it is for a person to judge (tested). Not built: continuous evaluation (the rules run when a person starts them, the analysis when its screen is opened); the watches of fund movements and of reclassifications (requirements 1710, 1711); rules an administrator can change beyond two thresholds."),

    ("PARTIAL", 1490, "src/ui/kit.tsx Truth · src/engine/types.ts TruthState · src/pages/Banking.tsx · src/pages/Forward.tsx · src/engine/forward.ts · src/pages/Budgets.tsx · src/ui/p3.tsx Simulated, Exposure, Estimate · src/pages/Twin.tsx · src/pages/Analysis.tsx · src/pages/Inventory.tsx · src/engine/stock.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T244 T245 · tests/p3control.test.ts 'a saved simulation is labelled SIMULATION, touches no entry, and cannot be relabelled' 'exposure is shown under one heading only, the most serious, and is never added to posted loss' · tests/p3app.test.ts 'a what-if is a SIMULATION, says what it assumed, and writes nothing' 'exposure is reported beside the loss that was posted, never inside it'",
     "Built: each of the ten states is a label of its own since Phase 1 (src/ui/kit.tsx: ACTUAL, RECONCILED, UNRECONCILED, COMMITTED, EXPECTED, FORECAST, AI ESTIMATE, SIMULATION, CONTINGENT, DISPUTED, besides BUDGET and PROVISIONAL); the bank reconciliation shows RECONCILED or UNRECONCILED, Forward keeps its certainties apart and marks its figures FORECAST, CONTINGENT or ESTIMATE, the budget screen sets BUDGET beside ACTUAL. Phase 3 adds figures of the state SIMULATION and keeps them out of the books: every result of the Digital Twin and every what-if answered by NUMI is marked SIMULATION beside base figures marked ACTUAL; a saved result is labelled SIMULATION in the database, touches no entry and cannot be relabelled, even by a privileged role (T244, T245); stock at stake is marked EXPOSURE and is never added to the loss that was posted (tested); the burn rate and the preview of a landed cost are marked ESTIMATE. Not built: DISPUTED is defined as a label and carried by no figure (a document can have the status disputed); no test asserts that the states of Phases 1 and 2 are kept apart in every total, and whether any total of those phases adds contingent or disputed amounts to actual ones was not assessed here."),

    ("PARTIAL", 1499, "src/pages/Companies.tsx · src/pages/Genesis.tsx · src/pages/Registers.tsx · supabase/migrations/0014_inventory.sql · supabase/migrations/0015_investments_funds.sql · supabase/migrations/0016_reality_control.sql · supabase/migrations/0017_scenarios_flows.sql save_flow_def, set_flow_status, clone_flow_def · supabase/migrations/0018_platform.sql integrations, save_integration · tests/sql/phase3_platform.sql T252 T257 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "Built: a company is added as data by a wizard (Phase 1); custom fields are defined with versions and register kinds with their own fields are added as data (Phase 2). Phase 3 adds: new modules — inventory, investments and funds, reality and control, scenarios and workflows, the platform — each brought by its own tables and its own handler of the posting engine, without the journal functions being defined again (recorded under requirement 85); workflows as data, in versions: a workflow in use is not edited, a change is its next version and a case keeps the version it started on (T252); integrations as records of a register, which holds intent and no secret (T257). Not built: a country is a code recorded on the company and no rule of NUMERO is chosen by it; no AI capability can be added (no model is connected and NUMI reads patterns written in the code); the migration files move forward only."),

    ("PARTIAL", 1517, "tests/sql/engine_invariants.sql T06 T10d T11e T11f T11g T16e · tests/numiOps.test.ts 'reports a refusal as a refusal and does not say whether records exist' · tests/sql/phase3_inventory.sql T168 T187 T189 · tests/sql/phase3_investments.sql T201 T205 T211 · tests/sql/phase3_control.sql T223 T235 T238 · tests/sql/phase3_platform.sql T244 T249 T254 T257 T258 T261 T262 T263 T266 T267 · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'notices: what falls due is found when a person opens the application, and finding it again adds nothing' · tests/p3app.test.ts 'stock is refused to a person without the permission, whatever the records hold' 'a list of the live books is read to its end'",
     "Built: automated tests cover accounting (balance, posting and reversal, since Phase 1), permissions, tenant isolation (a company cannot write into, use the accounts of or open the journals of another, T11e to T11g), approvals, audit (the trail is append-only, T10d), idempotency (a posting repeated returns the same voucher, T06; an invoice approved twice posts once, T16e) and AI boundaries (NUMI reports a refusal as a refusal). Phase 3 adds: integrations — the register holds no secret and guards what can move money (T257); migration — an import is checked before it enters the books, enters as drafts and the earlier trial balance is compared ledger by ledger (T261 to T263); security — every table has row level security and the internal functions cannot be called by a signed-in user (T266, T267); reconciliation — the comparisons of NUMERO Reality (tested); multi-company — a simulation refuses the figures of a company the person may not read (T244); idempotency — finding what falls due again adds no notice (T254), the same days of a management fee cannot be charged twice (T205), the same difference is one case (T223), the same file is not committed twice (T262); every entry posted by the Phase 3 suites balances (T189, T211, T238). Not built: concurrency — no test runs two sessions at the same time (stock awaiting approval on one document is refused on another, T168, one after the other); the live data layer between the screens and the database has no automated test apart from its two list readers; no test drives a screen; integrations are tested as a register only, since none is connected."),

    ("PARTIAL", 1541, "src/pages/Imports.tsx · src/engine/analysis.ts parallelRun · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql stage_import, commit_import, discard_import, backup_checks, record_backup_check · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T260 T261 T262 T263 · tests/p3control.test.ts 'an import is checked before it enters the books, and enters them as drafts' 'the books of the earlier system beside NUMERO: ledger by ledger, and ready only when nothing differs'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds, for data brought in from an earlier system under Imports: validate — the file is staged and checked (every row, duplicates, debits against credits, mapping of accounts) and a file that fails a check cannot be committed (T261); migrate — journals and opening balances enter the books as drafts that are approved like any other entry, and the same file is not committed twice (T262); verify — the trial balance of the earlier system is kept beside the books and compared ledger by ledger (T263); a staged file can be discarded with a reason. Backups made by the database provider can be recorded under System Health (T260). Not built: NUMERO makes no backup before an import (it keeps what a person records); a committed file cannot be rolled back as a whole — the database refuses to discard it and says that what was committed is corrected in the books; the migrations of the database schema carry no rollback and move forward only."),

    # ------------------------------------------------------------------ money movement and reclassification
    ("PARTIAL", 1556, "supabase/migrations/0008_expenses_advances_cash.sql approve_advance, release_advance, return_advance, save_claim, pay_claim, propose_fund_transfer · tests/sql/phase2_flow.sql T46 T47 T64 · src/pages/Control.tsx · supabase/migrations/0016_reality_control.sql wf_reclassification · supabase/migrations/0015_investments_funds.sql · src/pages/Studio.tsx ACTION_META · src/pages/FlowCase360.tsx · src/engine/reality.ts · tests/sql/phase3_control.sql T235 · tests/sql/phase3_platform.sql T250 · tests/p3.test.ts 'a capital call is a request, not money: approving it posts nothing' 'a distribution: entitlement by units, declaration before payment, tax withheld, a second person for each entry' · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing' 'an advance: released above what was approved, held past its date, claimed without receipts'",
     "Built: for an advance the approval, the release of the money, the expense claimed against it, its return and the payment of a claim are separate events, each with its own function, and an advance is not an expense (Phase 2, T46, T47); a fund transfer touches neither income nor expense (T64). Phase 3 adds: a reclassification is an event of its own, a new entry beside the original one, approved by a second person (T235); a capital call approved is a request, not money — approving it posts nothing, and the money received is recorded apart (tested); a dividend or distribution is declared, then paid holder by holder, each by its own approved entry (tested); in the Scenario Studio request, approval, release, evidence, settlement, accounting and reconciliation are kinds of step of their own, and the screen says of each what it is not (approval is not release; evidence is not expense; expense is not settlement); a release step is complete only when it points to the advance that released the money (T250); NUMERO Reality sets approval, release, claims and return of each advance against each other (tested). Not built: one universal engine of money movement and settlement — each kind of record carries its own events in its own code; a workflow records the events and moves nothing; an invoice is settled by its payments as in Phase 1, with no settlement record of its own."),

    ("IMPLEMENTED", 1570, "src/pages/Entry.tsx · src/pages/Cash.tsx · supabase/migrations/0008_expenses_advances_cash.sql fund_transfers, propose_fund_transfer · tests/sql/phase2_flow.sql T64 T65 · src/pages/Control.tsx · supabase/migrations/0016_reality_control.sql reclassifications, allocations, wf_reclassification, wf_allocation · tests/sql/phase3_control.sql T235 T236 T237 · src/pages/Budgets.tsx",
     "Recorded at Phase 1 as implemented (Entry › Transfer). A fund transfer between the company's own bank and cash ledgers is proposed and posted on approval, and states its kind — bank transfer, cash withdrawal, cash deposit, petty cash top-up, card payment, intercompany — so that a physical movement of cash is told apart from a bank transfer; it touches neither income nor expense (T64); between companies it makes one entry in each (T65). Phase 3 adds the two that were missing as records of their own, under Control: an accounting reclassification, a new entry that moves a posted amount to another ledger and leaves the original entry as it is (T235), and a cost allocation, which shares what a ledger holds between units by a driver and leaves the total of the ledger unchanged (T236, T237); each is proposed by a person with the permission and posted only on approval. A budget is changed by a revised version, approved like the first, which keeps the earlier version; that is how a budget is reallocated, and it moves no money and posts nothing. No test asserts the five side by side."),

    ("PARTIAL", 1571, "src/pages/Control.tsx ReclassTab · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql reclassifications, wf_reclassification · src/engine/templates.ts · tests/sql/phase3_control.sql T235 · tests/p3control.test.ts 'a reclassification leaves the original entry as it is and keeps the reason'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (an amount could be moved by a hand-written journal). Phase 3 adds Control › Reclassifications: a person who may create entries reclassifies a posted line to another active ledger of the company with a reason; the new entry carries the party and the units of the original line and is posted only when a second person approves it; no more than the line carries can be moved (T235). The classifications are the ledgers of the chart, so every heading of the list that the company keeps as a ledger (travel, meals, marketing, repairs, donation, suspense, write-off and any other) can be chosen. Not built: reclassification into or out of bank, cash, receivable, payable, tax and intercompany ledgers — refused, because they are corrected by reversing the source document — so the heading Intercompany of the list cannot be reached this way; an accounting policy that says which reclassifications are allowed (the refusal is fixed in the engine); a change of department or project (done by an allocation); a change of the category of an expense claim line or of another document (the ledger of the posted line is what changes)."),

    ("PARTIAL", 1580, "src/pages/Reality.tsx · src/pages/Case360.tsx LINK_KINDS · src/pages/Sentinel.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql cases, case_events, open_case, update_case · src/engine/registerKinds.json incident · tests/sql/phase3_control.sql T224 T225 T226 · tests/p3control.test.ts 'a case: the same difference is one case; status needs a note, closing needs the resolution; history is kept' 'an alert under a case follows the case'",
     "Built: an incident register item records an estimated loss and a recovery (Phase 2, recorded under requirement 319). Phase 3 adds the case: a case of the kind Incident, or raised from a Sentinel alert, is opened in NUMERO Reality and worked under the permission sentinel.review, with the statuses investigating, substantiated, unsubstantiated, remediated and closed, a note for every change and the resolution to close it; its history cannot be rewritten; files are attached as evidence; the alert under it follows the case (T224 to T226); a person links to it by hand the accounting entry that records the loss or its write-off, the invoice or bill, the advance, the claim, the asset, the stock document, the party or the ledger. Not built: the accounting treatment is not proposed from the case — a person writes the entry and links it; a recovery, an insurance claim or a legal action cannot be linked to a case (register items are not among the records a case links), and the incident register item is not tied to the case; the approved accounting policy for such a loss is not recorded anywhere."),

    ("TESTED", 1582, "src/pages/Control.tsx ReclassTab · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql reclassifications, wf_reclassification · tests/sql/phase3_control.sql T235 · tests/p3control.test.ts 'a reclassification leaves the original entry as it is and keeps the reason'",
     "Phase 3 built the reclassification, and it never changes the posted line: it proposes a new entry that moves the amount to the other ledger, posted only when a second person approves it; the record keeps the original ledger, the new ledger, the amount, the reason, who asked and when, and both entries (tested, T235). A posted entry cannot be edited since Phase 1, so an amount moved by a hand-written journal also leaves the earlier entry in place; such a journal carries its narration and no reclassification record. The test covers the reclassification of Phase 3; the rule for posted entries was not assessed again here."),

    # ------------------------------------------------------------------ reports
    ("PARTIAL", 1619, "src/pages/Reports.tsx · src/pages/ReportView.tsx · src/pages/Inventory.tsx · src/pages/Reality.tsx · src/pages/Analysis.tsx · src/pages/Fund360.tsx · src/pages/Investments.tsx · src/pages/Forward.tsx · src/pages/Budgets.tsx · src/pages/Audit.tsx · tests/sql/phase3_inventory.sql T186 · tests/p3control.test.ts 'deadlines across companies' 'five separate counts, never one score; and what was never checked is said'",
     "Built: the report library of Phase 1 — profit and loss, balance sheet, cash flow, trial balance, group consolidation, financial health, where the money went and came from, ageing, who owes us and whom we owe, general ledger, journal register and day book, cash and bank book, sales and purchase registers, budget against actual, audit trail — which covers accounting, management, AR, AP, bank, budget and audit reports and tax registers; Forward shows what is expected ahead. Phase 3 adds reports outside the library: inventory — value by category and item, set against the books (T186), exposure, loss posted by reason, reorder list; reality — Reality health and the differences between records (tested); investment — the statement of each investor of a fund and the group investment map; compliance — deadlines across companies (tested); analysis — year on year, burn rate and unusual entries. Not built: custom reports; project, property, commission, travel, vehicle, subscription, contract, NUMI and Truth reports as reports of their own; the reports of Phase 3 are screens with export, not reports of the library, and the other types listed were not assessed one by one here."),

    ("PARTIAL", 1649, "src/pages/Imports.tsx · src/engine/analysis.ts parallelRun · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql stage_import, commit_import · tests/sql/phase3_platform.sql T263 · tests/p3control.test.ts 'the books of the earlier system beside NUMERO: ledger by ledger, and ready only when nothing differs'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds one kind of external report: the trial balance of an earlier system is uploaded as a CSV file under Imports, checked, kept beside the books without posting anything, and compared with NUMERO ledger by ledger for migration and during a parallel run (T263, tested). Not built: the upload of any other report (profit and loss, balance sheet, a report of an auditor or of a board); a PDF or Excel report; storage of the report in the document system — the rows are kept in the tables of imports, not as a document; use for audit, reference or board records."),

    ("PARTIAL", 1663, "src/ui/RealityNote.tsx · src/pages/ReportView.tsx · src/engine/reality.ts REPORT_REALITY, realityOfReport · src/pages/Reality.tsx · src/pages/Case360.tsx · tests/p3control.test.ts 'a report states the reconciliation of the records it rests on, and of no others'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (a figure of a report opens the ledger behind it). Phase 3 adds one way from a report to an investigation: under the heading of every report of the library that rests on records, the strip Reconciliation lists the differences among those records and opens NUMERO Reality on them, chain by chain, where a person opens a case on a difference (the choice of differences is tested; the strip itself has no test). Not built: create a task, request evidence, create a watch, prepare a reclassification, request an approval, follow up or create a forecast scenario from a report; the case is opened in Reality, not on the report; reports outside the library (Forward, Analysis, People cost) carry no such strip."),

    ("PARTIAL", 1675, "src/ui/kit.tsx Truth · src/ui/p3.tsx Simulated, Estimate, Exposure · src/pages/ReportView.tsx · src/pages/Forward.tsx · src/pages/Budgets.tsx · src/pages/Twin.tsx · src/pages/TwinParts.tsx · src/pages/Analysis.tsx · src/numi/NumiPanel.tsx · tests/sql/phase3_platform.sql T245 · tests/p3control.test.ts 'a saved simulation is labelled SIMULATION, touches no entry, and cannot be relabelled'",
     "Built: the reports of the library are marked ACTUAL and, where a period is not locked, PROVISIONAL (Phase 1); Forward marks its figures FORECAST, and ESTIMATE where dates are expected ones; the budget screen sets BUDGET beside ACTUAL; an answer of NUMI carries its state. Phase 3 adds: on the Digital Twin the base figures are marked ACTUAL, every result, table, chart and export SIMULATION, and a value typed by a person TYPED; a saved simulation cannot be relabelled (T245); on Analysis the year on year is ACTUAL and the burn rate ESTIMATE; on Inventory the value is ACTUAL and stock at stake EXPOSURE. Not built: the states are told apart by the word on the chip, not by colour alone — FORECAST, AI ESTIMATE and SIMULATION share one colour, and the ESTIMATE of Phase 3 shares its colour with COMMITTED and EXPECTED; no test asserts the marks on the screens."),

    ("PARTIAL", 1677, "src/pages/ReportView.tsx · src/ui/RealityNote.tsx · src/engine/reality.ts REPORT_REALITY, realityOfReport, notChecked · src/lib/realityData.ts · tests/p3control.test.ts 'a report states the reconciliation of the records it rests on, and of no others' 'the reconciliation of a report is that of its period'",
     "Built: a report whose range holds a period that is not locked is marked PROVISIONAL (Phase 1, requirement 401). Phase 3 adds, on every report of the library that rests on records, the strip Reconciliation: it counts, among the records of the period of the report, those that do not agree with their other records — bank accounts with statement lines not matched for more than a week among them, on the reports of money, the balance sheet and the trial balance — says how many are above the threshold of their company, names what was never looked at (bank accounts with no statement imported, cash boxes never counted, assets never verified) and what the person may not read, and says that what was never checked is not counted as agreeing (tested). Not built: a warning of missing data other than what Reality never looked at; stale integration (none is connected); missing documents; incomplete department submission; a judgement of whether the difference could materially affect the report — the strip counts, it does not weigh; the comparison is made as the records stand today; the strip is not printed."),

    ("PARTIAL", 1683, "src/pages/Imports.tsx · src/engine/analysis.ts parallelRun · supabase/migrations/0018_platform.sql · tests/sql/phase3_platform.sql T263 · tests/p3control.test.ts 'the books of the earlier system beside NUMERO: ledger by ledger, and ready only when nothing differs'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds, under Imports › Parallel run, the comparison of an uploaded trial balance of an earlier system with NUMERO: ledger by ledger, as agrees, differs, not mapped or only in NUMERO, within a tolerance the person sets, with the difference of each ledger (T263, tested). Not built: NUMI does not make the comparison or answer 'Compare this with NUMERO' — it has no pattern for it; only a trial balance in CSV can be compared, at the level of closing balances by ledger (no movements, parties, stock or assets)."),

    # ------------------------------------------------------------------ fund movement
    ("PARTIAL", 1702, "src/pages/FlowCase360.tsx · src/pages/Studio.tsx · supabase/migrations/0017_scenarios_flows.sql flow_case_steps, complete_flow_step · src/pages/Advance360.tsx · src/engine/reality.ts · src/pages/Reality.tsx · tests/sql/phase3_platform.sql T249 T250 T251 · tests/p3control.test.ts 'an advance: released above what was approved, held past its date, claimed without receipts'",
     "Built: an advance shows what was released, settled and returned and the claims that settled it (Phase 2, recorded under requirement 1703). Phase 3 adds: a case of a workflow of the Scenario Studio shows its steps in order — request, approval, release, evidence, settlement, accounting, reconciliation — each with who completed it and when, and the release, settlement and accounting steps with the record they point to (T249 to T251); NUMERO Reality sets the approval, the release, the claims with and without receipts, the expense recognised and the return of each advance side by side (tested). Not built: a timeline for every amount — only an amount carried through a workflow case has one, and its steps are what persons recorded; 'used' and 'classified' as stages of their own; 'reconciled' is a step on which a person records that a comparison was made — the release of an advance is not matched to the bank statement."),

    ("PARTIAL", 1732, "src/engine/reality.ts · src/lib/realityData.ts · src/pages/Reality.tsx · src/pages/Case360.tsx · tests/p3control.test.ts 'an advance: released above what was approved, held past its date, claimed without receipts' 'an advance with no date set for settling it is reported once it has been held thirty days' · tests/sql/phase3_control.sql T223",
     "Built: nothing of this requirement was recorded as built before Phase 3 (Sentinel raised alerts on payments and journals, recorded under requirement 40). Phase 3 adds: NUMERO Reality reports, for every advance, more released than approved, claims without receipts, money still held after the date set for settling it or thirty days after the release where no date was set, and more settled and returned than released (tested for all but the last); each is a difference on which a person opens a case, kept until it is closed with its resolution (T223). Not built: these differences are not Sentinel alerts and are not stored — they are worked out when a person opens Reality; repeated, split or round advances, unusual beneficiaries and changes of bank details between advances are not looked for; fund transfers are not examined."),

    ("PARTIAL", 1734, "src/pages/Advance360.tsx · src/pages/Expenses.tsx · supabase/migrations/0008_expenses_advances_cash.sql · src/engine/reality.ts · src/pages/Reality.tsx · src/pages/Control.tsx · src/pages/FlowCase360.tsx · tests/sql/phase3_control.sql T235 · tests/p3control.test.ts 'an advance: released above what was approved, held past its date, claimed without receipts'",
     "Built: for an advance NUMERO knows who holds it, its purpose, what was released and from which ledger, the claims that settled it with their receipts, what was returned and what is still outstanding (Phase 2). Phase 3 adds the question 'is it reconciled?' for advances: NUMERO Reality sets approval, release, claims and return against each other and reports where they differ (tested); a reclassification keeps how an amount was classified before and after, who changed it and why (T235); a case of a workflow records who requested, who approved and who released, step by step. Not built: the twelve questions for money other than advances; 'what was it actually used for' is what was claimed and is compared with nothing else; the release is not matched to the bank statement; 'who is responsible' is the holder of the advance and nothing more."),

    # ------------------------------------------------------------------ the Genesis Builder and the Scenario Studio
    ("PARTIAL", 1495, "src/pages/Genesis.tsx · src/pages/Registers.tsx (Register kinds) · src/pages/Expenses.tsx (Categories) · src/pages/Assets.tsx (Categories) · src/pages/Companies.tsx · src/ui/ApprovalRuleEditor.tsx · src/pages/Approvals.tsx · tests/sql/phase2_payroll.sql T127–T128 · src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · src/pages/Inventory.tsx · supabase/migrations/0014_inventory.sql inv_categories · tests/sql/phase3_platform.sql T247 T248 T249 T251 T252",
     "Built: custom field definitions and values (values tested in T127–T128), custom record kinds (register kinds), custom categories (expense and asset categories), approval rules by kind of record, company and amount, added and changed on the Approvals page by a Group Super Admin or a holder of the permission approval.configure, a new company created by cloning an existing one (Phase 2). Phase 3 adds custom workflows — ways of working designed in the Scenario Studio for a company or the group, with steps, roles, a form and required documents, in versions, enforced when a case runs (T247 to T252) — and stock categories, each with its ledgers and its method of valuation. Not built: custom reports, custom dashboards, custom roles, custom formulas, company templates defined by the Super Admin; a custom workflow is a straight line started by a person, and it posts nothing."),

    ("PARTIAL", 1737, "src/pages/Genesis.tsx · src/pages/Registers.tsx (Register kinds) · src/ui/AccountMapping.tsx · src/pages/Expenses.tsx · src/pages/Assets.tsx · src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · supabase/migrations/0017_scenarios_flows.sql · src/pages/Notifications.tsx · src/pages/SystemHealth.tsx · src/pages/Communications.tsx · supabase/migrations/0018_platform.sql save_attention_rule, set_feature_flag, save_message_template · tests/sql/phase3_platform.sql T247 T252 T258 T276",
     "Built: a Genesis Builder screen for structure levels and units, custom field definitions with versions, party types, tax codes with dated rates, learned rules and controls; register kinds with their own fields; expense and asset categories; the account mapping (Phase 2). Phase 3 adds, outside the Genesis Builder: a workflow builder — the Scenario Studio, in which an administrator designs a way of working as a straight line of steps with roles, required documents and a form of its own, in versions (T247, T252); rules of attention that class notices by kind and amount (T276); capability switches that hide a module for the group, a company or a role (T258); message templates in versions. Not built: a form builder for the records of NUMERO (only a workflow has a form); branches and conditions in a workflow; status builder; rule and formula builder beyond approval rules and rules of attention; report and dashboard builder; menu and page builder (a switch hides an entry and adds none); custom roles editor; conditional field rules."),

    ("PARTIAL", 1747, "src/engine/registerKinds.json (kind 'trip') · src/pages/Expenses.tsx · src/pages/ClaimEditor.tsx · src/pages/Advance360.tsx · tests/sql/phase2_flow.sql T42–T58 · src/pages/Studio.tsx FLOW_EXAMPLES travel_advance · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · src/engine/p3Types.ts BookingDetail · supabase/migrations/0018_platform.sql check_travel_detail · tests/sql/phase3_platform.sql T248 T250 T251 T265",
     "Built: a Trip register item (traveller, from, to, purpose, mode, daily allowance), an advance and an expense claim linked to the trip, claim lines by category with receipts, and settlement of the advance (tested T42–T58). Phase 3 adds: a workflow for travel that requires these items can be designed in the Scenario Studio — the starting point 'Employee travel: advance, trip and settlement' has a form with destination, purpose, dates, mode and estimate, and steps for approval, a check of earlier advances, release of the advance, tickets and bills as required documents, settlement through the claim and its entry; the form is enforced (T248), the evidence step waits for its documents (T251) and the release step for the advance (T250); a line of the claim carries the booking of a flight, a train, a bus, a cab or a hotel stay with its operator, reference, route or city, dates and the parts of its amount, which must add up to the line (T265). Not built: a configured travel path — the workflow is not tied to the path or the trip record, and nothing makes a trip go through a case; meals are a claim line under a category, not a booking; flight, hotel and taxi are details of a claim line, not fields of the trip."),

    ("PARTIAL", 1765, "src/pages/Studio.tsx FLOW_EXAMPLES · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T248",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds forms carried by the starting points of the Scenario Studio, each changed freely before it is saved: expense (petty purchase, client entertainment), travel (destination, purpose, dates, mode, estimate), advances (site imprest, salary advance, advance to a vendor), petty cash (replenishment), purchase request (purchase of an asset, with its requisition), donation (charitable donation), emergency fund (emergency cash) and a custom form on an empty canvas; a form has fields of six kinds (text, number, money, date, a list to choose from, yes or no), required or not, and is enforced when a case is started (T248). Not built: templates for the forms of the records themselves — an expense claim, an advance, an invoice and a requisition are entered on fixed screens; no template for an invoice or for a project expense (the starting point for a project is its launch); a form exists only as part of a workflow, and there is no library of forms apart from the examples."),

    ("IMPLEMENTED", 1773, "src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql save_flow_def, check_flow_definition, start_flow_case, complete_flow_step · tests/sql/phase3_platform.sql T247 T248 T249 T250 T251 T252 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "Built by Phase 3 (the earlier note said no workflow builder exists). The Scenario Studio is the workflow builder; it is not named Flow Studio. In the designer a person with flow.configure lays out a workflow as cards in order — each with its kind of step shown as a mark, its role, the record it points to and the documents it requires — adds, removes and moves steps, and sees the path drawn as a line of marks; the definition is checked when saved and enforced when a case runs (T247 to T252). The path is a straight line: there is no branch, no condition and no parallel step (the nodes are recorded under requirement 1774). The designer screen has no automated test of its own; the rules it saves are tested in the database and in the sample engine."),

    ("PARTIAL", 1774, "src/engine/p3Types.ts FLOW_ACTIONS, FLOW_TRIGGERS, FLOW_TRIGGERS_WORKING · src/pages/Studio.tsx ACTION_META, NEEDS_RECORD · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T248 T249 T250 T251",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds nine kinds of step in the Scenario Studio, which meet these nodes: Start (a case is started by a person, by hand or by filling in the form), Form (the form of the workflow, enforced, T248), Approval (never by the person who started the case, T249), Document Request (an evidence step that waits for the kinds of document it requires, T251), Accounting Entry, Settlement (complete only when they point to the entry, claim or payment that did it; the workflow posts nothing), Reconciliation (a person records that the comparison was made), Task (every step is a task for a role; a review step also), Notification (a notice step records that someone was told — NUMERO raises no notice from a step and sends nothing), End (the case completes after its last step). Not built: Condition, Calculation, NUMI Analysis, Sentinel Check, Wait, Timer, Escalation, Webhook and Integration — none exists as a step; the text a workflow carries for NUMI, Sentinel and notifications configures nothing."),

    ("PARTIAL", 1789, "src/ui/AccountMapping.tsx · numero_private.set_account_map · tests/sql/phase2_treasury_purchasing.sql T82–T83 · src/pages/Expenses.tsx (Categories) · src/pages/Assets.tsx (Categories) · supabase/migrations/0014_inventory.sql inv_categories · src/pages/Inventory.tsx · src/engine/p3Types.ts P3_ACCOUNT_MAP_KEYS · src/engine/opsTypes.ts ACCOUNT_MAP_KEYS · src/pages/Investments.tsx",
     "Built: the account mapping (ledger role to ledger) edited on screen and tested (T82–T83); expense category to ledger; asset category to its three ledgers (Phase 2). Phase 3 adds: a stock category to its stock ledger and its cost of sales ledger; ten ledger roles in the same account mapping for the operations of Phase 3 — goods received not yet invoiced, landed cost clearing, stock lost, stock found, gain or loss on investments, changes in fair value, income from investments, distributions payable, management fees and fees owed to the manager; each holding names its own investment, income and gain ledgers. Not built: mapping by scenario (the accounting of a workflow is text that configures nothing), by path, or by a transaction type an administrator defines (the ledger roles are fixed in the code; a person maps each to a ledger and cannot add one)."),

    ("PARTIAL", 1792, "src/pages/Expenses.tsx (Categories) · numero_private.save_claim · tests/ops.test.ts 'policy flags inform the approver and never reject on their own' · tests/sql/phase2_flow.sql T70 · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql complete_flow_step · tests/sql/phase3_platform.sql T251 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "Built: for each expense category the company sets the amount above which a receipt is expected; a line without one is flagged EVIDENCE MISSING for the approver (tested). Required fields of a register kind are enforced (T70). Phase 3 adds evidence rules by scenario that name the kind of document and make it mandatory: each step of a workflow of the Scenario Studio states the kinds of document it requires, chosen from the 23 kinds of the document inbox (an invoice, a receipt, a ticket, a tax document and others), and the step cannot be completed until a document of each kind is attached to the case (T251). Not built: a rule by amount inside a scenario (a step requires its documents whatever the amount, so 'invoice mandatory above a configured amount' cannot be written); evidence rules by path; the engine checks the kind a person chose for a document, not its content; the rule binds only the cases of a workflow — an advance or a claim entered on its own screen is under the category rule alone."),

    ("PARTIAL", 1794, "src/pages/FlowDesigner.tsx · src/pages/Studio.tsx ACTION_META, NEEDS_RECORD · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql check_flow_definition, complete_flow_step · tests/sql/phase3_platform.sql T247 T249 T250 T251",
     "Built: nothing of this requirement was built before Phase 3 (a Financial Path has a 'settlement rule' field that records a choice as text; nothing applies it). Phase 3 adds, for the cases of a workflow of the Scenario Studio, the steps an administrator decides a case must pass: an approval step (T249), an evidence step with the kinds of document it requires, invoice and receipt among them (T251), a settlement step, which is complete only when it points to the record that settled — an expense claim, a payment, an entry (the rule is checked when the workflow is saved, T247), a reconciliation step, and any step may be marked optional; a workflow without a settlement step requires none. Not built: the rule binds only the cases of the workflow — advances and claims are settled by their own fixed rules whatever a workflow says, and the path's 'settlement rule' is still text; return and reimbursement are not told apart (the step points to a record, it does not check which); a bank match is recorded by a person and compared by nothing; a settlement step in a running case has no test (T250 tests the release step)."),

    ("PARTIAL", 1800, "src/pages/Notifications.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql attention_rules, save_attention_rule, notification_prefs, set_notification_pref · supabase/migrations/0019_corrections_after_assessment.sql notify_holders, attention_class · tests/sql/phase3_platform.sql T241 T276 T277 · tests/p3control.test.ts 'the owner is not told of every approval that waits: only of what the rules class for the owner' 'notices: an approval is told to those who can approve, never to the person who made it, and cannot be switched off'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (warnings were raised by fixed rules and shown inside the application). Phase 3 adds two configurable settings of notices: rules of attention, set by a Group Super Admin under Notifications › Rules, which class a notice or an alert by its kind and its amount, and decide whether a Group Super Admin is told of an approval that waits — only when a rule classes it as owner action or critical, or when nobody else could approve it (T276, T277); and preferences by which a person switches off kinds of notice, except those that govern (T241). Not built: a rule that raises a notice from a condition of the books (a department above 90% of its budget, or any other figure); a rule that names who is told (a notice goes to those who hold the permission, not to a role such as the CFO); the kinds of notice are fixed in the engine; nothing is sent outside the application."),

    ("PARTIAL", 1802, "src/pages/Registers.tsx · src/pages/Register360.tsx · supabase/migrations/0006_workflow_registers_documents.sql audit_register_kinds, audit_custom_values · src/engine/forward.ts · supabase/migrations/0017_scenarios_flows.sql flow_cases.register_item_id · src/pages/Studio.tsx · src/pages/FlowCase360.tsx · src/engine/analysis.ts complianceView · src/pages/Analysis.tsx · tests/p3control.test.ts 'deadlines across companies'",
     "Built: a new register kind is available in the register list, its search and filters, the CSV export of the list, Forward, the audit trail and follow-ups. Custom field values are written to the audit trail (Phase 2). Phase 3 adds, for items of any kind the group added: a case of a workflow of the Scenario Studio can be about a register item and a step can point to one, so a custom record can pass through a workflow; Analysis › Compliance deadlines offers every kind that carries a due date on an active item, so the deadlines of a custom kind are listed across companies when its kind is ticked (the list is tested with the kind compliance). Not built: reports of the library, NUMI answers, API and permissions for custom kinds and custom fields; the register kind named on a workflow is text — nothing requires a record of a kind to pass through a workflow; Reality, the Digital Twin and notices do not read custom kinds."),

    ("PARTIAL", 1818, "supabase/migrations/0002_ledger_engine.sql can_view_level, journals, org_units · supabase/migrations/0003_documents_banking_budgets.sql invoices · supabase/migrations/0006_workflow_registers_documents.sql register_items, documents · supabase/migrations/0015_investments_funds.sql funds, holdings, fund_distributions · supabase/migrations/0016_reality_control.sql cases, confirmations · supabase/migrations/0017_scenarios_flows.sql flow_cases · src/pages/Reality.tsx · src/pages/Studio.tsx · src/pages/Investments.tsx · src/pages/Vault.tsx · tests/p3.test.ts 'is confidential: a person who is not cleared does not see it'",
     "Built: records carry a level — internal, confidential, highly confidential, restricted, super admin only — read only by a person cleared for it (numero_private.can_view_level, since Phase 1): journals, organisation units, invoices, register items (financial paths among them), documents, fixed assets, purchasing documents, advances, expense claims, loans, deposits, employees and follow-ups; clearance is granted per person and company (vault_grants). Phase 3 adds the level on funds and holdings (a fund is confidential by default, and a person who is not cleared reads neither the fund nor its commitments, tested), distributions, cases, confirmations and the cases of workflows, chosen in the form that opens each. Not built: NORMAL as a level (internal is the lowest); a level on a field, a form, a scenario or workflow definition, or a report; BLACK VAULT as a level of a record."),

    ("PARTIAL", 1839, "src/lib/sandbox.ts · src/pages/Sandbox.tsx · src/store/app.ts · src/ui/Shell.tsx · tests/p3app.test.ts 'is built from the configuration and the balances, and writes nothing to the books' 'what is done in the sandbox stays in the sandbox, and changes no object of the books'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds the sandbox: a person with scenario.manage works on a copy of the configuration — workflows of the Scenario Studio, approval rules, account mapping, categories, register kinds — and of the balances of the books, prepares a transaction there and approves it acting as a second person, starts a case of a workflow, and the books are not touched (tested with an entry). Not built: the transactions of the books are not copied, so a test transaction cannot settle an open invoice or advance of the books; roles and permissions are not copied (every person holds every permission), so a route by role cannot be tried; nothing proved is carried to the books; trying a workflow or a changed rule in the sandbox has no test; NUMI does not run the test (requirement 1840)."),

    ("PARTIAL", 1905, "src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql · src/pages/Approvals.tsx · src/ui/ApprovalRuleEditor.tsx · tests/sql/phase3_platform.sql T247 T248 T249 T250 T251 T252 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "Built: approval rules by kind of record, company and amount, with steps by role, are added and changed on the Approvals page without a developer (since Phase 1 and 2, recorded under requirement 42). Phase 3 adds a workflow engine: in the Scenario Studio an administrator designs an approval process as a line of steps with roles, forms and required documents, in versions, for a company or the group, and cases follow it with the rules enforced (T247 to T252). Not built: the workflow engine does not carry the records of NUMERO — advances, claims, invoices and journals follow their own fixed flows and the approval rules, and a workflow case only points to them; a workflow has no branch or condition, so a process that differs by amount or kind is written as separate workflows; a case is started by a person."),

    ("PARTIAL", 1912, "supabase/migrations/0006_workflow_registers_documents.sql propose_posting, wf_dispatch, register_kinds · numero_private.open_request · src/ui/AccountMapping.tsx · src/pages/Genesis.tsx · src/engine/reports.ts · src/pages/Calculators.tsx · supabase/migrations/0017_scenarios_flows.sql save_flow_def, start_flow_case, complete_flow_step · src/engine/twin.ts · supabase/migrations/0018_platform.sql notifications, notify_holders, refresh_notifications · tests/sql/phase3_platform.sql T240 T247 T252",
     "Built: engines used by many kinds of record exist since Phases 1 and 2 — posting with its dispatcher (one handler per module), approval (rules by kind, company and amount), account mapping, custom fields, register kinds (entities of the group's own, paths among them), documents with their links, permissions, reports; calculators are on one screen. Phase 3 adds a workflow engine (the Scenario Studio: definitions in versions, cases, steps, T247 to T252), a notification engine (notices raised by the engine for approvals, alerts, follow-ups, cases and what falls due, T240), and a scenario engine for simulations (the Digital Twin). Not built: a form engine (the forms of the records are fixed screens; only a workflow has a form); a rule engine beyond approval rules, rules of attention and the fixed rules of Sentinel; a settlement engine (settlement is written for each kind of record); an AI/NUMI metadata engine (NUMI reads patterns written in the code); the workflow engine does not carry the records of NUMERO, which follow their own code."),

    ("PARTIAL", 1913, "src/pages/Studio.tsx FLOW_EXAMPLES · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T250 T251",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds templates over one engine: the starting points of the Scenario Studio for petty cash (replenishment and petty purchase), employee travel with its advance, site imprest (a site advance), charitable donation and emergency cash, among nineteen, each a configuration of the one workflow engine — steps, roles, form, required documents — that a person changes and saves without code. Not built: petty cash, advances and invoices of NUMERO are not these templates — they remain modules of their own code, and a workflow case only points to their records; a case posts nothing and moves no money; no template for a department invoice."),

    ("PARTIAL", 1914, "src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · supabase/migrations/0017_scenarios_flows.sql · src/engine/registerKinds.json (kind 'path') · src/pages/Registers.tsx · tests/sql/phase3_platform.sql T247 T248",
     "Built: a financial path such as 'Film production advance' is created as a register item without code, with its own cost-tracking dimension (Phase 2, recorded under requirement 1742). Phase 3 adds: a way of working nobody foresaw is designed without code in the Scenario Studio, from an empty canvas — its steps, the roles that act, its form and the documents it requires — and cases follow it (T247, T248). Not built: such a way of working brings no accounting, approval rule, permission, report or settlement rule of its own — its entries are those of the fixed modules, which a step points to; the path and the workflow are not tied to each other."),

    ("PARTIAL", 1915, "src/pages/Companies.tsx · src/pages/Genesis.tsx · src/pages/Registers.tsx · src/pages/Expenses.tsx · src/pages/Assets.tsx · src/ui/ApprovalRuleEditor.tsx · src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/Twin.tsx · src/pages/Notifications.tsx · src/pages/Communications.tsx · supabase/migrations/0017_scenarios_flows.sql · supabase/migrations/0018_platform.sql save_attention_rule, save_message_template · tests/sql/phase3_platform.sql T242 T247 T248 T276",
     "Built: without coding, a company, a department, a sub-department, a path (as a register item), a category, a field (shown and filled in on invoices and bills, register items, fixed assets and parties; on other record types it can be defined and is shown nowhere), an approval route (a rule by kind of record, company and amount with its steps by role, added and changed on the Approvals page) (Phase 2). Phase 3 adds: a scenario — a way of working designed in the Scenario Studio, and a simulation saved on the Digital Twin (T242); a form — the form of a workflow, with fields of six kinds (T248); a workflow — a straight line of steps (T247); a rule — a rule of attention by kind of notice and amount (T276); message templates for communications. Not built: a form apart from a workflow, a document type (the 23 kinds are fixed), a status, a rule other than approval rules and rules of attention, a calculator, a report, a dashboard, an automation, a NUMI rule (learned rules can only be disabled), a Sentinel rule (two thresholds only; a threshold tried on the Digital Twin changes nothing), a company template."),
]

# Looked at; Phase 3 changed nothing these requirements ask for.
UNCHANGED = [
    1482, 1484, 1497, 1498, 1518, 1526, 1530, 1534, 1538, 1539, 1540, 1548, 1551, 1554, 1555,
    1574, 1597, 1604, 1609, 1610, 1612, 1615, 1620, 1642, 1656, 1659, 1673,
    1695, 1696, 1699, 1703, 1705, 1707, 1708, 1710, 1711, 1713, 1714, 1716, 1717, 1725, 1728, 1736,
    1738, 1742, 1744, 1751, 1754, 1759, 1801, 1805, 1815, 1823, 1824, 1825, 1840, 1842, 1845, 1850,
    1854, 1860, 1865, 1871, 1872, 1873, 1874, 1891, 1892, 1916,
]
