# Requirement status — phase 3 — Inventory, Investments, System Health, Integrations. Assessed against the code on 2026-09-27.
#
# How to read this file
#   TESTED       engine + screen + a named automated test that asserts the behaviour
#   IMPLEMENTED  engine + screen, workflow works end to end, no test for this specific requirement
#   PARTIAL      some of it works; the note says "Built: ... Not built: ..."
#   PLANNED      not built; listed in PLANNED with the reason
#
# Facts that apply to many entries below (verified in the code):
#   * The screens were exercised in the demo (in-browser engine) only. No screen has been driven against the
#     live database. The database functions are tested directly (tests/sql/phase3_*.sql).
#   * Nothing leaves the application: no e-mail, SMS, WhatsApp or push is sent, and no bank, tax portal,
#     speech service, language model or GHL system is connected. The register of integrations records intent.
#   * Nothing runs on a schedule. A person starts every count, refresh and health report.
#   * Backups are made by the database provider. NUMERO keeps the record a person enters and sees no backup.
#   * A status is TESTED only where the named tests exercise what the requirement asks. Where a list in the
#     requirement holds a kind of document or a method that no test exercises (returns of stock, landed cost
#     shared by quantity or by weight), the status is IMPLEMENTED and the note names what is not tested.
#     Where the untested items are labels of one list with the same behaviour (reasons of a stock loss,
#     relations in the corporate structure), the status is TESTED and the note names the labels the tests use.
#   * Brought up to date on 2026-09-27 after the corrections listed in scripts/_assess/P3_CORRECTIONS.md.
#     Each correction named below was read in the code and in its test before it was relied on.
#     Brought up to date again on the same day after the corrections of the section 'Found when the records
#     were read a second time' of that file (R1 to R15) and after the measure of a page of the API.
#   * The live data layer (src/api/supabaseCore.ts, supabaseOps.ts, supabaseP3.ts) reads a list through one
#     of two readers (src/api/paging.ts). One reads the list to its end, a page at a time, in a complete
#     order; a list longer than its ceiling (20,000 records; 200,000 for ledger totals, monthly totals and
#     stock on hand) is refused with a message and is not cut. The other reads a stated number of the latest
#     records (notices 200; stock movements 2,000, or 5,000 on the page of an item or of a unit, or 20,000
#     of one stock document; imports 200; backup records 500). The size of a page is measured once in a
#     session: apiPage (src/api/supabaseCore.ts) asks public.api_row_probe for 1,001 numbers and counts what
#     arrives. The two readers are tested against a query that answers as the API does (tests/p3app.test.ts,
#     'a list of the live books is read to its end', six tests). That each list of the live data layer goes
#     through a reader with the right key, and the measure as the application takes it, are not tested: that
#     code runs only against the live database and is type-checked. See requirement 1535.
#   * The migration files 0014 to 0019 were extracted again from what the database holds. A correction stands
#     in the piece that made it, not in the function it corrects: the refusal that
#     tests/sql/phase3_investments.sql T213 asserts is in 0015_investments_funds.sql (piece p3_21), and the
#     corrections made after the assessment to stock on hand, to the date of a stock document, to system
#     health and to notices are in 0019_corrections_after_assessment.sql (pieces p3_24 and p3_25), while
#     0014 and 0018 hold those functions as they were first written. The same file holds the measure of a
#     page (public.api_row_probe, piece p3_26) and the count of statement lines matched in part in
#     numero_private.system_health (piece p3_27).
#   * The checks T278 (the measure of a page) and T279 (a statement line matched in part) are written in
#     tests/sql/phase3_platform.sql. No status below rests on them, and no entry names them as evidence.
#   * A gate on a screen (who may open it, who may press a button) cannot be observed in the sample data,
#     where every person holds every permission. Where a note names such a gate, it was read in the code and
#     has no automated test.
ENTRIES = [
    # (status, requirement number, evidence, notes)

    # ------------------------------------------------------------------ Inventory
    ("IMPLEMENTED", 24, "supabase/migrations/0014_inventory.sql · src/api/demoInventory.ts · src/engine/stock.ts · src/pages/Inventory.tsx · src/pages/InvItem360.tsx · src/pages/StockDocEditor.tsx · supabase/migrations/0019_corrections_after_assessment.sql · tests/sql/phase3_inventory.sql T160 T161 T162 T163 T165 T166 T167 T168 T169 T170 T171 T172 T173 T175 T176 T186 T187 T273 · tests/p3.test.ts 'weighted average: 100 at 10 and 100 at 14, an issue of 50 costs 600' 'first in, first out: 10 at 100 then 10 at 120, an issue of 15 costs 1600' 'a transfer proposes no entry: the place changes, the value does not' 'a stock document is not dated on a day that has not come' · tests/p3control.test.ts 'what is at or below its level is listed for a person to order'",
     "Items with a code (SKU), categories, stock locations, lots (a batch is recorded as a lot), serial numbers, expiry dates, the stock ledger with running quantity and value, valuation by weighted average or first in first out (chosen on the category and on the item), transfers between locations, returns from a customer and to a vendor, conditions noted on stock (damaged and four others), reorder level and reorder quantity with a suggested order. Tested: items and categories, both valuation methods, lots, serial numbers, expiry from the shelf life, transfers, damaged stock, the reorder list, agreement of the stock ledger with the general ledger. Not covered by a test: the two return documents (they exist in the engine and on the screen; the sample data holds one return awaiting approval), so the status is IMPLEMENTED and not TESTED. A stock document dated on a day that has not come is refused (tested); the database allows one day beyond its own date, because its day is that of UTC, and the sample engine allows none. The value of stock is kept per item, not per location. Bar codes, price lists and conversion between units are not built."),
    ("PARTIAL", 28, "supabase/migrations/0014_inventory.sql inv_lots, inv_unit_events, save_inv_lot, record_unit_event · src/api/demoInventory.ts · src/pages/InvUnit360.tsx · src/pages/Inventory.tsx · src/pages/StockDocEditor.tsx · tests/sql/phase3_inventory.sql T172 T182 · tests/p3.test.ts 'a serial-numbered unit that is sold remembers its customer, and its service history is kept' 'the movements of one lot are asked for as such, however many the item has'",
     "Built: for each serial-numbered unit — manufacturer and model (from the item), serial number, import details (supplier invoice, bill of entry, port, country of origin, currency, exchange rate), purchase cost from the receipt, landed cost added, the list sale price of the item and the linked sales invoice, installation date, warranty end date, customer and location at the customer, a link to a service or AMC contract kept in the registers, and a history of events (installation, engineer visit, spare part fitted, warranty claim, service contract, relocation) each with its cost and whether it is chargeable. A unit issued to a customer is recorded as sold to that customer when the entry of the issue is approved (tested). The page of a unit asks for the movements of its own unit, not for the latest of its item, so the receipt that gives the purchase cost is found however many movements the item has (tested in the sample engine; the same request to the live database has no automated test); it reads up to 5,000 of them and says when that number is reached. Not built: accounting for warranty obligations (no provision is worked out) and for service revenue (an event raises no invoice and proposes no entry; its cost is a record beside the books); a spare-part event takes nothing out of stock (a separate stock issue does); AMC has no record on the unit beyond the link to the register item; import details are typed on the unit after the receipt, not on the receipt screen."),
    ("IMPLEMENTED", 29, "supabase/migrations/0014_inventory.sql · src/api/demoInventory.ts · src/engine/stock.ts · src/pages/Inventory.tsx · src/pages/InvItem360.tsx · src/pages/InvUnit360.tsx · src/pages/StockDocEditor.tsx · tests/sql/phase3_inventory.sql T170 T171 T175 T176 · tests/p3app.test.ts 'exposure is reported beside the loss that was posted, never inside it'",
     "Products as items with a tax code and an HSN code; lot (batch) numbers with dates of manufacture and expiry and the days left; the supplier of each lot; purchase cost on the receipt; stock by location; a stock issue that names the customer and the sales invoice; returns from a customer and to a vendor; damaged and expired stock noted as a condition and written off only through an approved adjustment. The screen 'Units and lots' states that NUMERO is not a regulated pharmaceutical compliance system and does not replace one. Tested: a lot is required, expiry follows the shelf life, damaged and expired stock. Not covered by a test: returns, and the tax code and HSN code of an item. The tax code of an item is a recorded classification only: an invoice line does not take its tax from the item, and a sale is tied to stock only by naming the invoice on the stock issue."),
    ("PARTIAL", 153, "supabase/migrations/0014_inventory.sql warehouses, save_warehouse · src/api/demoInventory.ts · src/pages/Inventory.tsx · src/pages/StockDocEditor.tsx · src/pages/StockCount.tsx · tests/sql/phase3_inventory.sql T173 T177 · tests/p3.test.ts 'a transfer proposes no entry: the place changes, the value does not'",
     "Built: one company keeps any number of stock locations of six kinds (warehouse, store, site, office, in transit, service van), each with a code, an address, a keeper and a link to a branch, site or office of the company; stock, counts and transfers are kept per location, and a transfer between two locations of one company proposes no entry (tested with two locations). Units of a company (branch, office, site, warehouse and others) exist since Phase 1, without a limit on their number. Not built: the value of stock per location (value is kept per item); a test at the numbers named (50 branches, 20 warehouses, 10 sites, 5 offices); a bill or an invoice line tagged to a branch or an office (such a line carries a project only)."),
    ("TESTED", 482, "supabase/migrations/0016_reality_control.sql materiality, set_materiality, is_material · src/api/demoControl.ts · src/engine/reality.ts · src/pages/Control.tsx · src/pages/Reality.tsx · tests/sql/phase3_control.sql T220 T221 T230 · tests/p3control.test.ts 'materiality is a threshold for attention, set with its basis' 'verifying cash: a difference above the threshold is raised as a priority, and the books still say what they said'",
     "Each company has its own threshold, an amount set with its basis by a person with the permission; every change is written to the audit trail. A difference above the threshold is marked material and raised with priority; the books are not changed (tested). A difference at or below the threshold is still listed on the differences screen, marked 'below the threshold'; the engine uses the threshold only to set that mark. No test covers a difference below the threshold. A percentage can be recorded beside the amount and is not used in the comparison. A company without a threshold treats every difference as material."),
    ("TESTED", 568, "supabase/migrations/0014_inventory.sql create_stock_count, record_stock_count, review_stock_count, propose_stock_count, cancel_stock_count, assert_not_counting · src/api/demoInventory.ts · src/pages/StockCount.tsx · src/pages/Inventory.tsx · tests/sql/phase3_inventory.sql T177 T178 T179 T180 T181 · tests/p3.test.ts 'a stock count freezes the location, needs a second person and a reason, and changes the books only through an approved adjustment' 'a count that agrees with the books is closed and proposes nothing'",
     "Opening a count takes a snapshot of what the books hold in the location and, unless the person chooses otherwise, freezes the location so that no stock document can be proposed there. The count is entered line by line (the book quantity is hidden until the person asks for it), differences need a reason, a second person with the permission accepts the count or asks for a recount, and the differences become one adjustment whose entry is proposed and approved. Counting changes nothing in the books. Not built: separate count sheets for several counters of one location."),
    ("TESTED", 570, "supabase/migrations/0014_inventory.sql stock_doc_lines reason_code, save_stock_doc, propose_stock_doc · src/api/demoInventory.ts · src/engine/stock.ts postedLoss · src/pages/StockDocEditor.tsx · src/pages/Inventory.tsx · tests/sql/phase3_inventory.sql T174 T176 T180 · tests/p3.test.ts 'an adjustment says what happened; a condition noted on stock is exposure until a loss is approved' 'after everything, the stock ledger and the general ledger agree and nothing is left reserved' · tests/p3app.test.ts 'exposure is reported beside the loss that was posted, never inside it'",
     "Every line of a stock adjustment states what happened: damage, expiry, theft, breakage, obsolescence, shrinkage (and a difference on counting, stock found, a sample, other). A line without it is refused. The loss reaches the books only when the entry of the adjustment is approved by a second person, and the loss posted in a period is shown by reason. The tests use the reasons damage, shrinkage and theft; expiry, breakage and obsolescence are further values of the same list and are not exercised one by one. Theft is what a person recorded; NUMERO draws no conclusion."),
    ("IMPLEMENTED", 573, "supabase/migrations/0014_inventory.sql save_stock_doc, propose_stock_doc, apply_stock_doc · src/api/demoInventory.ts · src/pages/StockDocEditor.tsx · src/pages/InvUnit360.tsx · tests/sql/phase3_inventory.sql T182 · tests/p3.test.ts 'landed cost joins the stock that is still there; the share of what has left is a cost now'",
     "A landed cost document names a posted stock receipt, lists the charges (freight, insurance, customs duty, clearing, port charges or any other name; each with its amount, the ledger credited and the party owed) and shares the total over the lines of the receipt by value, by quantity or by weight, as chosen on the document. The share of goods still in stock joins the stock; the share of goods that have left is a cost at once. The entry is proposed and approved like any other. The tests share 500 over a receipt of one line, by value: the division between several lines, and sharing by quantity and by weight, are not covered by a test, so the status is IMPLEMENTED and not TESTED. Charges in a foreign currency and a link from a charge to the vendor's bill are not built."),
    ("TESTED", 635, "supabase/migrations/0018_platform.sql stage_import, commit_import, discard_import · src/api/demoPlatform.ts · src/pages/Imports.tsx · tests/sql/phase3_platform.sql T261 T262 T263 · tests/p3control.test.ts 'an import is checked before it enters the books, and enters them as drafts'",
     "A file is staged first: every row is shown with the ledger it maps to and what is wrong with it (preview), and four checks are recorded — validation, duplicates, balance, mapping of accounts. Committing is refused unless the checks pass; journals and opening balances then enter the books as drafts, and the trial balance of an earlier system is kept beside the books. A file already committed is refused; rows repeated in the file and vouchers that look already recorded are shown for a person to judge and do not stop the import. Limits: CSV files only; at most 5,000 rows a file; journals, opening balances and an earlier trial balance only; a staged file cannot be mapped again (it is brought in again with its mapping)."),
    ("TESTED", 700, "src/engine/stock.ts lossExposure, exposureTotals, postedLoss · supabase/migrations/0014_inventory.sql inv_holds, save_inv_hold, release_inv_hold · supabase/migrations/0019_corrections_after_assessment.sql stock_on_hand · src/api/demoInventory.ts · src/pages/Inventory.tsx · src/pages/InvItem360.tsx · tests/p3control.test.ts 'exposure is shown under one heading only, the most serious, and is never added to posted loss' · tests/p3app.test.ts 'exposure is reported beside the loss that was posted, never inside it' · tests/p3.test.ts 'stock moved to another place was not received again: it is as old as its receipt' · tests/sql/phase3_inventory.sql T175 T176 T272",
     "Stock still in the books is listed under near expiry, expired, damaged, obsolete, slow moving, missing and held for inspection, each quantity under one heading only. Exposure is quantity times the cost the item is carried at, marked EXPOSURE and shown beside the loss posted in the period, never added to it. Expiry comes from the dates of the lots; damaged, obsolete, missing and held for inspection are conditions a person notes; slow moving is worked out from the last movement. The tests cover expired, near expiry, damaged, obsolete, held for inspection and slow moving; no test notes a 'missing' condition. Exposure is worked out in the application from the records; the database holds the conditions noted. Near expiry is fixed at 60 days; slow moving is 180 days unless the item sets its own. Stock moved to another location of the company is as old as its receipt: a transfer in is not a receipt and a transfer out is not stock leaving, so a transfer does not restart the period after which stock is called slow moving (tested in the database and in the sample engine). Where a location received nothing from outside, the last receipt of the item and lot anywhere in the company is used. The day is kept per item, lot and location, not per quantity: in a location that also received the item from outside, stock transferred in takes the day of the last such receipt there, which can be later than the day the company received it."),
    ("PARTIAL", 1275, "supabase/migrations/0018_platform.sql fact_ledger_monthly, fact_refresh, refresh_facts · src/api/demoPlatform.ts · src/api/supabaseP3.ts listFacts · src/pages/SystemHealth.tsx · src/pages/Analysis.tsx · tests/sql/phase3_platform.sql T264 · tests/p3control.test.ts 'the monthly totals agree with the posted entries'",
     "Built: an analytical store of monthly totals (debit, credit, number of lines) per company, ledger and unit, rebuilt from posted entries when a person asks; the state of the store per company and whether entries were posted since; the year-on-year analysis reads the store page by page, or the ledger when the person chooses (the source is named on the screen). The totals agree with the posted entries (tested). Not built: refresh on a schedule or as entries are posted (a refresh rebuilds the whole company); any analysis other than year on year reading the store (burn rate, unusual entries, the digital twin and the reports read the ledger); totals per unit are stored and read by no screen; totals for the group with currency conversion; any measurement under load."),
    ("TESTED", 1387, "supabase/migrations/0014_inventory.sql stock_count_lines, create_stock_count, record_stock_count · src/engine/stock.ts countDifferences · src/api/demoInventory.ts · src/pages/StockCount.tsx · tests/p3control.test.ts 'book quantity against physical quantity' · tests/sql/phase3_inventory.sql T177 T180 · tests/p3.test.ts 'a stock count freezes the location, needs a second person and a reason, and changes the books only through an approved adjustment'",
     "The count sheet sets the quantity in the books at the snapshot beside the quantity counted, line by line, with the difference and its value at the cost of the snapshot, and totals of lines that agree, differ, are short and are over. Stock found that the books do not hold in the location is added with a book quantity of zero."),
    ("PARTIAL", 1503, "src/engine/features.ts · src/pages/Features.tsx · src/pages/SystemHealth.tsx · tests/p3app.test.ts 'the inventory of capabilities says what is not connected, and every key is its own'",
     "Built: a list of 53 capabilities in 26 areas, each with what it does, what it does not do, its state (working, partial, recorded only, not connected) and a link to its screen, with search and a filter by state; the count of requirements built, partial and not built per module, read from the requirement ledger. Every top-level screen of the application has an entry. The areas include Accounting, Banking, Treasury, Payroll, People Cost, Expenses, Revenue, Tax, Audit, Assets, Inventory, Parties, Documents, Forward, Sentinel, Reality, Truth, Digital Twin, NUMI, Security and Integrations. The test asserts that every key is unique and that every capability that is not 'working' states its limits. Not built: an area 'Projects' (a project is a tag on entries and has no entry in the list); the list is written by hand in the code — nothing checks it against the screens, the tests or the requirement ledger, and the state of a capability is typed, not derived."),
    ("PARTIAL", 1509, "docs/NUMERO_MASTER_SPEC.md · docs/NUMERO_SPEC_INDEX.md · docs/requirements.json · scripts/build_requirement_ledger.py · scripts/check_status_part.py · scripts/_assess/STATUS_BRIEF_P3.md · scripts/_assess/P3_CORRECTIONS.md · scripts/extract_migrations.py · supabase/migrations/0014_inventory.sql · supabase/migrations/0019_corrections_after_assessment.sql · src/pages/Inventory.tsx",
     "Built: the specification is kept in the repository with an index and a ledger of its 1,916 requirements; migrations and screens name the requirement numbers they serve in their headers; the status of a requirement is recorded with evidence, and the check of a status file refuses evidence that names a file that does not exist; the brief for an assessment requires each claim to be verified in the code. A search of src, supabase and tests finds no TODO or FIXME marker. Not built: a record, for each implementation decision, that the specification and the existing code were consulted; nothing in the repository enforces the practice, and no test can show it. The assessment found the migration files behind the database in one place (the refusal of a management fee for days that have not passed, asserted by test T213); the files were then extracted again from what the database holds (scripts/extract_migrations.py) and the refusal is in supabase/migrations/0015_investments_funds.sql. What the assessment found and what was done about each finding is kept in scripts/_assess/P3_CORRECTIONS.md. One correction was written from the text of a file and not from the function as the database held it, named a column that no longer existed, and stopped notices until the database tests found it; the next piece corrected it. Nothing compares the files with the database by itself: a person extracts them."),

    # ------------------------------------------------------------------ Investments
    ("PARTIAL", 30, "supabase/migrations/0015_investments_funds.sql · src/api/demoInvest.ts · src/engine/invest.ts · src/pages/Investments.tsx · src/pages/Fund360.tsx · src/pages/Holding360.tsx · src/pages/Approvals.tsx · tests/sql/phase3_investments.sql T192 T193 T194 T195 T196 T197 T198 T199 T200 T201 T202 T203 T204 T205 T211 T213 · tests/p3.test.ts 'a capital call is a request, not money: approving it posts nothing' 'units are issued when the money is posted, and a receipt cannot exceed what was called' 'net asset value comes from the books and is approved by a second person' 'the management fee follows its formula and the same days cannot be charged twice' · tests/p3control.test.ts 'the multiples of a fund carry their formulas, and none is shown without its divisor' 'a commitment that has ended counts for what was called of it: nothing of it remains to be called' 'an investor whose commitment has ended has nothing left to be called'",
     "Built: funds (structure, manager, fee, capital ledger, confidentiality), investors and capital commitments, capital calls approved by a second person, contributions recorded against a call, units issued when the money is posted, investment transactions (purchase, sale, income, write-down, valuation), holdings in a company of the group or an outside party, management fee by a stated formula and only for days that have passed (tested in the database and in the sample engine), distributions, realised gain or loss on a sale, unrealised change for holdings carried at fair value, net asset value worked out from the books and approved by a second person, a statement per investor on the screen with export to CSV, approval and audit trail on each of these. The module has its own screens, permissions and tables and is separate from ordinary purchases and sales. In the summary of a fund a commitment that has ended counts for what was called of it, so that nothing of it is shown as remaining to be called, and a note says how many have ended (tested). Not built: a scheme as a record of its own (it is a text field on the fund); fund expenses as a register (they are ordinary entries of the fund's company); redemption and transfer of units; carried interest and waterfalls; statements as PDF or sent to investors; an investor portal; any SEBI or AIF report, and any place where such reporting and controls are configured — the screens state that nothing on them is a regulatory report. A net asset value cannot be prepared where two funds share one company. On the statement of an investor whose commitment has ended nothing is shown as not yet called, as in the summary of the fund (tested); the other figures and the lines of the statement have no test. The tile 'Committed' of the fund says that it holds the active commitments and what was called of those that ended; this sentence of the screen has no automated test."),
    ("TESTED", 456, "supabase/migrations/0015_investments_funds.sql save_distribution, submit_distribution, decide_distribution, propose_distribution_payment · src/api/demoInvest.ts · src/pages/Distribution360.tsx · src/pages/Investments.tsx · src/pages/Approvals.tsx · tests/sql/phase3_investments.sql T206 T207 T208 T209 T210 · tests/p3.test.ts 'a distribution: entitlement by units, declaration before payment, tax withheld, a second person for each entry' 'a dividend cannot be declared while no shareholder is on record'",
     "A dividend (of a company to its shareholders) or a distribution (of a fund to its unit holders) is prepared with the entitlement of each holder by shares or units held on the record date, submitted, approved by a second person, declared when its entry is posted, and paid holder by holder through entries that are each proposed and approved. Tax deducted is worked out at the rate entered on the declaration and credited to the ledger of tax payable on payment. Payment cannot be recorded before the declaration is posted. One rate of tax applies to every holder of a declaration; rates per holder and tax certificates are not built. For a dividend all classes of share are counted together. A draft cannot be cancelled from the screen. NUMERO records that the money was paid; it pays nothing."),
    ("TESTED", 561, "supabase/migrations/0015_investments_funds.sql corporate_links, equity_holders, save_corporate_link, save_equity_holder · src/api/demoInvest.ts · src/engine/invest.ts corporateTree · src/pages/Investments.tsx · tests/sql/phase3_investments.sql T190 T191 · tests/p3.test.ts 'the corporate structure: owners cannot hold more than the whole, and a company cannot own its owner' · tests/p3control.test.ts 'the group as a tree: what is held through another company is the product of the percentages'",
     "The register of links records who owns what (a company of the group or an outside party on either side), what the owned entity is — holding company, subsidiary, associate, joint venture, special purpose vehicle, investment entity, operating company or branch — with ownership and voting percentages and the dates between which the link is in force. The screen shows the group as an indented tree with the percentage held directly and through every level, the companies outside the tree, the register of links including those ended, and the shareholders of each company. Owners cannot hold more than the whole and a company cannot own its own owner (tested). The tests use the relations subsidiary and associate; the other six are further values of the same list. The tree is drawn as of today only; there is no drawn chart; a link is ended by a date, not deleted. The form lets a person save a link who manages investments in the company that owns or in the company that is owned, and a Group Super Admin when both sides are outside parties, as the database does; this gate of the screen has no automated test."),
    ("IMPLEMENTED", 1350, "src/engine/invest.ts investmentMap, holdingPosition · supabase/migrations/0015_investments_funds.sql holdings · src/api/demoInvest.ts · src/pages/Investments.tsx · src/pages/Holding360.tsx · tests/p3control.test.ts 'a valuation of a holding at cost stands beside the books' · tests/p3app.test.ts 'investments: carried amount against cost'",
     "The tab 'Group investment map' shows the active investments of each company: a flow from the company that invested to what it invested in, a summary per company (carrying amount, of which at cost, of which in companies of the group, holdings with no valuation) and a table of every holding. The tests cover the position of one holding and the total NUMI states; no test covers the map by company, so the status is IMPLEMENTED and not TESTED. Amounts in different currencies are shown as recorded, without conversion. Only active holdings that are shared with the person are shown."),

    # ------------------------------------------------------------------ System Health
    ("PARTIAL", 304, "src/engine/registerKinds.json · supabase/migrations/0018_platform.sql · src/pages/Registers.tsx · src/pages/Register360.tsx · src/pages/JournalEditor.tsx · src/pages/ClaimEditor.tsx · tests/sql/phase3_platform.sql T265 · tests/p3control.test.ts 'a generator is a register kind with a tag of its own'",
     "Built: a generator is a register item (reference GEN-00001) with the office or site it serves (required, as text), make and model, capacity, fuel (diesel, petrol, gas, battery, solar hybrid), ownership, operating hours as last read with the date of the reading, fuel in the tank as last read, date last serviced, next service due and expiry of the maintenance contract (both watched with a warning). Each generator gets a cost-tracking tag of its own (tested); a journal line, an expense claim or an advance can carry it, and the page of the generator lists the posted entries tagged to it. Not built: a log of diesel bought and used, of maintenance, of repairs and of operating hours (one last reading is kept; cost is seen only as tagged entries, not split into diesel, maintenance and repairs); a link from the generator to the office or site as a record (the office or site is typed, and cost reaches it only when the entry also carries the tag of that office or site); a vendor's bill tagged to the generator (a bill line carries a project only)."),
    ("PARTIAL", 592, "supabase/migrations/0018_platform.sql backup_checks, record_backup_check, system_health · src/api/demoPlatform.ts · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T259 T260 · tests/p3control.test.ts 'capabilities are switched by a Group Super Admin; backups are recorded by a person and never changed'",
     "Built: the tab 'Backups' shows the last successful backup on record, the state of backups in the health report, the last successful restore test on record and the recovery readiness (unknown, unproven, stale, tested), with the last record that did not succeed; a record cannot be changed or removed; with nothing on record the state is 'not recorded' (tested). The screen is open to the permission system.health and to the Group Super Admin. Not built: NUMERO does not see, make or restore a backup — every figure is what a person typed from the console of the database provider, and nothing checks it against the provider."),
    ("PARTIAL", 1280, "supabase/migrations/0018_platform.sql system_health · supabase/migrations/0019_corrections_after_assessment.sql system_health · src/api/demoPlatform.ts · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T260 · tests/sql/phase3_inventory.sql T274 · tests/p3.test.ts 'after everything, the stock ledger and the general ledger agree and nothing is left reserved' 'system health compares a stock ledger with the books also when it holds no item' · tests/p3control.test.ts 'the monthly totals agree with the posted entries' 'a statement line matched in part is not reconciled: the notice and the health of the system count it'",
     "Built: the health report, made when a person opens the screen, counts — for missing data: companies whose analytical store was never refreshed, and backups and restore tests not on record; for stale feeds: bank accounts with no statement line in 35 days, and stores with entries posted since the refresh; for posting failures: posted entries that do not balance, and proposed entries awaiting approval; for reconciliation: statement lines that are not reconciled — unmatched, suggested, awaiting review or matched in part, in the database and in the sample engine alike (tested in the sample engine) — and stock ledgers that differ from the general ledger, also a stock ledger whose categories hold no item yet (tested). Not built: abnormal volumes (volumes are counted and compared with nothing); failed jobs (NUMERO runs no job and keeps no queue; the part is reported as 'not connected'); feeds other than imported bank statements; any watch that runs without a person opening the screen, and any notice when a figure changes."),
    ("TESTED", 1428, "supabase/migrations/0018_platform.sql feature_flags, set_feature_flag · src/api/demoPlatform.ts · src/engine/features.ts capabilityOn · src/store/app.ts · src/App.tsx · src/ui/Shell.tsx · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T258 · tests/p3app.test.ts 'no switch means on' 'switched off for the group' 'a company decides before the group' 'a role decides before the group, and a company with a role before everything' 'what the application cannot run without is never switched off' · tests/p3control.test.ts 'capabilities are switched by a Group Super Admin; backups are recorded by a person and never changed'",
     "A capability (module) is switched on or off for the whole group, for one company, for one role, or for one company and role; the most specific switch decides, and a capability the application cannot run without is never switched off. Only a Group Super Admin sets a switch (tested), and the change is written to the audit trail; the screen asks for a note, the database accepts a switch without one. A user group is a role: there is no switch for a single person. A switch acts on the menu and on the routes of the application: it hides the screen. It changes no permission and the database does not refuse a call to a capability that is switched off. The order of the switches and the rule of the database are tested; hiding the screen in the browser has no automated test."),
    ("PARTIAL", 1429, "supabase/migrations/0018_platform.sql system_health · src/api/demoPlatform.ts · src/pages/SystemHealth.tsx · src/numi/p3.ts · tests/sql/phase3_platform.sql T259 T260 · tests/p3app.test.ts 'system health: what is not recorded or not connected is not counted as in order'",
     "Built: the screen 'System health' reports twelve parts of NUMERO, each with its own state (failure, attention, ok, not recorded, not connected), its explanation and its figures, without a score; it is shown only to the permission system.health (tested); NUMI answers a question about it. Not built: the report is made when a person opens the screen or asks — nothing watches NUMERO between two openings, nothing notifies anyone when a part turns to failure, and no history of the states is kept; the report reads the database only (it measures neither the hosting, nor the storage bucket, nor response times other than the time the report itself took to load)."),
    ("PARTIAL", 1430, "supabase/migrations/0018_platform.sql system_health · supabase/migrations/0019_corrections_after_assessment.sql system_health · src/api/demoPlatform.ts · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T260 · tests/sql/phase3_inventory.sql T274 · tests/p3app.test.ts 'system health: what is not recorded or not connected is not counted as in order' · tests/p3control.test.ts 'a statement line matched in part is not reconciled: the notice and the health of the system count it'",
     "Built: parts for the database (it answered; volumes counted), the posting engine (posted entries that do not balance; entries awaiting approval), queues and background jobs (reported as 'not connected': none exist), bank statements (no feed is connected; accounts without a statement line in 35 days and lines that are not reconciled, a line matched in part among them: tested in the sample engine), integrations (the register; 'not connected' unless one is recorded as active), storage (documents counted from the register of documents, not from the bucket), backups (as recorded by a person) and notifications (unread notices; only the channel inside the application works); also stock against its ledger (every stock ledger, also one whose categories hold no item yet: tested), alerts and cases, the audit trail and the analytical store. Not built: a part for AI and a part for the API (the screen says that the report has none); reconciliation jobs (there are none; statement lines that are not reconciled are counted under bank statements)."),
    ("PARTIAL", 1432, "supabase/migrations/0018_platform.sql backup_checks, record_backup_check, system_health · src/api/demoPlatform.ts · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T260 · tests/p3control.test.ts 'capabilities are switched by a Group Super Admin; backups are recorded by a person and never changed'",
     "Built: a person records each restore test with its date, outcome, evidence, recovery point and minutes to recover; the health report states the recovery readiness as 'unproven' while a backup is on record and no restore was tested (tested), and as 'stale' and in need of attention when the last successful restore test is more than 120 days old. Not built: NUMERO tests no restore itself; nothing reminds anyone that a test is due (no notice is raised and nothing runs on a schedule — the state is seen only by a person who opens the screen); the 120 days cannot be changed."),
    ("PARTIAL", 1434, "supabase/migrations/0014_inventory.sql · supabase/migrations/0018_platform.sql fact_ledger_monthly, system_health · supabase/migrations/0019_corrections_after_assessment.sql api_row_probe · src/api/paging.ts · src/api/supabaseCore.ts apiPage · src/api/supabaseP3.ts · src/pages/SystemHealth.tsx · src/pages/InvItem360.tsx",
     "Built: tables carry indexes on the columns they are read by; monthly totals are kept in an analytical store so that analysis over years need not read every line; the store is read page by page; posted entries and stock movements cannot be altered, whatever the volume; a list of the live data layer is read to its end a page at a time, in pages whose size is measured once in a session and not assumed, and one longer than its ceiling is refused with a message, not cut (see requirement 1535); the health screen counts companies, entries and entry lines and states that load tests have not been run. Not built: any load test or measurement at millions of entries; partitioning or archiving; showing a long list page by page or filtering it in the database — the lists of Phase 3 (items, lots, stock documents, conditions noted) are read whole into the browser, and a list of more than 20,000 records is refused, so that a company with more records of one kind than that is shown the message and no list; the health report examines every posted entry each time it is opened. No automated test covers scale."),
    ("PARTIAL", 1535, "src/api/paging.ts all, first · src/api/supabaseCore.ts apiPage, rpcAll · src/api/supabaseOps.ts · src/api/supabaseP3.ts · src/pages/InvItem360.tsx · src/pages/InvUnit360.tsx · src/pages/Notifications.tsx · src/pages/SystemHealth.tsx · src/pages/Imports.tsx · src/pages/Inventory.tsx · src/pages/StockDocEditor.tsx · supabase/migrations/0019_corrections_after_assessment.sql api_row_probe · tests/p3app.test.ts 'page by page, in a complete order, until a page comes back short' 'a list that ends on the edge of a page costs one more request, and loses nothing' 'a list longer than its ceiling is refused, never cut' 'the size of a page is what the API delivers: assumed larger, the list would end early' 'the latest records only: as many as were asked for, and no more' 'a refusal of the database is a refusal, not an empty list' · tests/p3.test.ts 'the movements of one lot are asked for as such, however many the item has'",
     "Built: the live data layer reads a list through one of two readers. One reads the list to its end, a page at a time, in a complete order (the key of the table is added to the order asked for); a list longer than its ceiling — 20,000 records, and 200,000 for ledger totals, balances of parties, monthly totals and stock on hand — is refused with a message and is not cut; the message advises fewer companies, or a shorter period where the list has one. The other reads a stated number of the latest records: 200 notices, 300 rows of the audit trail unless more are asked for, 2,000 stock movements (5,000 on the page of an item and on the page of a unit, 20,000 of one stock document), 200 imports, 500 backup records, 50 runs of a scenario. Items, lots, stock documents, conditions noted on stock and communications, which were cut at a fixed number before, are read to their end, and so are the payroll runs of a period (getPayrollLines in src/api/supabaseOps.ts). The page of a unit asks for the movements of its own unit. The size of a page is measured once in a session: the application asks the database for 1,001 numbers (public.api_row_probe) and counts what arrives, so that a lower 'Max rows' setting of the project does not end a list early; 1,000 is used where it cannot be measured. The item page, the unit page, the page of a stock document, the notices, the backup records, the list of imports (while no filter by status is chosen) and the entries created by an import say on the screen when only the newest records are listed; the health screen states the numbers and, against the live database, the size of a page as measured; reports of record read the ledger itself. The two readers are tested against a query that answers as the API does (six tests), and the request by unit is tested in the sample engine. Not built: showing a long list page by page or filtering it in the database — a list is read whole into the browser, and where more than 20,000 records of one kind exist the screen shows the refusal and no list: the lists of items, lots, stock documents and invoices take no period, so that one company with more than 20,000 of them cannot open those lists. The form of a landed cost reads up to 20,000 movements of the receipt and does not say when that number is reached. Not tested: that each list of the live data layer goes through a reader with the right key, the measure of a page as the application takes it (apiPage in src/api/supabaseCore.ts), and the sentences on the screens — that code runs only against the live database or in the browser, is type-checked, and no screen has been driven against the live database. A check of the function of the database that the measure calls is written (T278 in tests/sql/phase3_platform.sql); this status does not rest on it and it is not cited as evidence."),

    # ------------------------------------------------------------------ Integrations
    ("PARTIAL", 60, "supabase/migrations/0018_platform.sql message_templates, communications, save_message_template, prepare_communication, mark_communication, guard_communication · src/api/demoPlatform.ts · src/pages/Communications.tsx · src/App.tsx · src/ui/Shell.tsx · src/engine/features.ts · tests/sql/phase3_platform.sql T255 T256 · tests/p3control.test.ts 'NUMERO prepares a communication; a person sends it; what was sent cannot be rewritten'",
     "Built: templates for invoice, payment reminder, statement, receipt, approval request, report, confirmation of balance and capital call, kept for the whole group or for one company, each change a new version; a message prepared from a template with the values of its placeholders typed by a person, addressed to a party and optionally linked to one of its open sales invoices; the text can be copied or opened in the person's own mail program; a person records that it was sent and how, or that it was not; the history cannot be rewritten or removed (tested); preparing needs the permission communication.send (tested). The screen, its entry in the menu and its route open to a person who holds communication.send or party.view in a company, as the rule of the database for reading communications says; a person who holds party.view alone reads the history and can prepare and record nothing. This gate of the screen has no automated test. The history is read to its end. Not built: NUMERO sends nothing; the invoice, statement, receipt or report itself is not attached or produced; placeholders are not filled from the books; a message cannot be linked from this screen to a record other than a sales invoice; approval requests are not sent to approvers outside the application."),
    ("PARTIAL", 61, "supabase/migrations/0018_platform.sql notifications, notification_prefs, notify_holders, refresh_notifications, set_notification_pref · supabase/migrations/0019_corrections_after_assessment.sql notify_holders, attention_class, on_alert, refresh_notifications, system_health · src/api/demoPlatform.ts · src/pages/Notifications.tsx · src/ui/Shell.tsx · tests/sql/phase3_platform.sql T240 T241 T253 T254 T276 T277 · tests/p3control.test.ts 'notices: an approval is told to those who can approve, never to the person who made it, and cannot be switched off' 'notices: what falls due is found when a person opens the application, and finding it again adds nothing' 'the owner is not told of every approval that waits: only of what the rules class for the owner' 'the class of an alert is worked out from its difference where it carries no amount, whichever way it points' 'a statement line matched in part is not reconciled: the notice and the health of the system count it'",
     "Built: notices inside the application, by class of attention, with a bell in the header, read and unread, and preferences per kind of notice and channel; approvals that wait for a person are governance notices and cannot be switched off (tested). An approval that waits is told to those who can approve it and never to the person who made it; a Group Super Admin is told of it only when the rules of the group class it as owner action or critical, or when no other person could approve it, and still sees every request in the inbox of approvals (tested). The class of a notice of an alert is worked out from the amount of the alert or, where it carries none, from its difference, by its size (tested). A statement line matched in part counts as not reconciled for the notice of a reconciliation left incomplete, in the database and in the sample engine alike, and the health of the system counts it too (tested in the sample engine). Notices are raised for: an approval waiting, an approval waiting more than three days, an alert of priority or critical attention (an anomaly), a follow-up given to a person or due, a case given to a person, a bank reconciliation left incomplete, and an item of the registers that falls due (rent, lease, insurance, subscription, a compliance deadline such as a tax return recorded there). Not built: delivery by e-mail, push, SMS or WhatsApp (a preference can be recorded; nothing is sent); notices for a vendor's bill that falls due, for a collection overdue and for a cash-flow warning; what falls due is looked for when a person opens the application, not on a schedule."),
    ("PARTIAL", 598, "supabase/migrations/0018_platform.sql integrations, save_integration · src/api/demoPlatform.ts · src/pages/SystemHealth.tsx · tests/sql/phase3_platform.sql T257 · tests/p3control.test.ts 'the register of integrations holds no secret, and guards what can move money'",
     "Built: a register in which a GHL platform (kind 'GHL platform') or any other system is described for the whole group or one company, each with its own list of what it may do, its own authentication method, the place where its secret is kept (never the secret; text that looks like one is refused), its environment and status; an integration that can move money is marked HIGH RISK, needs a recorded test in a sandbox before production and is made active only by a Group Super Admin (tested). Not built: any connection to GHL ONE, Jamin Bazaar, GHL India Ventures, 777 Raptor or any other platform; any interface through which such a platform could reach NUMERO; authentication of an outside system; enforcement of the scopes (they are lines of text). The register records intent only."),
    ("PARTIAL", 1277, "supabase/migrations/0018_platform.sql integrations, save_integration, system_health · src/api/demoPlatform.ts · src/pages/SystemHealth.tsx · src/engine/features.ts · tests/sql/phase3_platform.sql T257 · tests/p3control.test.ts 'the register of integrations holds no secret, and guards what can move money'",
     "Built: the register of integrations with the kinds bank, payment gateway, CRM, HR, payroll, point of sale, ERP, e-commerce, logistics, GHL platform and others, with direction, scopes, risk, environment, status and owner, and the rules that guard what can move money (tested); the health report and the list of capabilities state 'not connected'. Not built: the integration layer itself — NUMERO exposes no interface to other systems and calls none; no connector, no key management, no log of calls, no rate limit. Bank statements, journals and balances enter as files that a person imports."),
]
PLANNED = {
    571: "Manufacturing is not built: no bill of materials, no raw material or finished goods stage, no work in progress, no production order, no consumption, labour, machine cost, overhead, scrap, wastage or yield. The list of capabilities says so under Inventory.",
}
