# Records of phases 1 and 2 brought up to date after phase 3 — part 2. Assessed against the code on 2026-09-27.
#
# Each record replaces the record of the same number in docs/requirement-status.json (or, for a requirement that
# was PLANNED, its reason in docs/requirement-planned-notes.json). What the earlier record said and is still true
# is carried over; what Phase 3 added is named as such. No status was lowered.
# "Phase 1" and "Phase 2" inside a note mean: as recorded at the end of that phase and not assessed again here.
UPDATES = [
    ("PARTIAL", 504, "src/pages/Home.tsx · src/pages/Cockpit.tsx · src/ui/HomeBeyond.tsx",
     "Lowered from IMPLEMENTED on reading the record again after Phase 3: the screens do not hold all that the requirement lists. Built: the Command Centre and the Cockpit show, across the companies a person may read, cash, revenue, expenditure, profit, receivables, payables, assets, liabilities and debt, with companies, banks, customers and vendors, and ask NUMI; Phase 3 adds, beside the ledger, investments and funds, stock, the differences of NUMERO Reality and what waits for the owner (HomeBeyond). Not built: total committed expenditure and forecast cash as figures of this view, and panels for departments, projects, people, tax, audit and the Black Vault; the name 'Control Tower' is only a spoken alias of the Command Centre."),

    # (status, requirement number, evidence, notes)

    ("PARTIAL", 320, "src/pages/Reality.tsx CaseForm, CASE_KINDS, CASE_STATUSES, caseRight · src/pages/Case360.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql cases, open_case, update_case · tests/sql/phase3_control.sql T222 T223 T224 T225 T226",
     "Built: nothing of this requirement was recorded as built before Phase 3 (an incident register item of Phase 2 has types such as theft, improper payment reported and whistleblower report; it has no statuses of investigation). Phase 3 adds cases under NUMERO Reality: a person who reviews alerts opens a case of the kind 'Incident' by hand, with what was found or reported, an amount at stake, an owner, a class of attention and a confidentiality level; the case moves through the statuses open, triage, under review, investigating, substantiated, unsubstantiated, remediated and closed, each change with its note, and closing needs a resolution (T224); its history cannot be rewritten and the case cannot be deleted (T225); an alert under a case found unsubstantiated is closed with it (T226); records — accounting entries, invoices and bills, purchase documents, advances, parties, stock documents and others — are linked to it. The form asks for facts, the engine does not use the word for the offence, and no person is named as responsible by NUMERO. Not built: the listed kinds (duplicate payment, fake invoice and the others) as a field — a case states them in its title and text; 'reported' is the status 'open'; a tie between a case and an incident register item (register items cannot be linked to a case)."),

    ("PARTIAL", 446, "src/pages/Studio.tsx FLOW_EXAMPLES asset_purchase · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T248 T249 T251 T252 · src/pages/Purchasing.tsx · src/pages/Assets.tsx · tests/sql/phase2_treasury_purchasing.sql T94–T106",
     "Built: nothing of this requirement was recorded as built before Phase 3; the pieces exist since Phase 2 as separate records — purchase requisitions, requests for quotation, vendor quotations with a recorded selection, purchase orders under approval, goods receipts (T94–T106), and a fixed asset registered by hand, which can name the bill it was bought on. Phase 3 adds the Scenario Studio, in which a workflow 'Purchase of an asset' is supplied as a starting point: a form for what is to be bought, why it is needed (the justification) and the estimate (the cost), then the steps requisition with quotations (a quotation must be attached), approval, purchase order, delivery, bill, payment and entry in the asset register, each step able to point to its record; a case follows the steps in order, the form is enforced (T248), a step waits for the documents it requires (T251), and the person who started the case cannot complete its approval (T249). The engine is tested on a workflow for an advance, not on this one. Not built: capitalisation that follows from the case — the asset is still registered by hand and completing the case creates nothing; any tie between the case and the purchase records other than a step made to point to one; a capital budget checked against the request; the path is a straight line, a person starts every case, and no workflow exists until a person makes one active."),

    ("IMPLEMENTED", 642, "src/pages/Reality.tsx (Confirmations from outside) · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql confirmations, save_confirmation, update_confirmation, raise_confirmation_alert · tests/sql/phase3_control.sql T231 T232 · tests/p3control.test.ts 'a confirmation: NUMERO works out the balance, a person sends it and records the reply'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds confirmations of balance under NUMERO Reality: for a bank, a person chooses the bank account and the date; NUMERO works out the balance of its bank ledger from posted entries up to that date; the person records that the request was sent, on which day, how and to whom (a request cannot be marked sent without saying how), then the balance the bank confirms, the day it was received and the document received; the difference is calculated, raised as an alert once, and explained or recorded as disputed by a person; a request can be marked unanswered or cancelled with a reason. NUMERO sends nothing and produces no letter. The status is IMPLEMENTED and not TESTED: the tests (T231, T232) drive a confirmation of a customer, not of a bank."),

    ("PARTIAL", 643, "src/pages/Reality.tsx (Confirmations from outside) · src/pages/Communications.tsx · src/api/demoControl.ts · src/api/demoPlatform.ts · supabase/migrations/0016_reality_control.sql save_confirmation, update_confirmation · supabase/migrations/0018_platform.sql message_templates, prepare_communication · tests/sql/phase3_control.sql T231 T232 T233 · tests/sql/phase3_platform.sql T255 T256 · tests/p3control.test.ts 'a confirmation: NUMERO works out the balance, a person sends it and records the reply'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds confirmations of balance with a customer or a vendor under NUMERO Reality: NUMERO works out the balance with the party from posted entries up to the date — receivables less advances received, or payables less advances paid (T231); the person records that it was sent and how, the balance the party confirms, and the difference, which is raised as an alert once and is then explained or recorded as disputed by a person (T232); between companies of the group the other side is read from its own books (T233). Under Communications, a letter of confirmation of balance or a statement of account is prepared from a template and its sending recorded (T255, T256). Not built: a statement or a confirmation request generated from the books — the values of the letter are typed by a person, and the letter is not tied to the confirmation record; 'resolved' as a status of its own (a difference ends as explained or disputed); NUMERO sends nothing."),

    ("PARTIAL", 324, "src/engine/registerKinds.json incident · tests/sql/phase2_flow.sql T68 T69 · src/pages/Register360.tsx · src/pages/Tasks.tsx · src/pages/Reality.tsx CaseForm · src/pages/Case360.tsx LinkDialog, Attachments · src/pages/Control.tsx (Reclassifications) · supabase/migrations/0016_reality_control.sql cases, update_case, propose_reclassification · tests/sql/phase3_control.sql T224 T225 T235",
     "Built: an incident of type 'Off-book transaction reported'; original evidence is attached and can be neither deleted nor altered (T68, T69); follow-ups record the steps of the investigation and their outcome; correcting entries are ordinary journals under approval, and those tagged to the incident's dimension are listed on its page (Phase 2). Phase 3 adds: a case of the kind 'Incident' under NUMERO Reality, opened by a person who reviews alerts, which states what was reported, carries its own attachments and moves through open, triage, under review, investigating, substantiated, unsubstantiated, remediated and closed, each change with its note and closing with its resolution, in a history that cannot be rewritten (T224, T225); accounting entries, parties, bank accounts and other records are linked to the case, so the correcting entries can be named on it; an amount posted to the wrong ledger is moved by a reclassification that leaves the original entry as it is, records the reason, and is posted only on approval (T235; bank, cash, party, tax and intercompany ledgers cannot be reclassified). Not built: the five stages as a guided workflow — the statuses of a case follow no enforced order, and no workflow of the Scenario Studio is supplied for it; a tie between the case and the incident register item (a register item cannot be linked to a case), so the page of the incident still lists only entries tagged to its dimension."),

    ("PARTIAL", 337, "src/engine/registerKinds.json write_off · src/pages/Asset360.tsx · numero_private.propose_asset_disposal · tests/sql/phase2_flow.sql T32 · src/pages/StockDocEditor.tsx · src/pages/Inventory.tsx · src/engine/stock.ts postedLoss · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql save_stock_doc, propose_stock_doc · tests/sql/phase3_inventory.sql T164 T174 T176 · src/pages/Holding360.tsx · src/api/demoInvest.ts",
     "Built: a Write-off Request register item with what is to be written off and the justification (both required), recovery efforts, the approver's name and the voucher number; an asset write-off is a proposed entry that another person must approve (T32); any write-off journal follows the amount-based approval rules for journals (Phase 2). Phase 3 adds the write-off of inventory: a stock adjustment on which every line must state what happened — damage, expiry, theft, breakage, obsolescence, shrinkage and others (T174) — with evidence attached to the document, proposes its entry, which the person who proposed it cannot approve (T164) and which reaches the books only on approval (T176); the loss posted in a period is shown by reason. An investment can be written down through an entry proposed from its page and approved by a second person. Not built: the type of write-off as a field of the register item; evidence required (it can be attached, nothing requires it); an approval workflow on the register item itself (the approver is a typed name); write-off functions for bad debts, advances and receivables; a rule supplied that sends large write-offs to the Super Admin."),

    ("PARTIAL", 339, "src/engine/registerKinds.json incident · tests/sql/phase2_flow.sql T62 T63 · src/pages/Register360.tsx · src/pages/Cash.tsx · src/pages/StockDocEditor.tsx · src/pages/Inventory.tsx · src/engine/stock.ts lossExposure, postedLoss · src/pages/Reality.tsx (Physical verification) · src/pages/Verification360.tsx · supabase/migrations/0014_inventory.sql · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_inventory.sql T174 T175 T176 · tests/sql/phase3_control.sql T227 T228 T230",
     "Built: theft and cyber incidents are recorded with estimated loss, recovered amount and insurance claim reference; a cash count records the difference from the books and raises an alert (T62, T63) (Phase 2). Phase 3 adds: stock noted as missing is shown as exposure, at its cost, without changing its value (T175); a loss of stock is recorded by an adjustment whose lines state the reason, theft among them, and reaches the books only when a second person approves its entry (T174, T176), and the loss posted in a period is shown by reason; physical verifications of fixed assets and of cash under NUMERO Reality, where an asset reported missing or cash found short raises an alert and changes nothing in the books (T227, T228, T230). Not built: the kinds of theft as separate choices on an incident; original value, insurance recovery and net loss as figures (net loss is not calculated); a link between an incident and the stock adjustment, the verification or the write-off that follows it."),

    ("PARTIAL", 346, "src/engine/registerKinds.json · src/engine/templates.ts · src/pages/Registers.tsx · src/pages/Inventory.tsx (Loss exposure) · src/pages/StockDocEditor.tsx · src/engine/stock.ts lossExposure, exposureTotals, postedLoss · src/ui/p3.tsx Exposure · supabase/migrations/0014_inventory.sql · tests/sql/phase3_inventory.sql T174 T175 T176 · tests/p3.test.ts 'an adjustment says what happened; a condition noted on stock is exposure until a loss is approved'",
     "Built: an exceptional-transaction register item with nature 'Wastage', amount and a required explanation; an 'Expired / Damaged Stock' ledger in the wellness template (Phase 2). Phase 3 adds, for inventory: expiry dates on lots, and stock that is expired, near expiry, damaged, obsolete, held for inspection or not moving shown on the Inventory screen as EXPOSURE, beside the loss actually posted and never added to it, with its method stated (quantity × the cost carried; near expiry within 60 days; slow moving after 180 days or the days set on the item) and marked as an estimate (T175); a loss of stock by expiry, damage, breakage, obsolescence or shrinkage recorded by an adjustment whose every line states its reason and posted only on approval (T174, T176), and the loss posted in a period shown by reason. NUMERO still estimates no loss that it posts: every posted amount follows from quantities a person records. Not built: food waste, material waste, construction waste, unused subscriptions and unused bookings as types; a wastage report across these kinds."),

    ("PARTIAL", 362, "Entry › I don't know what this is · src/pages/Entry.tsx · src/engine/templates.ts (2190 Suspense — Needs Classification) · src/pages/Control.tsx (Reclassifications) · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql propose_reclassification, wf_reclassification · tests/sql/phase3_control.sql T235",
     "Built: an entry of which a person does not know the nature is parked in the ledger 'Suspense — Needs Classification', where it stays visible (Phase 1). Phase 3 adds the classification that follows: under Control › Reclassifications an authorised person moves the amount of a posted line from that ledger to the ledger it belongs in, with the reason; NUMERO proposes the entry, a second person approves it, and the original entry stays as it was, with the reason, the person and both entries on record (T235). Not built: AI suggestions for the item; a list of what waits in suspense with its age and who investigates it; a case or a workflow of investigation tied to the item."),

    ("PARTIAL", 373, "tests/engine.test.ts · src/pages/Assets.tsx › Reconciliation · tests/ops.test.ts › the asset register agrees with the general ledger · src/pages/Treasury.tsx · src/pages/Expenses.tsx · src/pages/Inventory.tsx · src/pages/InvItem360.tsx · src/engine/stock.ts stockAgainstBooks · src/pages/SystemHealth.tsx · src/pages/Fund360.tsx · src/engine/invest.ts investorStatement · supabase/migrations/0014_inventory.sql · tests/sql/phase3_inventory.sql T186 T274 · tests/p3app.test.ts 'the stock ledger and the general ledger carry the same value, in both trading companies'",
     "Built: the party subledger, reconciled with its control accounts (Phase 1); since Phase 2 a fixed asset register compared with its ledgers, ledger by ledger, with any difference shown; a loan register with its schedule; advances held, person by person. Phase 3 adds: a stock ledger — item by item, lot by lot and place by place, with every movement and a running quantity — whose value is compared with its ledger in the books, ledger by ledger, on the Inventory screen and under System Health (T186, T274); and, for a fund, a subledger of investors: each commitment with what was called, contributed and distributed and the units held. Not built: a comparison of the investors' subledger with the capital ledger of the fund; subledgers for projects and properties; a comparison of the loan register with the loan ledger."),

    ("IMPLEMENTED", 374, "21 voucher types (src/api/demoCore.ts voucherTypes · supabase/migrations/0002_ledger_engine.sql voucher_types) · src/pages/Control.tsx (Reclassifications) · supabase/migrations/0016_reality_control.sql propose_reclassification · tests/sql/phase3_control.sql T235",
     "Recorded at Phase 1 as implemented, with 21 voucher types, which include the eleven listed; each is a type of an ordinary journal. Phase 3 adds a reclassification made as an operation: a posted line, or part of it, is moved to another ledger with its reason, through an entry proposed by NUMERO and posted on approval, while the original entry stays as it was (T235)."),

    ("PARTIAL", 389, "Banking · src/pages/Cash.tsx · src/pages/Assets.tsx › Reconciliation · tests/sql/phase2_flow.sql T62 · tests/ops.test.ts › the asset register agrees with the general ledger · src/pages/Reality.tsx · src/engine/reality.ts findDifferences · src/lib/realityData.ts · src/pages/StockCount.tsx · src/pages/Inventory.tsx · src/api/demoControl.ts · supabase/migrations/0014_inventory.sql · supabase/migrations/0016_reality_control.sql save_confirmation, update_confirmation · tests/sql/phase3_inventory.sql T177 T180 T186 · tests/sql/phase3_control.sql T230 T231 T232 T233 · tests/p3control.test.ts 'a confirmation: NUMERO works out the balance, a person sends it and records the reply'",
     "Built: bank (Phase 1); cash, as a physical count compared with the book balance (T62); fixed assets, as the register compared with its ledgers. Intercompany differences are shown in the consolidation report. Phase 3 adds: inventory, as a count of each place compared with the books line by line, quantity and value, closed only through an approved adjustment (T177, T180), and as the stock ledger compared with its ledger in the books (T186); cash, also as a verification sheet under NUMERO Reality (T230); confirmations of balance, each worked out from the books as at a date and compared with what the other side confirms, for a bank account, a customer or a vendor (receivables and payables), a loan, a deposit, an investment (a quantity) and another company of the group, whose side is read from its own books (T231–T233); and, under NUMERO Reality, advances compared from approval to release, evidence, settlement and return, and invoices and orders compared with the books and the money. Not built: credit cards, payment gateways, payroll and taxes as reconciliations of their own; security deposits paid or received, which are register items (of deposits, only fixed deposits can be confirmed); each reconciliation is made when a person opens the screen or records a confirmation, not continuously."),

    ("PARTIAL", 396, "tests/engine.test.ts · src/pages/Assets.tsx › Reconciliation · tests/ops.test.ts › the asset register agrees with the general ledger · src/pages/Inventory.tsx · src/engine/stock.ts stockAgainstBooks · src/pages/SystemHealth.tsx · src/engine/reality.ts stock · src/api/demoPlatform.ts systemHealth · supabase/migrations/0018_platform.sql system_health · tests/sql/phase3_inventory.sql T186 · tests/sql/phase3_platform.sql T274 · tests/p3app.test.ts 'the stock ledger and the general ledger carry the same value, in both trading companies'",
     "Built: receivable and payable control accounts compared with the party subledger in a test, with no screen (Phase 1); fixed asset ledgers compared with the asset register on screen and in a test (Phase 2). Phase 3 adds inventory control: the value of the stock ledger is compared with the balance of each stock ledger in the books, on the Inventory screen, under System Health and as a difference in NUMERO Reality (T186; also when the ledger holds no item, T274). The comparison is made when a person opens the screen. Not built: a screen for the receivable and payable comparison; payroll control."),

    ("PARTIAL", 454, "supabase/migrations/0009_treasury_payroll.sql loans.kind · src/pages/Treasury.tsx · src/engine/registerKinds.json (kinds 'capital_infusion', 'dividend') · tests/sql/phase2_treasury_purchasing.sql T84 · src/pages/Investments.tsx (shareholders, dividends and distributions) · src/pages/Distribution360.tsx · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql equity_holders, save_equity_holder, distributions · tests/sql/phase3_investments.sql T206 T207 T208 T209 T210",
     "Built: loans from and to directors, and from and to shareholders (both kinds are offered on the loan screen), as loans in their own liability or asset ledger, apart from expenses (T84: a loan taken must sit in a liability ledger); capital infusion and dividend as register items; reimbursements through expense claims (Phase 2). Phase 3 adds a register of shareholders of each company — holder, class of share, number of shares and paid-up amount as typed by a person, with the share of the class — and dividends declared on it: the entitlement of each shareholder follows the shares held, tax withheld at one rate entered on the declaration, and the declaration and each payment are entries posted only on approval (T206–T209 test this on the units of a fund; a dividend cannot be declared while no shareholder is on record, T210). Not built: a director or shareholder account view that brings capital, loans, reimbursements and dividends of one person together; drawings; capital introduced as read from the books (paid-up capital is typed). No test uses the director or the shareholder kind of loan."),

    ("TESTED", 462, "src/pages/StockCount.tsx · src/pages/Inventory.tsx (Stock counts) · src/engine/stock.ts countDifferences · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql create_stock_count, record_stock_count, review_stock_count, propose_stock_count · tests/sql/phase3_inventory.sql T177 T178 T179 T180 T181",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds the stock count: a count of a place lists the book quantity of every item and lot and freezes the place while it is open (T177); the quantity found is entered, blind by default; the screen shows, line by line, the book quantity, the physical quantity, the difference and its value at the cost of the snapshot, with the value short and over; a difference cannot pass review without its reason, and review needs its own permission (T178, T179); counting changes nothing in the books — the difference reaches them only through an adjustment proposed from the count and approved by a second person (T180); a count that agrees is closed and proposes nothing (T181)."),

    ("PARTIAL", 480, "ratios › runway · src/pages/Analysis.tsx (Burn rate) · src/engine/analysis.ts burnRate · src/numi/p3.ts · tests/p3control.test.ts 'burn rate: cash falling is measured, cash rising is said, too little data is refused' · tests/p3app.test.ts 'burn rate is an average of what happened, not a forecast'",
     "Built: a runway among the ratios, on the run rate (Phase 1). Phase 3 adds Analysis › Burn rate: the net fall in cash and bank balances a month, averaged over the last 3, 6 or 12 months as the person chooses, and the months the cash in hand would last at that rate, with the formula and its figures shown, the burn and the runway marked as estimates, the statement that these are averages of what happened and not a forecast, and no figure where the books hold fewer than three months or cash rose (tested); NUMI answers the same question. Not built: a burn estimated from assumptions a person sets — expected receipts and payments, or a simulation of the Digital Twin — the only choice is the number of past months; a gross burn (the screen says why it is not shown)."),

    ("PARTIAL", 503, "Home, Cockpit, NUMI integrity (src/pages/Home.tsx · src/pages/Cockpit.tsx · src/numi/engine.ts integrity) · src/pages/SystemHealth.tsx · src/api/demoPlatform.ts systemHealth · supabase/migrations/0018_platform.sql system_health · src/pages/Reality.tsx · tests/sql/phase3_platform.sql T259 T274 T279",
     "Built: on Home and the Cockpit, debit and credit integrity (posted entries re-added, unbalanced entries counted, 'ALL BOOKS BALANCED' when they agree), the number of bank lines not reconciled and of drafts and approved entries not yet posted; NUMI answers whether the books balance (Phase 1). Phase 3 adds System Health, which states for the whole group: posted entries that do not balance and entries proposed by operations that await approval, with the oldest; for each bank account the statement lines not matched (a line matched in part counts as not matched, T279) and whether no statement has been imported for 35 days; the value of each stock ledger against its ledger in the books (T274); open alerts and cases; and NUMERO Reality, which lists the records that differ between documents, operations, books, cash and what exists. Not built: one dashboard of the eight — the suspense balance, intercompany differences, unclosed periods and missing documents are not on these screens (the checklist of the month-end close shows the suspense and intercompany balances of one company); control account differences for receivables and payables (the comparison is tested in the engine but shown on no screen)."),

    ("PARTIAL", 560, "supabase/migrations/0009_treasury_payroll.sql fixed_deposits · src/pages/Treasury.tsx · tests/sql/phase2_treasury_purchasing.sql T91–T93 · src/pages/Investments.tsx · src/pages/Holding360.tsx · src/engine/invest.ts · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql holdings, holding_txns, propose_holding_txn, record_holding_valuation, decide_holding_valuation · tests/sql/phase3_investments.sql T192 T193 T194 T195 T196 T197 T198 T199",
     "Built: fixed deposits, with the maturity value labelled as calculated and the interest taken from what the bank paid (Phase 2). Phase 3 adds a register of investments, each an instrument of the kind equity, preference, debt, units of a fund, convertible, partnership interest, property or other, held in a company of the group or in an outside party and carried in an asset ledger (T192); a purchase, a sale with its gain or loss, income with the tax deducted, and a write-down each reach the books only through an entry approved by a second person (T193–T196); accounting is kept apart from valuation: a valuation states its method, its valuer and its basis (T197), and for a holding carried at cost it stands beside the books and proposes no entry (T198), while for a holding at fair value the change is posted on approval (T199). Not built: the maturity date and coupon of a bond, and interest accrued on it (income is recorded when received); investments on the Treasury console, which still shows fixed deposits only; conversion of holdings kept in other currencies."),

    ("PARTIAL", 562, "src/pages/Investments.tsx (corporate structure, shareholders) · src/engine/invest.ts corporateTree · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql corporate_links, save_corporate_link, equity_holders, save_equity_holder, audit_corporate_links, audit_equity_holders · tests/sql/phase3_investments.sql T190 T191",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds, under Investments: a register of the links of the corporate structure — who owns which company of the group or which outside party, the relation, the percentage of ownership and of votes, and the dates from and to which the link is in force — changed only by a person who holds the permission (T190), with a reason; the owners of one entity cannot hold more than the whole, and a company cannot own its own owner (T191); a link that ends is kept with its end date and the register lists ended links; a tree of the structure with the percentage held through every level; and a register of shareholders of each company, with holder, class, number of shares, paid-up amount and share of the class. Every change is written to the audit trail. Not built: an effective date on a shareholding — a change of the number of shares overwrites it, and the earlier number is kept only in the audit trail; the tree as at an earlier date (it is drawn as at today); a history of ownership shown on the screen other than the list of links with their dates."),

    ("PARTIAL", 567, "src/pages/Inventory.tsx · src/pages/InvItem360.tsx · src/pages/InvUnit360.tsx · src/pages/StockDocEditor.tsx · src/engine/stock.ts lossExposure · src/engine/p3Types.ts Tracking, WarehouseKind, HoldCondition · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql · tests/sql/phase3_inventory.sql T168 T170 T171 T172 T173 T175",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds an inventory module: an item is tracked by lot (batch) or by serial number, and an item tracked by lot cannot be received without its lot (T170); a lot carries its expiry date, set from the shelf life of the item (T171); a serial number is one unit (T172); stock is kept by stock location of six kinds, among them 'in transit' for goods in transit (T173); stock on documents awaiting approval is reserved and cannot be issued elsewhere (T168); stock noted as damaged, obsolete, expired, missing or held for inspection is shown as exposure without changing its value (T175), and expired stock is also found from the dates on the lots. Not built: bins within a location; consignment stock (held for or by another party); stock reserved for a customer or an order (the reserve is only that of documents awaiting approval)."),

    ("PARTIAL", 569, "src/pages/Inventory.tsx (Loss exposure, Units and lots, Stock) · src/pages/InvItem360.tsx · src/engine/stock.ts lossExposure · supabase/migrations/0014_inventory.sql stock_on_hand · tests/sql/phase3_inventory.sql T171 T272 · tests/p3.test.ts 'stock moved to another place was not received again: it is as old as its receipt'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds expiry views of stock: lots with their expiry dates, sortable, and under Loss exposure stock expired and stock expiring within 60 days, with its quantity and value at cost; stock that has not moved for 180 days, or the days set on the item, is shown as slow moving, and the day stock came in is that of its receipt, not of a transfer (T272); the stock screen shows the last day in and out of each item. Not built: ageing of stock in the bands 0–30, 31–60, 61–90, 91–180 and over 180 days; the 60-day window of near expiry cannot be changed."),

    ("PARTIAL", 572, "src/pages/StockDocEditor.tsx (landed cost) · src/pages/InvUnit360.tsx IMPORT_FIELDS · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql save_stock_doc, propose_stock_doc · tests/sql/phase3_inventory.sql T182 · tests/p3.test.ts 'landed cost joins the stock that is still there; the share of what has left is a cost now'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds landed cost on a posted stock receipt: freight, insurance, customs duty, clearing charges (the charges of the clearing agent), port charges, inland transport and handling are offered, and a charge under any other name — demurrage, detention or warehousing — can be typed, each with its amount, the ledger credited and the party owed, shared over the goods by value, quantity or weight, the share of goods still in stock joining their cost (T182); on a lot or a unit, the supplier invoice, the bill of entry, the port of entry, the country of origin, the currency and the rate of exchange, typed after the receipt. Not built: shipment, container and bill of lading or airway bill as records or fields; duty as anything other than an amount typed; charges in a foreign currency; a link from a charge to the bill of the clearing agent or the transporter; anything for exports."),

    ("PARTIAL", 581, "src/engine/templates.ts · src/engine/registerKinds.json · src/pages/Registers.tsx · src/pages/Investments.tsx · src/pages/Fund360.tsx · src/pages/Holding360.tsx · src/pages/Distribution360.tsx · src/pages/Approvals.tsx · src/engine/invest.ts fundSummary, investorStatement · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql · tests/sql/phase3_investments.sql T195 T197 T199 T200 T201 T202 T203 T204 T205 T206 T209 T213 · tests/p3app.test.ts 'the fund: what was called is owed, what was received became units, and the net asset value rests on the books of its own company'",
     "Built: a fund company template with ledgers for unit capital, portfolio investments, management fees, realised and unrealised gains; a 'fund' tag; capital call and distribution register items that appear in Forward (Phase 2). Phase 3 adds fund accounting on the books of the fund's own company: a fund with its scheme, structure, manager, fee and capital ledger, kept confidential (T200); investor commitments; capital calls as a percentage of commitments, approved by a second person and posting nothing (T201); contributions received per investor, never above what was called, with units issued when the money is posted (T202, T203); a capital account per investor — committed, called, contributed, distributed, units held and their value — on the page of the fund, with export; portfolio investments held by the fund, with valuations that state their method, valuer and basis (T197), realised gain or loss on a sale (T195) and unrealised change at fair value (T199); the net asset value prepared from the books and approved by a second person (T204); the management fee with its formula, never charged twice or for days that have not passed (T205, T213); distributions by units held on the record date, with tax withheld, paid through approved entries (T206, T209). Not built: fund expenses as a record of their own (they are ordinary entries of the fund's company and reach the net asset value through its books); valuation inputs beyond a value with its method, valuer and basis (no model); carried interest and waterfalls; redemption and transfer of units; regulatory reporting. The net asset value is an accounting figure, not a validated regulatory valuation: professional validation remains outside NUMERO."),

    ("PARTIAL", 681, "src/engine/registerKinds.json capital_call, capital_infusion, dividend · src/pages/Registers.tsx · src/engine/forward.ts buildEvents · src/pages/Fund360.tsx · src/engine/invest.ts fundSummary, investorStatement · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql · tests/sql/phase3_investments.sql T201 T203 T205 T206",
     "Built: capital calls (with total commitment and called to date), capital infusions and dividends or distributions are register items shown in Forward as EXPECTED, apart from the books (Phase 2). Phase 3 adds investor accounting itself, kept on the page of a fund and in the books of its company, apart from Forward: for each investor, what was called and is not yet received, and what remains to be called of the commitment; capital calls approved (T201) and contributions posted (T203); management fees charged (T205) and distributions declared (T206). Not built: these Phase 3 records in Forward — the capital calls, distributions and fees of the fund module are not read by Forward, which still shows only the register items; expected management fees, fund expenses and portfolio investment commitments as future amounts; a forecast of calls or distributions not yet made."),

    ("PARTIAL", 695, "src/engine/registerKinds.json (kind 'capital_infusion') · src/pages/Registers.tsx · src/pages/Fund360.tsx · src/pages/Approvals.tsx · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql fund_commitments, capital_calls, propose_capital_receipt · tests/sql/phase3_investments.sql T201 T202 T203",
     "Built: a capital infusion register item with party (the source), amount, instrument and a state chosen from the list the database accepts, which includes proposed, approved, committed and received (Phase 2). Phase 3 adds, for a fund, capital from investors followed amount by amount: what each investor committed, what a capital call asks of it — submitted, then approved by a second person (T201) — and what was received, posted to the bank and to the capital of the investors, never more than was called (T202, T203); an investor is any party, including a company of the group recorded as a party. Not built: for a company that is not a fund, the amounts proposed, approved, committed and received as separate figures, and a link from the register item to the receipt in the books."),

    ("PARTIAL", 361, "src/pages/Expenses.tsx (Categories) · src/pages/Accounts.tsx · src/pages/Genesis.tsx · src/pages/Registers.tsx (Register kinds) · src/pages/Payroll.tsx · src/ui/ApprovalRuleEditor.tsx · src/ui/ops.tsx (CustomFields) · tests/sql/phase2_flow.sql T70 · tests/ops.test.ts 'policy flags inform the approver and never reject on their own' · src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T248 T249 T252",
     "Built: all of the following without coding — expense categories (covers expense and entertainment types), revenue ledgers in the chart of accounts, party types, departments, offices, cost centres and projects (organisation units and new structure levels), incident types and subscription plans (options of a register kind, edited by a Group Super Admin), utilities (register items), allowances (freely named salary components), approval rules (kind of record, company, amount band and steps by role, added and changed on the Approvals page), custom fields (defined in Genesis; those defined for invoices and bills, register items, fixed assets and parties appear on those records, where their values are entered) (Phase 2). Phase 3 adds, in the Scenario Studio, workflows designed without coding by a person who manages workflows: a straight line of steps of nine kinds, among them approval steps by role that the person who started the case cannot complete, a form and the documents each step requires; a workflow is checked when it is designed and kept in versions (T247, T248, T249, T252). Not built: new confidentiality levels (the five levels are fixed in the database); an approval workflow beyond a rule of the approval engine or a line of steps of the Studio — no condition, no branch, no steps taken side by side, and a workflow of the Studio approves no journal or document of the books; custom fields on journals, payments, organisation units and companies, which can be defined but are shown on no screen. The approval rule editor and the custom fields on a party were read in the code; neither has an automated test."),

    ("PARTIAL", 426, "src/pages/Twin.tsx · src/pages/TwinParts.tsx · src/engine/twin.ts simulate, compare · src/lib/twinData.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T244 T245 · tests/p3app.test.ts 'the twin starts from the books: cash and receivables are those of the balance sheet' 'a simulation leaves the base and the books as they were' · tests/p3control.test.ts 'side by side: the base and the scenarios, with the change from the base'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (Forward projects cash only). Phase 3 adds the Digital Twin: from the balances of the books — cash, receivables, payables, inventory, borrowings and fixed assets, shown at the start and marked ACTUAL — it projects month by month cash, receivables, payables, borrowings and working capital, under assumptions a person sets, each stated with its formula; every figure is marked SIMULATION, and a saved result touches no entry and cannot be relabelled (T244, T245); scenarios are set side by side with the base. Not built: a projected balance sheet — inventory is held at its starting value, fixed assets and equity are not projected (money spent on assets leaves cash and is not added to assets), and the projection is not presented as a balance sheet that balances; the twin is arithmetic on monthly rates read from the books, not a forecast."),

    ("PARTIAL", 471, "src/pages/JournalEditor.tsx · src/pages/Ledger.tsx · src/pages/Control.tsx (Allocations) · src/api/demoControl.ts · src/engine/p3Types.ts AllocationDriver · supabase/migrations/0016_reality_control.sql wf_allocation · tests/sql/phase3_control.sql T236 T237 · tests/p3control.test.ts 'an allocation shares out what the ledger holds, explains itself, and leaves the total unchanged'",
     "Built: nothing of this requirement was recorded as built before Phase 3; since Phase 1 a journal line can be tagged to a department, a project or another unit, and the ledger can be filtered by that tag, so cost gathers on the units it is tagged to. Phase 3 adds allocation, under Control › Allocations: what an income or expense ledger of a company holds for a period is shared between its units of one kind by headcount, revenue, area, usage, equal shares or shares typed by a person, with the formula and the share of each unit on record; no more can be shared than the ledger holds (T236), and the entry is posted only on approval and leaves the total of the ledger unchanged (T237). Not built: a cost-centre report (recorded as not built under requirement 51); allocation rules that are kept and applied again each period; driver values read from the books (they are typed); allocation between companies."),

    ("PARTIAL", 481, "src/engine/forward.ts earlyWarnings · src/pages/Forward.tsx · tests/forward.test.ts 'early warnings state facts, rules and assumptions' · src/pages/Notifications.tsx · src/ui/Shell.tsx · src/api/demoPlatform.ts refreshNotifications · supabase/migrations/0018_platform.sql refresh_notifications, on_alert · supabase/migrations/0019_corrections_after_assessment.sql · tests/sql/phase3_platform.sql T253 T254 T279 · tests/p3control.test.ts 'notices: what falls due is found when a person opens the application, and finding it again adds nothing' 'a statement line matched in part is not reconciled: the notice and the health of the system count it'",
     "Built: nothing of this requirement was recorded as built before Phase 3; Forward, since Phases 1 and 2, raises when it is opened a cash shortfall against a threshold, the service of debt falling due and a promise to pay that has passed. Phase 3 adds notices inside the application, found when a person opens it and not repeated (T254): bank statement lines unmatched for more than a week — 'bank not reconciled' — to those who reconcile (T279); compliance deadlines, among them tax deadlines, and renewals of insurance, rent, leases, guarantees, letters of credit and covenants falling due, to those who read the registers; and every alert of priority or critical attention, to those who watch the company (T253). Not built: receivables overdue, large payments due, budget exceeded, an expense spike, margin decline, suspense too old and period not closed as alerts or notices; loan instalments as a notice (they are among the early warnings of Forward only); anything sent outside the application; nothing runs on a schedule."),

    ("PARTIAL", 527, "src/pages/Purchasing.tsx · src/pages/PurchaseDetail.tsx · supabase/migrations/0007_assets_purchasing.sql purchase_docs, purchase_doc_lines · tests/sql/phase2_treasury_purchasing.sql T94–T106 · src/pages/StockDocEditor.tsx · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql save_stock_doc · tests/sql/phase3_inventory.sql T185",
     "Built: nothing of this requirement was recorded as built; a goods receipt exists since Phase 2 in purchasing — the goods received line by line, with quantity and condition, its date, the purchase order it answers, and the person who recorded it (T94–T106). Phase 3 adds the warehouse: in a company that keeps stock, a stock receipt names the goods receipt, takes its goods into a stock location at the rate of the order, and cannot take in more than was received (T185). Not built: the warehouse on the goods receipt itself (it is on the stock receipt that follows); the receiver as a named field distinct from the person who recorded the receipt."),

    ("PARTIAL", 533, "src/pages/ReportView.tsx › Ageing · src/ui/records.tsx Promises · numero_private.save_promise · src/pages/Tasks.tsx · src/engine/registerKinds.json dispute · src/pages/Communications.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql prepare_communication, mark_communication · tests/sql/phase3_platform.sql T255 T256 · tests/p3control.test.ts 'NUMERO prepares a communication; a person sends it; what was sent cannot be rewritten'",
     "Built: nothing of this requirement was recorded as built; the steps exist as separate records since Phases 1 and 2 — invoices due and overdue in the ageing report, follow-ups with an owner and a due date, promises to pay against an invoice with their outcome, receipts of payment, and disputes as register items. Phase 3 adds the reminder: under Communications a payment reminder is prepared from a template, addressed to the customer and linked to one of its open sales invoices; a person sends it from their own mailbox and records that it was sent and how, and what was recorded cannot be rewritten (T255, T256). Not built: a workflow that carries an invoice from due to reminder, follow-up, promise and payment or escalation — each step is started by a person and nothing ties the steps together; a reminder raised by an invoice that falls due; the amounts of a reminder filled from the books (they are typed); NUMERO sends nothing."),

    ("PARTIAL", 582, "src/engine/registerKinds.json compliance · src/pages/Registers.tsx · src/pages/Analysis.tsx (Compliance deadlines) · src/engine/analysis.ts complianceView · src/pages/Notifications.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql refresh_notifications · tests/p3control.test.ts 'deadlines across companies' · tests/sql/phase3_platform.sql T254",
     "Built: nothing of this requirement was recorded as built before Phase 3; a compliance deadline can be recorded since Phase 2 as a register item, for GST, TDS, income tax, payroll statutory, corporate filing, audit, licence or other, with its due date, and Forward warns of it. Phase 3 adds Analysis › Compliance deadlines, the NUMERO Compliance view: the deadlines recorded for each company, across the companies a person may read, as overdue, due this week, this month and later, by company and in a list; other kinds that carry a due date — insurance, contracts, licences and the rest — can be ticked in (tested); a notice inside the application when a compliance item or a renewal falls due (T254). Not built: the deadlines that apply to a company in law — NUMERO shows only what people recorded, and the screen says so; marking a deadline as met from the view; any reminder outside the application."),

    ("PARTIAL", 591, "src/pages/SystemHealth.tsx (Backups) · src/pages/Settings.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql backup_checks, record_backup_check, system_health · tests/sql/phase3_platform.sql T259 T260 · tests/p3control.test.ts 'capabilities are switched by a Group Super Admin; backups are recorded by a person and never changed'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds, under System Health › Backups, a record that a person enters of each backup the database provider made and of each restore test — date, outcome, what it covers, evidence, who did it, the recovery point and the minutes it took — which cannot be dated in the future, changed or removed (T260); the screen states the last successful backup, the last successful restore test and the recovery readiness: not recorded, unproven (a backup and no restore test), stale or tested. Not built: encrypted backups, point-in-time recovery, replication and restore testing by NUMERO — it makes, copies and restores nothing, and every figure is what a person typed; whether the provider does these was not verified; no written recovery procedure is in the project; nothing reminds anyone that a test is due. No live account exists yet."),

    ("PARTIAL", 603, "src/pages/Reality.tsx (Reality health) · src/engine/reality.ts findDifferences, realityHealth, notChecked, realityOfReport · src/lib/realityData.ts · src/ui/RealityNote.tsx · src/pages/ReportView.tsx · src/pages/SystemHealth.tsx · tests/p3control.test.ts 'physical reality counts what it can find to differ: orders whose goods were received are among those checked' 'a report states the reconciliation of the records it rests on, and of no others'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds NUMERO Reality, which evaluates the reconciliation status of the records a person may read: for each of five realities — document, operation, accounting, cash, physical — how many records were checked, how many agree and how many differ, with the method, what was never looked at and what the person may not read; the differences by chain, largest first; and, under the heading of each report of the library, the reconciliation status of the records it rests on (tested). System Health states the statement lines not matched and the stock ledgers that differ from the books. Not built: continuous evaluation — the status is worked out when a person opens the screen or the report, not as records change, and nothing is raised when it worsens other than the notices and alerts recorded elsewhere; the evaluation is made as the records stand today, not as at the date of a report."),

    ("PARTIAL", 604, "src/pages/Reality.tsx · src/engine/reality.ts purchases, sales, advances, assets, cash, stock, bank, sheets · src/lib/realityData.ts · src/pages/Banking.tsx · src/pages/Assets.tsx › Reconciliation · supabase/migrations/0016_reality_control.sql save_confirmation · tests/sql/phase3_control.sql T230 T231 T232 T233 · tests/sql/phase3_inventory.sql T186 · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'goods received but not taken into stock differ in the physical reality' 'an advance: released above what was approved, held past its date, claimed without receipts' 'what a verification of stock, cash or documents found reaches Reality; the last sheet of a place stands for it'",
     "Built: nothing of this requirement was recorded as built before Phase 3; bank reconciliation exists since Phase 1 and the asset register is compared with its ledgers since Phase 2. Phase 3 adds NUMERO Reality, which attempts: bank ↔ books (statement lines older than a week not matched); cash ↔ books (the last count of each box and verification sheets, T230); customer ↔ receivable and vendor ↔ payable (confirmations of balance, T231, T232); inventory ↔ ledger (T186); asset register ↔ what a verification found; company A ↔ company B (a confirmation that reads the other side from its own books, T233); advance ↔ settlement (approval, release, evidence, settlement and return); purchase order ↔ goods receipt ↔ bill ↔ payment ↔ stock; invoice ↔ books ↔ receipts recorded against it (tested). Not built: card ↔ expense; payroll ↔ bank ↔ ledger; tax ↔ books ↔ filed data; contract ↔ billing ↔ payment; investment record ↔ accounting (an investment can be confirmed with an outside party as a quantity, and is not compared with its ledger); invoice ↔ bank (a receipt is compared as recorded in NUMERO, not with the bank statement). The comparison is made when a person opens the screen."),

    ("TESTED", 614, "src/numi/p3.ts shocksFrom · src/numi/NumiPanel.tsx · src/engine/twin.ts simulate · src/lib/twinData.ts · tests/p3app.test.ts 'the questions of the specification are read as they are asked' 'a what-if is a SIMULATION, says what it assumed, and writes nothing' 'a what-if it cannot read is not guessed'",
     "Built: nothing of this requirement was recorded as built before Phase 3. Phase 3 adds what-if questions to NUMI: 'What if collections are delayed 30 days?' is read as customers paying 30 days later (tested with the words of the specification), a simulation is run on the Digital Twin from the books, and the answer is headed and labelled SIMULATION, beside base figures labelled ACTUAL, states what it assumed and that it is not a forecast, and writes nothing to the books (tested); a question it cannot read is answered as not read, not guessed (tested). The simulation is arithmetic on monthly rates read from the books, not a statistical forecast."),

    ("PARTIAL", 631, "supabase/migrations/0002_ledger_engine.sql journals.origin · src/pages/JournalDetail.tsx · src/pages/Journals.tsx · src/pages/Approvals.tsx · supabase/migrations/0006_workflow_registers_documents.sql documents.origin · src/pages/Imports.tsx · src/api/demoPlatform.ts commitImport · supabase/migrations/0018_platform.sql commit_import · tests/sql/phase3_platform.sql T262",
     "Built: nothing of this requirement was recorded as built; since Phase 1 every journal records its origin — entered by a person, proposed by NUMI and approved by a person, generated from a business event, or imported — and the page of an entry shows it. Phase 3 adds the importer that gives the origin 'imported' its meaning: journals and opening balances brought in from a CSV file arrive as drafts marked as imported and carry the import batch as their source, with the file name and its fingerprint (T262). Not built: bank feed, API, OCR, e-mail, integration and AI extraction as origins — none of these is connected; provenance of records other than journals and uploaded documents."),

    ("PARTIAL", 637, "src/pages/Imports.tsx · src/api/demoPlatform.ts stageImport, commitImport · supabase/migrations/0018_platform.sql stage_import, commit_import, discard_import · tests/sql/phase3_platform.sql T261 T262 · tests/p3control.test.ts 'an import is checked before it enters the books, and enters them as drafts'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds, under Imports, opening balances brought in from a CSV file of the earlier system: a person maps its columns and its account codes to ledgers of NUMERO; every row is checked, and a file whose debits do not equal its credits, or with an account not mapped, fails and cannot be committed (T261); nothing enters the books when a file is staged, and on commit the balances arrive as one draft opening entry, dated as at the day of the balances, which is approved like any other entry (T262). Opening assets, liabilities, equity, receivables, payables, inventory, loans and fixed assets can thus be brought in as ledger balances. Not built: balances by customer and vendor (the file has no party), stock by item, the fixed asset register and the loan register brought in as records; Excel files (CSV only, at most 5,000 rows a file)."),

    ("PARTIAL", 638, "src/pages/Imports.tsx · src/engine/analysis.ts parallelRun · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql stage_import, commit_import · tests/sql/phase3_platform.sql T261 T262 T263 · tests/p3control.test.ts 'an import is checked before it enters the books, and enters them as drafts' 'the books of the earlier system beside NUMERO: ledger by ledger, and ready only when nothing differs'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds a mapping framework that depends on no vendor: a CSV file of any earlier system — journals, opening balances or its trial balance — is read once a person says which column holds what and maps its account codes to ledgers of NUMERO; the file is checked before anything enters the books (T261) and journals arrive as drafts (T262); the trial balance of the earlier system is kept beside the books and compared ledger by ledger, and the parallel run is ready only when nothing differs (T263, tested). Not built: Excel files and the export formats of Tally or an ERP read as they are (they must be saved as CSV); import of masters — accounts, parties, items — and of invoices and bills; a mapping kept and applied to the next file (a staged file is brought in again with its mapping)."),

    ("IMPLEMENTED", 656, "Truth chips (src/ui/kit.tsx Truth) · src/ui/p3.tsx Simulated, Exposure, Estimate · src/pages/Twin.tsx · src/numi/p3.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T244 T245 · tests/p3app.test.ts 'a what-if is a SIMULATION, says what it assumed, and writes nothing'",
     "Recorded at Phase 1 as implemented: a chip names the state of a figure — ACTUAL, COMMITTED, BUDGET, FORECAST, SIMULATION, AI ESTIMATE and others — each with its word and its explanation; BUDGET, FORECAST, AI ESTIMATE and SIMULATION each have their own colour and their own line (solid, dashed, dotted, filled), so they can be told apart without colour. Phase 3 brings the first figures of the state SIMULATION: every result of the Digital Twin and every what-if of NUMI is marked SIMULATION beside base figures marked ACTUAL, and a saved result is labelled SIMULATION in the database, touches no entry and cannot be relabelled (T244, T245); estimates worked out by a formula (burn rate, landed cost before it is posted) are marked ESTIMATE, and stock at stake EXPOSURE. The status stays IMPLEMENTED: no test asserts that every state is shown distinctly on every screen."),

    ("PARTIAL", 664, "src/engine/forward.ts · src/pages/Forward.tsx · src/lib/forwardData.ts · tests/forward.test.ts · tests/numiOps.test.ts · src/pages/Twin.tsx · src/lib/twinData.ts · src/engine/twin.ts · src/pages/Notifications.tsx · supabase/migrations/0018_platform.sql refresh_notifications · tests/sql/phase3_platform.sql T244 T254",
     "Built: a dedicated engine that builds every known future money event from open invoices and bills, promises to pay, approved purchase orders, the registers (50 kinds, and any the administrator adds), loans, deposits, payroll, claims and advances, each with its source, certainty and basis; cash horizons, calendar, early warnings, commitments and payment priority on the Forward screen; a source the viewer may not read is named on screen, not silently left out (Phases 1 and 2). Phase 3 adds scenarios, on the Digital Twin and not in Forward: simulations from the balances of the books and the open purchase commitments Forward reads, marked SIMULATION (T244); and notices inside the application when a deadline or a renewal recorded in the registers falls due, found when a person opens the application (T254). Not built: monitoring that runs by itself — Forward is calculated when it is opened or asked, and nothing runs on a schedule; notice of anything outside the application; statistical forecasts; tax worked out from the books; the records of inventory, investments and funds added in Phase 3 as sources of Forward (capital calls, distributions and fees of a fund are not read); conversion of register items, loans, deposits, advances and claims held in another currency (Forward states how many such items it counts at face value, and in which currencies)."),

    ("PARTIAL", 666, "tests/forward.test.ts 'every event names its source, its certainty and how it was arrived at', 'contingent amounts are reported beside the projection, never inside it' · tests/numiOps.test.ts 'firm and uncertain amounts are never added into one unlabelled figure' · tests/sql/phase2_flow.sql T72 · src/engine/forward.ts · src/engine/twin.ts SIMULATION · src/pages/Twin.tsx · src/numi/p3.ts · tests/sql/phase3_platform.sql T244 T245 · tests/p3app.test.ts 'a what-if is a SIMULATION, says what it assumed, and writes nothing'",
     "Built: every future amount carries one of DUE, CONTRACTED, COMMITTED, SCHEDULED, EXPECTED, PROBABLE, POSSIBLE, CONTINGENT or FORECAST; ACTUAL is used only for the cash of today; contingent amounts are kept out of every projection (tested); firm and other amounts are shown as separate figures (Phase 2). Phase 3 adds SIMULATION: the what-if of the Digital Twin and of NUMI, marked SIMULATION on every figure, kept apart from Forward and from the books, and not relabelled once saved (T244, T245). Not built: a simulation beside the classes of Forward — the twin does not start from the events of Forward by their class, only from the balances and the open purchase commitments. The all-in projection of Forward still adds firm, expected, possible and forecast amounts into one figure, labelled FORECAST, with the firm-only figure beside it."),
]

# Looked at; Phase 3 changed nothing these requirements ask for.
UNCHANGED = [
    335, 336, 342, 344, 345, 347, 355, 356, 357, 360, 368, 381, 386, 387, 397, 400, 403, 424, 430, 432, 448, 457, 465,
    485, 486, 490, 506, 511, 513, 514, 515, 516, 518, 519, 537, 538, 543, 552, 556, 557, 558, 574, 576, 585, 590,
    596, 597, 600, 609, 619, 625, 626, 633, 636, 640, 644, 645, 646, 660, 662, 663, 667, 683, 685, 689, 690,
]
