# Records of phases 1 and 2 brought up to date after phase 3 — part 1. Assessed against the code on 2026-09-27.
#
# Each record replaces the record of the same number in docs/requirement-status.json (or, for a requirement that
# was PLANNED, its reason in docs/requirement-planned-notes.json). What the earlier record said and is still true
# is carried over; what Phase 3 added is named as such. No status was lowered.
# "Phase 1" and "Phase 2" inside a note mean: as recorded at the end of that phase and not assessed again here.
UPDATES = [
    ("PARTIAL", 53, "src/pages/ReportView.tsx Financial Health · src/engine/analysis.ts burnRate · src/pages/Analysis.tsx",
     "Lowered from IMPLEMENTED on reading the record again after Phase 3: the requirement also asks that metrics be definable per company, and that was never built. Built: Reports › Financial Health shows the ratios of the books (current and quick ratio, debt to equity, gross and net margin, receivable and payable days, among others), each with its formula (Phase 1); Phase 3 adds burn rate and runway under Analysis, with their formulas, refused below three months of history. Not built: metrics defined per company; inventory days and the cash conversion cycle are not shown as figures of their own."),

    # (status, requirement number, evidence, notes)

    ("PARTIAL", 2, "Companies, Team, PeriodClose, Genesis · src/pages/SystemHealth.tsx · src/engine/features.ts capabilityOn · src/store/app.ts · src/App.tsx Need · src/ui/Shell.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql feature_flags, set_feature_flag, integrations, save_integration · tests/sql/phase3_platform.sql T257 T258 · tests/p3control.test.ts 'capabilities are switched by a Group Super Admin; backups are recorded by a person and never changed' 'the register of integrations holds no secret, and guards what can move money'",
     "Built: create/archive/clone companies, units, access grants, period lock/reopen, approve/reject, consolidated view, drill-down (Phase 1). Phase 3 adds two controls that only a Group Super Admin holds: capability switches under System Health, by which a module is switched on or off for the whole group, one company, one role, or one company and role (T258) — a switch hides the menu entry and, for the screens built in Phase 3, the screen itself, and it changes no permission; and the register of integrations, in which an integration that can move money is made active only by a Group Super Admin, after a recorded test in a sandbox (T257). Not built: custom-role editor; impersonation; control of integrations beyond the register (no system is connected: the register records intent and controls no connection); control of AI permissions (the switches named NUMI and Voice commands are read by no screen, so Ask NUMI stays in the header when they are off); control of exports; a switch does not close a screen of Phase 1 or 2 to a person who opens it by its address, because those routes do not read the switch."),

    ("PARTIAL", 5, "src/pages/Registers.tsx (Register kinds) · supabase/migrations/0006_workflow_registers_documents.sql register_kinds, save_register_item · src/pages/Register360.tsx · tests/sql/phase2_flow.sql T70–T73 · src/pages/Studio.tsx · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/engine/p3Types.ts FLOW_LINKS · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T249 T251",
     "Built: a Group Super Admin can define a new kind of record (a register kind) with its own fields, reference prefix, category and optional cost-tracking dimension. Records of that kind can be created, edited, searched, given documents and follow-ups, and they appear in Forward. T70–T73 test the register engine on the supplied kinds. Phase 3 adds, beside the kinds and not as part of them: a workflow designed in the Scenario Studio — a straight line of steps, a form, approval steps that the person who started the case cannot complete, documents required per step — whose steps may point to a register item, so that a record of a custom kind can be the subject of a case (T247, T249 and T251 test the workflow engine, not a custom kind). Not built: relationships between custom records, a form designer, accounting mappings, reports, dashboards, APIs and permissions per custom module; a workflow or an approval that belongs to a custom kind — the kind named on a workflow is text that configures nothing, nothing requires a record of the kind to pass through a case, a workflow posts nothing and a person starts every case. No automated test covers creating a kind."),

    ("PARTIAL", 6, "tests/sql/engine_invariants.sql · tests/engine.test.ts · tests/sql/phase2_flow.sql T30–T41 · tests/sql/phase2_treasury_purchasing.sql T84–T93 · tests/ops.test.ts · src/pages/Assets.tsx · src/pages/Treasury.tsx · src/lib/workflow.ts · src/api/demoInventory.ts · src/api/demoInvest.ts · src/api/demoControl.ts · src/pages/StockDocEditor.tsx · src/pages/Holding360.tsx · src/pages/Control.tsx · supabase/migrations/0014_inventory.sql wf_stock_doc · supabase/migrations/0015_investments_funds.sql wf_holding_txn, wf_capital_receipt, wf_distribution, wf_distribution_payment, wf_fund_fee · supabase/migrations/0016_reality_control.sql wf_reclassification, wf_allocation · tests/sql/phase3_inventory.sql T163 T165 T176 T189 · tests/sql/phase3_investments.sql T193 T195 T199 T211 · tests/sql/phase3_control.sql T235 T237 T238",
     "Built: double entry, journals, contra, receipts, payments, purchases, sales, notes, cash/bank book, day book, TB, P&L, BS, cash flow, control accounts, advances, loans, intercompany, suspense (Phase 1, tested). Phase 2 adds depreciation by straight-line or written-down value, calculated for a month when a person starts the run and posted on approval (T30–T38); asset disposal (T39–T41) and impairment; loan disbursement and instalments (T84–T90); fixed deposit placement and closure (T91–T93); entries for advances, expense claims, fund transfers and payroll. Phase 3 adds entries proposed by stock documents (receipt, issue, return, adjustment, landed cost; stock that is lost is written off only through an approved adjustment, T176), by investment transactions (purchase, sale with its gain or loss, income, write-down, change in fair value, T193–T199), by capital received from investors, by dividends and distributions declared and paid, by the management fee of a fund, by the reclassification of a posted line, which leaves the original entry as it is (T235), and by the allocation of a cost between units (T237); every entry posted by these suites balances (T189, T211, T238). Every one is proposed by the operation and reaches the ledger only on approval. Not built: fund flow; accrual and prepayment schedules; runs that start by themselves (a person starts each depreciation run); impairment has no dedicated test."),

    ("PARTIAL", 11, "Documents, DocumentEditor, Owed, ReportView › Ageing · src/ui/records.tsx Promises · src/pages/DocumentEditor.tsx · numero_private.save_promise · tests/forward.test.ts › early warnings state facts, rules and assumptions · tests/sql/phase2_flow.sql T74 · src/pages/Communications.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql message_templates, communications, prepare_communication, mark_communication · tests/sql/phase3_platform.sql T255 T256 · tests/p3control.test.ts 'NUMERO prepares a communication; a person sends it; what was sent cannot be rewritten'",
     "Built: customer master, invoices, partial payments, credit terms, ageing, overdue (Phase 1); promises to pay recorded against an invoice or a customer with amount, date, person and channel, closed with an outcome, shown in Forward as PROMISED and raised as a warning when the date passes; an invoice that takes a customer beyond the configured credit limit is recorded and flagged, not blocked (T74); Phase 3 adds a payment reminder or a statement of account prepared under Communications from a template, addressed to the customer and linked to one of its open sales invoices, with the values of its placeholders typed by a person; the text is copied or opened in the person's own mail program, and the person records that it was sent and how, or that it was not; what was recorded cannot be rewritten (T255, T256). Not built: recurring invoices, payment schedules; the sending of a reminder — NUMERO sends nothing through any channel; a reminder is not raised by an invoice that is overdue (a person chooses to prepare it), and its amounts are typed, not filled from the books. Saving a promise has no dedicated automated test."),

    ("PARTIAL", 12, "Documents, DocumentEditor, Payments · src/pages/Purchasing.tsx · src/pages/PurchaseDetail.tsx · src/ui/records.tsx BillOrder · tests/sql/phase2_treasury_purchasing.sql T94–T106 · tests/ops.test.ts › requisition → order → receipt → bill, with a three-way comparison · src/pages/StockDocEditor.tsx · src/api/demoInventory.ts · src/engine/reality.ts purchases · src/pages/Reality.tsx · supabase/migrations/0014_inventory.sql · tests/sql/phase3_inventory.sql T185 · tests/p3.test.ts 'stock received against a goods receipt takes the rate of the order and cannot exceed what was received' · tests/p3control.test.ts 'the example of the specification: 100 ordered, 100 billed, 82 received, 100 paid — reality does not reconcile' 'goods received but not taken into stock differ in the physical reality'",
     "Built: bills, terms, partial payments, advances, duplicate-bill detection (Phase 1); purchase requisitions, requests for quotation, vendor quotations with a recorded selection, purchase orders, goods and service receipts, a bill linked to its order, and the three-way comparison of ordered, received and billed, which shows quantity differences, the price difference between a bill and its order, and charges that are not on the order (T94–T106); Phase 3 adds: the goods of a confirmed goods receipt are taken into stock by a stock receipt that names it, takes the vendor and the rate of the order and cannot exceed what was received (T185); NUMERO Reality sets, order by order, the order, the receipts, the bills, the bills posted, the payments and the goods taken into stock side by side and reports where they do not agree — billed or paid for what no receipt confirms, bills above the order, bills not in the books, goods received and not taken into stock (tested in the engine). The comparison is made when a person opens the screen. Not built: detection of a price change against earlier purchases (only a bill against its own order is compared); missing-documentation detection for bills; payment anomalies other than a payment for what no receipt confirms."),

    ("PARTIAL", 16, "tax_codes, tax_code_components · Genesis › Tax codes · ReportView › Registers · src/ui/AccountMapping.tsx · tests/sql/phase2_treasury_purchasing.sql T93 · tests/sql/phase2_payroll.sql T115 · src/pages/Holding360.tsx · src/pages/Investments.tsx · src/pages/Distribution360.tsx · src/api/demoInvest.ts · src/pages/Analysis.tsx · src/engine/analysis.ts complianceView · src/pages/Inventory.tsx · tests/sql/phase3_investments.sql T196 T206 T209 · tests/p3.test.ts 'income is recorded with the tax deducted from it' · tests/p3control.test.ts 'deadlines across companies'",
     "Built: CGST/SGST/IGST codes with effective dates, HSN/SAC, sales and purchase registers (Phase 1); tax deducted at source is recorded as an amount entered by a person — on the closure of a fixed deposit, to the ledger mapped as tax deducted receivable (T93), and as a salary deduction, to the ledger mapped as tax deducted payable (T115); tax and compliance deadlines can be recorded in the registers and are raised as warnings in Forward; Phase 3 adds: tax deducted from the income of an investment, entered by a person as the payer stated it and posted with the income to tax receivable (T196); tax deducted from a dividend or a distribution, worked out at the one rate a person enters on the declaration and credited to tax payable when a holder is paid (T206, T209); Analysis › Compliance deadlines, which lists the deadlines recorded in the registers across companies as overdue, this week, this month and later (tested), with a notice inside the application when one falls due; a tax code and an HSN code on an inventory item, as a recorded classification. Not built: TDS/TCS sections, rates and calculation (every rate is typed; NUMERO does not decide which rate applies); reverse charge; ITC reconciliation; return workflows; a calendar of statutory dates (only deadlines that people recorded are shown)."),

    ("PARTIAL", 22, "src/pages/Treasury.tsx · src/pages/Loan360.tsx · supabase/migrations/0009_treasury_payroll.sql · tests/sql/phase2_treasury_purchasing.sql T84–T93 · tests/ops.test.ts 'loan schedule, disbursement and instalments in order' · tests/forward.test.ts 'loan position and debt ladder' · src/pages/Investments.tsx · src/pages/Holding360.tsx · src/ui/HomeBeyond.tsx · src/engine/invest.ts · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql holdings · tests/sql/phase3_investments.sql T192 T193 T195 T198 T199 · tests/p3app.test.ts 'investments: carried amount against cost'",
     "Built: cash and bank positions by company and ledger, fixed deposits, loans taken and given with interest, payment obligations on loans, a liquidity ladder, forex exposure from open documents, and totals across the selected companies of the group (not converted when the companies keep different currencies). Phase 3 adds investments other than fixed deposits, on a screen of their own and not on the Treasury console: holdings in companies of the group or in outside parties, with purchase, sale, income, write-down and valuation, carried at cost or at fair value, each through an approved entry (T193–T199), and a map of what each company has invested; the Command Centre shows the amount carried. Not built: investments on the Treasury console — the console and its totals show fixed deposits and no other investment, and open no holding; holdings in different currencies are shown as recorded, without conversion."),

    ("PARTIAL", 27, "src/pages/StockDocEditor.tsx · src/pages/InvUnit360.tsx · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql save_stock_doc, propose_stock_doc, save_inv_lot · tests/sql/phase3_inventory.sql T182 T185 · tests/p3.test.ts 'landed cost joins the stock that is still there; the share of what has left is a cost now'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds: a landed cost document that names a posted stock receipt and lists its charges — freight, insurance, customs duty, clearing charges, port charges, inland transport, handling, or a charge under any other name — each with its amount, the ledger credited and the party owed, and shares the total over the lines of the receipt by value, by quantity or by weight; the share of goods still in stock joins their cost and the share of goods that have left is a cost at once (T182, tested by value on a receipt of one line); on a lot or a serial-numbered unit, the supplier invoice, the bill of entry, the port of entry, the country of origin, the currency of purchase and the exchange rate, typed after the receipt. The purchase order with its supplier exists since Phase 2, and a stock receipt takes the rate of the order (T185). Not built: incoterms, shipment, container, bill of lading or airway bill, as records or as fields; customs beyond the number of the bill of entry and the duty as a charge; charges in a foreign currency; a link from a charge to the bill of the vendor; import details on the receipt itself; anything for exports."),

    ("PARTIAL", 36, "src/engine/nlp.ts · Sentinel · src/numi/ops.ts · tests/numiOps.test.ts · src/numi/p3.ts · src/engine/analysis.ts unusualEntries · src/pages/Analysis.tsx · tests/p3app.test.ts 'stock: the value agrees with the stock ledger and with the books' 'a what-if is a SIMULATION, says what it assumed, and writes nothing' 'a what-if it cannot read is not guessed' 'burn rate is an average of what happened, not a forecast' · tests/p3control.test.ts 'an unusual entry is measured against its own ledger and explained, not accused'",
     "Built: classification, ledger and journal suggestions, duplicate and anomaly detection, variance explanation (Phase 1); answers on cash ahead from recorded documents and registers, labelled FORECAST, and on advances, claims, commitments, debt, deposits, assets and payroll totals; Phase 3 adds answers on stock (value, exposure, reorder, a named item), on funds and investments, on the differences between records, open cases and confirmations, on burn rate and year on year, on the health of the system and on what waits for the person, each refused where the person lacks the permission; a question that begins 'what if' is answered with a calculation marked SIMULATION, which says what it assumed and what it could not read, and writes nothing (tested); on the Analysis screen, entries unusual for their ledger are found by a statistical rule (median and spread) — NUMI itself does not run that rule. Not built: invoice and receipt extraction; statistical forecasting (the burn rate is an average of what happened and a what-if is arithmetic on monthly rates; neither is a forecast); missing-document detection across the books (only an expense-claim line without a receipt is flagged, by the claim engine). No language model is connected: NUMI works by rules over the records."),

    ("IMPLEMENTED", 39, "src/voice · tests/commands.test.ts · src/voice/commands.ts ROUTES, SENSITIVE · tests/p3app.test.ts 'commands on the phase 3 screens'",
     "Command interpretation is tested. Phase 3 adds the routes of the new screens (inventory, investments, reality, digital twin, sandbox, studio, notifications, communications, system health, imports, analysis, capabilities) and extends the list of what is never carried out from a command: changing stock, declaring or paying a dividend or distribution, buying or selling an investment or calling capital, committing an import, reclassifying or allocating an amount, sending a message, closing a case, switching a capability or an integration. Such a command opens the screen and the person acts there; eleven such sentences are tested, each refused as an action. Microphone capture could not be exercised in the build environment: verify in Chrome or Edge."),

    ("PARTIAL", 40, "run_sentinel · src/pages/Sentinel.tsx · tests/sql/phase2_flow.sql T63 T65 T74 · tests/sql/phase2_treasury_purchasing.sql T100 T102 · tests/sql/phase2_corrections.sql T136 · tests/forward.test.ts › dependence on one vendor is stated beside dependence on one customer · tests/ops.test.ts › a missing asset raises a factual alert and changes nothing in the books · src/api/demoControl.ts · src/api/demoPlatform.ts · src/engine/analysis.ts unusualEntries · src/pages/Analysis.tsx · src/pages/Notifications.tsx · supabase/migrations/0016_reality_control.sql · supabase/migrations/0018_platform.sql on_alert · tests/sql/phase3_control.sql T228 T230 T232 · tests/sql/phase3_platform.sql T253 T277 · tests/p3control.test.ts 'an unusual entry is measured against its own ledger and explained, not accused'",
     "Built: 8 Sentinel rules, run on demand (Phase 1); since Phase 2 further factual alerts are raised by the engine at the moment of the event and appear in the same list — a cash count that differs from the books, a bill above its order or ahead of its receipt, one side of an intercompany transfer standing alone, a customer beyond the credit limit, an identical file uploaded twice, an asset reported missing or damaged, a payment from a cash box above its limit for a single payment (T136); Forward raises a cash shortfall, a large share of receivables with one customer and a large share of payables with one vendor when it is opened; Phase 3 adds: an alert when a verification of assets, stock, cash or documents finds something other than the books say (T228, T230) and when a balance confirmed from outside differs from the books (T232); a notice inside the application, to those who watch the company, for every alert of priority or critical attention (T253); and, under Analysis, entries unusual for their own ledger, found by the median and spread of that ledger and explained in a sentence that says why and that it is for a person to judge (tested) — an unusually large expense or journal entry is found this way, by amount; the list is shown when a person opens the screen and raises no alert. Not built: continuous evaluation (nothing runs on a schedule: the Sentinel rules run when a person starts them, the analysis when its screen is opened); revenue-decline and unusual-vendor rules; an expense spike as a rule of Sentinel (it is seen only as an entry unusual for its ledger)."),

    ("PARTIAL", 42, "approval_rules · numero_private.open_request · src/pages/Approvals.tsx · src/ui/ApprovalRuleEditor.tsx · tests/sql/phase2_corrections.sql T139 T140 T141 · tests/ops.test.ts › in an approval of several steps a later approver may lower the amount, not raise it · src/lib/workflow.ts APPROVAL_ENTITIES · src/api/demoInvest.ts · src/pages/TwinParts.tsx RulesTab · src/engine/analysis.ts tryApprovalRule · src/pages/FlowDesigner.tsx · src/pages/Studio.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_investments.sql T201 · tests/sql/phase3_platform.sql T247 T249 · tests/p3.test.ts 'a capital call is a request, not money: approving it posts nothing' 'a distribution: entitlement by units, declaration before payment, tax withheld, a second person for each entry' · tests/p3control.test.ts 'a rule is tried against what is already on record before it is put in force'",
     "Built: the approval engine chooses a multi-step rule by company, amount and kind of record, and since Phase 2 applies it to journals, entries proposed by operations, advances, expense claims, requisitions and purchase orders; the configured rules are listed on the Approvals screen, where a Group Super Admin or a holder of the permission approval.configure adds and changes them in a form (name, kind of record, company, amount from and to, steps by role in order, in force or not); a rule of two steps is tested on an advance, where a later step may lower the amount authorised and may not raise it (T139 to T141); Phase 3 adds: capital calls and dividends or distributions as kinds of record the rules apply to, decided in the same inbox (T201); under Digital Twin, a rule — kind of record, company, amount band, steps — tried against the requests already on record, with its amounts stated company by company (tested; the trial is not required before a rule is saved, and the roles of the steps are not compared); in the Scenario Studio, a designer in which a workflow is laid out as cards in order, with approval steps by role that the person who started the case cannot complete (T247, T249). Not built: a visual builder of approval rules — the rule editor is a form, and the designer of the Studio builds workflows of cases, not rules of the approval engine; its path is a straight line with no condition on the amount, so the example of the requirement (other approvers for each band of amount) is met by the rules in the form and not by the designer; rules on account, department, project, vendor or risk score. The rule editor has no automated test: the tests save their rule through the data layer."),

    ("PARTIAL", 48, "src/pages/Control.tsx · src/api/demoControl.ts · src/pages/Reports.tsx · supabase/migrations/0016_reality_control.sql wf_allocation · tests/sql/phase3_control.sql T236 T237 · tests/p3control.test.ts 'an allocation shares out what the ledger holds, explains itself, and leaves the total unchanged'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (the profit and loss of one company, or of the companies selected, is a report since Phase 1). Phase 3 adds, under Control › Allocations, the sharing of a cost or an income that stands in one ledger of a company between its units of one kind — departments, projects, branches or any other kind of unit — by headcount, revenue, area, usage, equal shares or shares typed by a person, with the formula and the share of each unit on record, through an entry that is posted only after approval and leaves the total of the ledger unchanged (T236, T237). Not built: a figure of profit by branch, department, project, product, service, property, customer, vendor relationship, salesperson, channel or campaign — the report library holds no such report (project profitability and the cost-centre report are recorded as not built under requirement 51); allocation rules that are kept and applied again — each allocation is a document made once, for one period, and the values of its driver are typed, not read from the books; allocation between companies."),

    ("PARTIAL", 49, "src/pages/Forward.tsx › Calendar · src/engine/forward.ts · tests/forward.test.ts · src/pages/Analysis.tsx · src/engine/analysis.ts complianceView · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql refresh_notifications · tests/sql/phase3_platform.sql T254 · tests/p3control.test.ts 'deadlines across companies'",
     "Built: a month calendar in Forward that places on their dates the collections and payments due on invoices and bills, loan instalments, payroll, subscriptions, rent, insurance premiums, contract amounts, purchase commitments and maturing deposits, each with its certainty and a link to its record; Phase 3 adds, outside the calendar: Analysis › Compliance deadlines, a list of the register items that carry a due date — compliance items such as tax returns and audit deadlines, and other kinds when ticked — across companies, as overdue, this week, this month and later (tested), and a notice inside the application when such an item falls due (T254). Not built: these deadlines on the calendar itself — a date is placed on the calendar only when it carries an amount, so tax and audit deadlines, renewals and expiries recorded without an amount are in the list of deadlines and among the early warnings, and are not on the calendar; budgets; invoice dates (a document is placed on its due date, not its issue date)."),

    ("PARTIAL", 51, "src/pages/ReportView.tsx · src/pages/Assets.tsx · src/pages/Reports.tsx · src/pages/Inventory.tsx · src/engine/stock.ts · src/ui/RealityNote.tsx · tests/sql/phase3_inventory.sql T186 · tests/p3app.test.ts 'the stock ledger and the general ledger carry the same value, in both trading companies' · tests/p3control.test.ts 'a report states the reconciliation of the records it rests on, and of no others'",
     "Built: 17 of the 23 listed reports in the report library (Phase 1); the asset register — cost, accumulated depreciation and book value of every asset, with export — on the Fixed assets screen (Phase 2), not in the report library; Phase 3 adds the valuation of inventory on the Inventory screen, not in the report library: the value of stock by category and item by item (quantity, unit cost calculated, value, places), with export, and the value per the stock ledger set against the balance of the same ledger in the books (T186) — as the stock stands today, not as at a date chosen; and, under the heading of every report of the library that rests on records, the reconciliation status of those records (tested). Not built: inventory valuation as a report of the library and as at a date; project profitability, cost-centre report, tax returns, fund flow."),

    ("PARTIAL", 58, "Banking › Import · src/pages/Banking.tsx · src/pages/Imports.tsx · src/engine/analysis.ts parallelRun · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql stage_import, commit_import, discard_import · tests/sql/phase3_platform.sql T261 T262 T263 · tests/p3control.test.ts 'an import is checked before it enters the books, and enters them as drafts' 'the books of the earlier system beside NUMERO: ledger by ledger, and ready only when nothing differs'",
     "Built: bank statements from a CSV file (Phase 1). Phase 3 adds, under Imports: journal entries, opening balances and the trial balance of an earlier system brought in from a CSV file; a person says which column of the file holds what, and maps the account codes of the file to ledgers of NUMERO; the file is staged and checked before anything enters the books — every row, duplicates, debits against credits, mapping of accounts — every row is shown with what is wrong with it, and a file that fails a check cannot be committed (T261); journals and opening balances then arrive as drafts, which are approved like any other entry (T262); the trial balance of the earlier system is kept beside the books, posts nothing, and is compared with NUMERO ledger by ledger (T263). Not built: Excel files (CSV only, at most 5,000 rows a file); import of accounts, customers, vendors, products, invoices and bills; a reader for the export of any named accounting software or ERP (any CSV whose columns a person maps is read); a staged file cannot be mapped again: it is brought in again with its mapping."),

    ("PARTIAL", 65, "Row Level Security, roles, numero_private schema · src/pages/SystemHealth.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql backup_checks, record_backup_check, integrations, system_health · tests/sql/phase3_platform.sql T257 T259 T260 T266 T267 · tests/p3control.test.ts 'capabilities are switched by a Group Super Admin; backups are recorded by a person and never changed' 'the register of integrations holds no secret, and guards what can move money'",
     "Built: row level security, roles and permissions, and the logic kept in a private schema (Phase 1). Phase 3 adds: a check that every table has row level security and that the internal functions of the platform cannot be called by a signed-in user (T266, T267); under System Health, a record of each backup and of each restore test, entered by a person from the console of the database provider and not changeable afterwards, with the recovery readiness stated as not recorded, unproven, stale or tested (T260); a register of integrations that holds no secret and refuses text that looks like one (T257). Not built: backups, restores and restore tests made by NUMERO — it makes none; backups, point-in-time recovery and disaster recovery are those of the database provider and were not verified in this assessment; nothing reminds anyone that a backup or a restore test is due. Not configured, as recorded at Phase 1: MFA, passkeys, IP restriction, rate limiting."),

    ("IMPLEMENTED", 68, "supabase/migrations · supabase/migrations/0014_inventory.sql · supabase/migrations/0015_investments_funds.sql · supabase/migrations/0016_reality_control.sql · supabase/migrations/0017_scenarios_flows.sql · supabase/migrations/0018_platform.sql · supabase/migrations/0019_corrections_after_assessment.sql · src/api/supabaseCore.ts all, rpcAll · tests/sql/phase3_inventory.sql T187 T189 · tests/sql/phase3_investments.sql T211 · tests/sql/phase3_control.sql T238 · tests/sql/phase3_platform.sql T267",
     "Recorded at Phase 1 as implemented, without a note: relational tables in the migrations, and entries that must balance. Phase 3 adds tables of its own for inventory, which the requirement lists among the core entities (items, lots, stock documents, and movements that can be neither altered nor deleted, T187), and for investments and funds, cases and verifications, simulations and workflows, notifications, imports and an analytical store of monthly totals, each under row level security (T267); every entry posted by the Phase 3 suites balances (T189, T211, T238). The volume the requirement names has not been measured: no load test was run; the live data layer reads lists in pages of 1,000 and refuses, with a message, a list longer than 20,000 rows (200,000 for ledger totals), and that paging has no automated test."),

    ("PARTIAL", 79, "src/pages/SystemHealth.tsx · src/pages/Settings.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql backup_checks, record_backup_check, system_health · tests/sql/phase3_platform.sql T259 T260 · tests/p3control.test.ts 'capabilities are switched by a Group Super Admin; backups are recorded by a person and never changed'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds, under System Health › Backups, a record that a person enters of each backup the database provider made and of each restore test: the date, the outcome, what it covers, the evidence, who did it, the recovery point and the minutes it took to recover; a record cannot be dated in the future, changed or removed (T260); the screen states the last successful backup, the last successful restore test and the recovery readiness — not recorded, unproven (a backup and no restore test), stale, tested. Not built: NUMERO makes, encrypts, versions and restores no backup and tests no restore; every figure is what a person typed, and nothing checks it against the provider; whether the backups of the provider are automated, encrypted, versioned and recoverable to a point in time was not verified in this assessment; no written recovery procedure is in the project; nothing reminds anyone that a backup or a restore test is due. Settings still lists scheduled encrypted backups with restore testing as planned."),

    ("IMPLEMENTED", 85, "supabase/migrations/0006_workflow_registers_documents.sql propose_posting, wf_dispatch, register_kinds · src/engine/registerKinds.json · src/pages/Registers.tsx · supabase/migrations/0014_inventory.sql wf_stock_doc · supabase/migrations/0015_investments_funds.sql wf_holding_txn, wf_capital_receipt, wf_distribution, wf_distribution_payment, wf_fund_fee · supabase/migrations/0016_reality_control.sql wf_reclassification, wf_allocation · src/lib/workflow.ts · src/pages/Fund360.tsx · src/pages/Analysis.tsx · tests/p3app.test.ts 'every workflow source and every approval entity the sample uses has a label, a rule and a link'",
     "Shown by how phase 2 was added: assets, purchasing, advances, cash, treasury and payroll each propose entries through one posting engine, which finds the handler of a module by its name, so a new module adds its own tables and its own handler. The journal functions were extended once, in migration 0006, to call that dispatcher; migrations 0007 to 0009 did not touch them. Register kinds and their fields are data. Phase 3 was added in the same way: inventory, investments and funds, reclassification and allocation each bring their own tables and their own handler, and migrations 0014 to 0019 do not define the journal functions again; one function of Phase 2, save_claim, was changed to carry the booking on a claim line. Of the fifteen future modules listed, Phase 3 built parts of three: fund administration and investor reporting (funds, commitments, capital calls, units, net asset value from the books, a statement per investor on the screen with export; no investor portal, no carried interest, nothing is sent) and analytics (year on year, burn rate, entries unusual for their ledger, an analytical store of monthly totals). The other twelve are not built; insurance policies and contracts exist only as register kinds; the digital twin is arithmetic on monthly rates and is not AI forecasting."),

    ("IMPLEMENTED", 90, "Truth chip on every figure class · src/ui/kit.tsx Truth · src/ui/p3.tsx Simulated, Exposure, Estimate · src/pages/Twin.tsx · src/numi/p3.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T244 T245 · tests/p3control.test.ts 'a saved simulation is labelled SIMULATION, touches no entry, and cannot be relabelled' 'exposure is shown under one heading only, the most serious, and is never added to posted loss' · tests/p3app.test.ts 'a what-if is a SIMULATION, says what it assumed, and writes nothing'",
     "Recorded at Phase 1 as implemented, without a note: a chip names the class of a figure. Phase 3 adds figures of the class SIMULATION and keeps them apart from the books: every result of the digital twin and every what-if answered by NUMI is marked SIMULATION, beside base figures marked ACTUAL; a saved result is labelled SIMULATION in the database, touches no entry and cannot be relabelled, even by a privileged role (T244, T245); stock at stake is marked EXPOSURE and is never added to the loss that was posted (tested); the burn rate and the preview of a landed cost are marked ESTIMATE. The status stays IMPLEMENTED and is not TESTED: the tests assert that simulations and exposure are kept apart, not that each of the five classes is labelled on every screen."),

    ("PARTIAL", 101, "src/pages/Inventory.tsx · src/pages/StockDocEditor.tsx · src/pages/StockCount.tsx · src/api/demoInventory.ts · src/engine/p3Types.ts WarehouseKind · supabase/migrations/0014_inventory.sql warehouses, save_warehouse · tests/sql/phase3_inventory.sql T173 T177 · tests/p3.test.ts 'a transfer proposes no entry: the place changes, the value does not'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (units of a company such as branch, office and site exist since Phase 1 and are recorded under requirement 1). Phase 3 adds the places where stock is kept: a company keeps any number of stock locations of six kinds — warehouse, store, site, office, in transit, service van — each with a code, an address, a keeper and a link to a branch, a site or an office of the company; stock, counts and transfers are kept location by location (T173, T177). Not built: a structure of its own for each location, set up by a person; factories, clinics, showrooms, temporary offices, virtual offices and remote teams as kinds of location (they can be recorded only as units of the company); the value of stock per location (value is kept per item)."),

    ("PARTIAL", 108, "src/pages/Studio.tsx FLOW_EXAMPLES vendor_onboarding · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/api/demoPlatform.ts · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T248 T249 T251 T252 · tests/p3control.test.ts 'a workflow: checked when designed, enforced when run, and it posts nothing'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds the Scenario Studio, in which a workflow for taking on a vendor is designed for one company or for the whole group, in versions (T252); a starting point, 'A new vendor is taken on', is supplied — details and tax document, bank details verified by a second person, approval, vendor told of the terms, first order — and its steps, roles, form and required documents can be changed. A case follows the steps in order: the form is enforced (T248), a step waits for the documents it requires (T251), and the person who started the case cannot complete its approval (T249). The engine is tested on a workflow for an advance, not on this one. Not built: the eight stages of the requirement as supplied (the starting point has five steps; a person adds the others); any tie between the case and the vendor record — a vendor is created, used on a bill and paid whether or not a case exists, and completing a case activates nothing; verification of tax or bank details by NUMERO (a person completes the step); no workflow exists until a person designs one and makes it active; the path is a straight line and a person starts every case."),

    ("PARTIAL", 117, "src/pages/StockDocEditor.tsx · src/pages/Inventory.tsx · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql save_stock_doc, propose_stock_doc, warehouses · tests/sql/phase3_inventory.sql T182 · tests/p3.test.ts 'landed cost joins the stock that is still there; the share of what has left is a cost now'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds landed cost: freight, insurance, customs duty, clearing charges, port charges, inland transport and handling, or a charge under any other name, each with its amount, its ledger and the party owed — the transporter, the forwarder or the clearing agent, as an ordinary party — shared over the goods of a stock receipt by value, by quantity or by weight; the share of goods still in stock joins their cost and the share of goods that have left is a cost at once (T182); and a stock location of the kind 'in transit'. Not built: shipment, consignment, container, vehicle and tracking number as records; origin, destination, volume, fuel surcharge, warehousing, demurrage, detention and delivery; weight other than as the basis for sharing a landed cost; a logistics cost tied to the cost of a project or to the profitability of a product; kinds of logistics provider (a provider is an ordinary vendor)."),

    ("PARTIAL", 121, "src/pages/Fund360.tsx · src/pages/Investments.tsx · src/pages/Distribution360.tsx · src/engine/invest.ts investorStatement · src/api/demoInvest.ts · supabase/migrations/0015_investments_funds.sql · tests/sql/phase3_investments.sql T200 T201 T202 T203 T206 T209 · tests/p3.test.ts 'is confidential: a person who is not cleared does not see it' 'units are issued when the money is posted, and a receipt cannot exceed what was called' · tests/p3app.test.ts 'the fund: what was called is owed, what was received became units, and the net asset value rests on the books of its own company'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds, on the page of a fund, each investor with the commitment, what was called, what is not yet called, what was contributed, what is called and not yet received, the units held and their share of the fund, the distributions paid before and after tax, the value of the units at the last approved net asset value, and a statement line by line with export to CSV, with a link to the party page of the investor; capital calls and distributions are approved by a second person, and units are issued when the money is posted (T201, T203, T206, T209); a fund is confidential, and a person who is not cleared reads neither the fund nor its commitments (T200). Not built: KYC status; documents kept per investor (documents are attached to the fund); one page of an investor across several funds (the statement is that of one commitment in one fund); a statement as PDF or sent to the investor; an investor portal; redemption and transfer of units. The statement has no automated test of its own."),

    ("PARTIAL", 133, "src/engine/registerKinds.json · src/pages/ClaimEditor.tsx · src/pages/Expenses.tsx · src/pages/Register360.tsx · supabase/migrations/0011_review_corrections.sql item_dims · tests/sql/phase2_corrections.sql T135 · tests/ops.test.ts 'a claim linked to a trip carries the trip into its entry' · src/engine/p3Types.ts BookingDetail · src/api/demoOpsB.ts · supabase/migrations/0018_platform.sql check_travel_detail · tests/sql/phase3_platform.sql T265 · tests/p3control.test.ts 'a booking on a claim line: its parts must add up to the line'",
     "Built: a trip register item with its own reference and cost-tracking tag; an advance and an expense claim can be linked to the trip, and the accounting entry of a linked claim or advance carries the trip's tag (tested, T135); the trip page lists the linked claims and advances and shows, from the posted entries tagged to the trip, the cost recorded on expense ledgers apart from the advances still held by people, so that an advance released for the trip is not counted as cost before a claim is approved (the split is calculated on the page and has no test of its own); receipts are attached to the claim; claim lines can be allocated to a department and a project; the claim shows its own total; Phase 3 adds the booking on a line of the claim: a line is marked as a flight, a train, a bus, a cab or a hotel stay, with its operator, booking reference, route or city, dates, class and the parts of its amount (base fare, taxes, booking charges, room charges, meals, toll, parking and others), which must add up to the line (T265, tested with a train). Not built: cost by flight, hotel, taxi, visa and the other headings as figures of the trip — the trip page adds up entries by ledger and does not read the bookings; visa, meals, client meeting, conference and forex as kinds of booking; a vendor's bill tagged to the trip (a bill line carries a project only); allocation to a customer; forex lines."),

    ("PARTIAL", 143, "src/pages/Communications.tsx · src/api/demoPlatform.ts · src/engine/p3Types.ts Communication · supabase/migrations/0018_platform.sql communications, prepare_communication, mark_communication, guard_communication · tests/sql/phase3_platform.sql T255 T256 · tests/p3control.test.ts 'NUMERO prepares a communication; a person sends it; what was sent cannot be rewritten'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds a record of the communications prepared in NUMERO: each message names its party, its channel (e-mail, letter, WhatsApp, SMS, telephone, in person, portal of the other party), its subject and text, the record it is about where one is linked, who prepared it, and whether a person sent it, on which day and how; payment reminders, statements of account, confirmations of balance and capital calls are prepared from templates; what was recorded cannot be rewritten or removed (T256), and preparing needs the permission communication.send (T255). The messages are listed on the Communications screen, where they can be sorted by party. Not built: anything brought in from outside — no mailbox, message service or telephone system is connected, so an e-mail, a message, a call or a meeting note that was not written in NUMERO is not on record; the communications of a party on the page of that party; calls and meeting notes as records of their own; the statement or the invoice itself attached to a message. NUMERO sends nothing."),

    ("PARTIAL", 145, "tests/sql/phase2_payroll.sql T126 · tests/ops.test.ts 'a task cannot be closed without its outcome; required custom fields are enforced' · src/pages/Tasks.tsx · src/pages/Register360.tsx · src/pages/Advance360.tsx · numero_private.save_task · src/pages/Notifications.tsx · src/ui/Shell.tsx · src/api/demoPlatform.ts · supabase/migrations/0018_platform.sql on_approval_request, on_task_assigned, refresh_notifications · tests/sql/phase3_platform.sql T240 T241 T254 T276 · tests/p3control.test.ts 'notices: an approval is told to those who can approve, never to the person who made it, and cannot be switched off' 'notices: what falls due is found when a person opens the application, and finding it again adds nothing'",
     "Built: a person creates a follow-up from an advance, from a register item or from the Follow-ups screen; it is linked to the record, has an owner, a due date and a priority, and cannot be closed without its outcome (T126). Passed promises, expiring documents and contracts that end are shown as warnings in Forward, and requests awaiting approval are listed in the approval inbox. Phase 3 adds notices inside the application: when a request waits for approval, every person who may approve it in that company is told, never the person who made it, and that notice cannot be switched off (T240, T241; a Group Super Admin is told only of what the rules of the group class for the owner, T276); a person is told when a follow-up is given to them and when one of theirs falls due, and when a register item of certain kinds — compliance, insurance, rent, lease, maintenance contract, subscription, licence, guarantee — falls due (T254). Not built: tasks generated by the records themselves (no collection task for an overdue invoice, no renewal task for an expired document); a follow-up cannot be created from an invoice or bill screen; a notice to the owner of a contract that is about to expire — contracts are not among the kinds that raise a notice, and a notice goes to whoever may read the registers, not to a named owner; any notice outside the application (no e-mail, SMS or push is sent); what falls due is looked for when a person opens the application, not on a schedule."),

    ("PARTIAL", 196, "src/engine/registerKinds.json · src/pages/Registers.tsx · src/pages/Expenses.tsx · numero_private.submit_advance, approve_advance · src/pages/Studio.tsx FLOW_EXAMPLES travel_advance · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · src/pages/ClaimEditor.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T248 T249 T250 T271",
     "Built: a trip record with traveller, from, to, purpose, dates, client or project (text) and one estimated amount; an advance request linked to the trip, which goes through approval; Phase 3 adds a second way to make the request: in the Scenario Studio a workflow for travel can be designed — a starting point, 'Employee travel: advance, trip and settlement', is supplied, with a form for destination, purpose, dates, mode and one estimate, and the steps request, approval, check by finance, release of the advance, evidence, settlement and entry; a person who holds flow.view starts a case and states their own request (T271), the form is enforced (T248), the person who started the case cannot approve it (T249), and the step that releases money is complete only when it points to the advance (T250). Not built: the trip record itself still has no approval, and a case is tied to it only if a step is made to point to the register item; estimated cost by flight, train, taxi, hotel, meals, visa, insurance (one estimate); budget check; booking before the journey (a booking is recorded afterwards, on a line of the expense claim); the manager of the employee is not worked out — 'manager approval' is an approval by a role or by any second person; an employee cannot create the trip record (it needs the register.manage permission); no workflow exists until a person designs one and makes it active."),

    ("PARTIAL", 199, "src/pages/ClaimEditor.tsx · src/pages/DocumentEditor.tsx · src/engine/templates.ts · src/engine/p3Types.ts BookingDetail, BOOKING_PARTS · src/api/demoOpsB.ts · supabase/migrations/0018_platform.sql check_travel_detail · tests/sql/phase3_platform.sql T265 · tests/p3control.test.ts 'a booking on a claim line: its parts must add up to the line'",
     "Built: a flight recorded as an expense claim line (airline as merchant, date, amount, ticket attached) or as a travel agent's bill with tax, under the 'Airfare' ledger (Phase 2). Phase 3 adds a booking of the kind flight on the claim line: airline, booking reference (PNR), from, to, class, date of travel, booked through (the travel agent), and the amount made up of base fare, taxes, booking charges, baggage, seat, change fee and cancellation fee; the parts, where given, must add up to the line. Not built: the flight number as a field of its own; a booking on the bill of a travel agent (it is recorded on an expense claim only); no field is required, and the text is stored as typed. The rule that the parts add up is tested with a train booking (T265); a flight has no test of its own."),

    ("PARTIAL", 201, "src/pages/ClaimEditor.tsx · src/engine/templates.ts · src/engine/p3Types.ts BookingDetail, BOOKING_PARTS · src/api/demoOpsB.ts · supabase/migrations/0018_platform.sql check_travel_detail · tests/sql/phase3_platform.sql T265 · tests/p3control.test.ts 'a booking on a claim line: its parts must add up to the line'",
     "Built: local transport recorded as an expense claim line with provider as merchant, purpose, fare and receipt, under the 'Local Conveyance' or 'Toll & Parking' ledger (Phase 2). Phase 3 adds a booking of the kind cab or taxi on the claim line: operator or driver, trip reference, from, to, date, purpose, and the amount made up of fare, taxes, toll, parking, tip and other charges, which, where given, must add up to the line; a bus is a kind of booking of its own (requirement 200). Not built: auto, metro and rental car as kinds of their own (they are recorded as 'cab or taxi', with the operator typed); no field is required. A cab has no test of its own: the rule that the parts add up is tested with a train booking (T265)."),

    ("PARTIAL", 202, "src/pages/ClaimEditor.tsx · src/engine/templates.ts · src/engine/p3Types.ts BookingDetail, BOOKING_PARTS · src/api/demoOpsB.ts · supabase/migrations/0018_platform.sql check_travel_detail · tests/sql/phase3_platform.sql T265 · tests/p3control.test.ts 'a booking on a claim line: its parts must add up to the line'",
     "Built: a hotel stay recorded as an expense claim line (hotel as merchant, date, total, invoice attached) for the traveller, on a claim linked to the trip, under the 'Hotel & Accommodation' ledger (Phase 2). Phase 3 adds a booking of the kind hotel stay on the claim line: hotel, booking reference, city, check-in, check-out, booked through, purpose, and the amount made up of room charges, taxes, meals, laundry and other charges, which, where given, must add up to the line; the screen refuses a stay that ends before it begins. Not built: the number of nights and the room rate as fields (room charges are one amount, and the nights are not worked out from the dates); no field is required. A hotel stay has no test of its own: the rule that the parts add up is tested with a train booking (T265)."),

    ("PARTIAL", 225, "src/engine/templates.ts · src/engine/registerKinds.json · src/pages/JournalEditor.tsx · src/pages/Ledger.tsx · src/pages/Register360.tsx · supabase/migrations/0018_platform.sql · tests/sql/phase3_platform.sql T265 · tests/p3control.test.ts 'a generator is a register kind with a tag of its own'",
     "Built: ledgers for electricity, water and utilities, telephone and internet, fuel; utility register item with connection number and premises; a journal line tagged to an office, warehouse, site or property, and the ledger filtered by that tag; Phase 3 adds the generator as a register item, with the office or site it serves (typed), its fuel, the fuel in the tank and the operating hours as last read, and a cost-tracking tag of its own (T265), so that fuel bought for a generator is seen on its page when the entry carries its tag. Not built: gas and generator fuel ledgers in the template; a log of fuel bought and used; a bill line tagged to an office, a site or a generator (bills carry a project tag only); a utilities report by location."),

    ("PARTIAL", 259, "src/pages/DocumentEditor.tsx · numero_private.approve_invoice · src/pages/Control.tsx · src/api/demoControl.ts · supabase/migrations/0016_reality_control.sql wf_allocation · tests/sql/phase3_control.sql T236 T237 · tests/p3control.test.ts 'an allocation shares out what the ledger holds, explains itself, and leaves the total unchanged'",
     "Built: one vendor bill entered as several lines, each tagged to a project; the posted entry carries the project on each line (Phase 2). Phase 3 adds an allocation made after posting, under Control › Allocations: an amount that stands in an expense ledger without a project, or with one project, is shared between projects by shares a person types (50, 30, 20) or by another driver, and NUMERO proposes the allocation entry, which is posted on approval and leaves the total of the ledger unchanged (T237, tested between departments). Not built: a split by percentage on the bill itself; a line for head office on a bill (only projects can be chosen on a bill line), and in an allocation every recipient is a unit of the one kind chosen, so projects and a head office share one allocation only if head office is itself recorded as a project; the allocation works on what a ledger holds for a period, not on one invoice."),

    ("PARTIAL", 260, "src/pages/Control.tsx · src/api/demoControl.ts · src/engine/p3Types.ts AllocationDriver · src/pages/PeopleCost.tsx · supabase/migrations/0016_reality_control.sql wf_allocation · tests/sql/phase3_control.sql T236 T237 · tests/p3control.test.ts 'an allocation shares out what the ledger holds, explains itself, and leaves the total unchanged'",
     "Built: nothing of this requirement was built before Phase 3. Phase 3 adds, under Control › Allocations, the sharing of an amount of an income or expense ledger of one company between its units of one kind, by headcount, revenue, area, usage, equal shares or shares typed by a person (which serves a fixed percentage), with the pool it is taken from, the formula in words with its figures, the driver value, the share and the amount of each unit, and the period; no more can be shared out than the ledger holds (T236); the entry is proposed, posted after approval, and leaves the total of the ledger unchanged (T237). Not built: transaction volume and a custom formula as drivers; the values of a driver read from the books (headcount, revenue and area are typed by a person); allocation rules that are kept, versioned and applied again — each allocation is a document made once, for one period; allocation between companies. People cost still states that shared costs are not allocated."),

    ("PARTIAL", 265, "src/engine/analysis.ts unusualEntries · src/pages/Analysis.tsx · tests/p3control.test.ts 'an unusual entry is measured against its own ledger and explained, not accused'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (the Sentinel rules of Phase 1 — a reference used twice, a manual journal posted at a weekend or just below an approval threshold — and the policy flags of an expense claim of Phase 2 are recorded under requirements 40 and 256; they act on bills, payments, manual journals and claim lines, and were not assessed again here). Phase 3 adds Analysis › Unusual entries: every posted entry of the period is measured against the median of its own ledger, so an amount far above what is usual for fuel, meals or any other expense ledger is listed with the usual amount, the spread, the number of entries compared and a sentence that says why it stands apart and that whether it is in order is for a person to say (tested). Not built: a card transaction without a receipt (card transactions are not recorded); comparison by person, vendor, vehicle or season (the comparison is by ledger); an alert or a notice for an unusual entry (the list is shown when a person opens the screen); at most the latest 5,000 posted lines of the period are examined, and only entries above the usual are listed."),

    ("PARTIAL", 286, "src/pages/Notifications.tsx · src/pages/Analysis.tsx · src/engine/analysis.ts attentionOf, forOwner · src/pages/Control.tsx · src/engine/reality.ts · src/api/demoPlatform.ts · src/api/demoControl.ts · supabase/migrations/0018_platform.sql attention_rules, attention_class · supabase/migrations/0016_reality_control.sql · tests/sql/phase3_control.sql T220 T221 T230 · tests/sql/phase3_platform.sql T276 T277 · tests/p3control.test.ts 'who attends to what: the rule of the group decides, and the owner is shown only what needs the owner' 'the owner is not told of every approval that waits: only of what the rules class for the owner'",
     "Built: nothing of this requirement was recorded as built before Phase 3 (approval rules that choose their steps by the amount exist since Phase 1 and are recorded under requirement 42). Phase 3 adds two controls that follow the amount: rules of attention, set by a Group Super Admin under Notifications › Rules, which class a notice or an alert by its kind and its amount as information, finance action, management action, owner action or critical, so that of the approvals that wait the owner is told only of those the rules class for the owner (T276, T277); and a materiality threshold for each company, set with its basis under Control, above which a difference found by a verification, a confirmation or NUMERO Reality is raised as a priority and below which it is left for routine review (T220, T221, T230). Not built: any rule supplied with the application — without a rule of the group nothing is classed as owner action, and where no threshold is recorded for a company every difference counts as above it; the percentage recorded with a threshold is not used in the comparison; a workflow of the Scenario Studio cannot take another path by the amount; proportion in the accounting treatment itself."),

    ("PARTIAL", 309, "src/engine/registerKinds.json · src/pages/Registers.tsx · src/pages/ClaimEditor.tsx · src/engine/p3Types.ts BOOKING_PARTS · tests/sql/phase3_platform.sql T265",
     "Built: an exceptional-transaction register item with nature 'Cancellation loss', amount, explanation, approved by, voucher reference and attached documents; customer refund due as a register item; Phase 3 adds, on the booking of a flight, a train or a bus recorded on a line of an expense claim, the cancellation fee — and for a flight the change fee — as a part of the amount of the line (the rule that the parts add up is tested, T265, with base fare, taxes and booking charges; no test uses a cancellation fee). Not built: type of cancellation; original value, refund, penalty, non-refundable amount, credit received and outstanding refund as fields; a cancellation fee on a hotel stay or on anything other than a travel booking; a cancellation recorded against the booking or the order it cancels."),

    ("PARTIAL", 318, "src/engine/registerKinds.json · src/pages/Registers.tsx · src/pages/Register360.tsx · src/pages/Studio.tsx FLOW_EXAMPLES insurance_claim · src/pages/FlowDesigner.tsx · src/pages/FlowCase360.tsx · supabase/migrations/0017_scenarios_flows.sql · tests/sql/phase3_platform.sql T247 T250 T251",
     "Built: insurance claim register item with policy number, claim number, amount claimed, amount approved by the insurer, amount received, attached documents; an incident register item that carries the claim reference; Phase 3 adds the stages as steps of a workflow: in the Scenario Studio a workflow for an insurance claim can be designed — a starting point is supplied: insurer told, proof of the loss, claim filed, survey, amount received, loss and recovery recognised — and followed case by case, each step completed in its turn, a step waiting for the documents it requires (T251) and the step for the amount received complete only when it points to the receipt (T250; the engine is tested on a workflow for an advance). Not built: a tie between the case and the insurance claim register item, unless a step is made to point to it; 'approved or rejected' as an outcome of a step (a step is done or skipped, and the path has no branch); deductible; outstanding as a figure; no workflow exists until a person designs one and makes it active."),

    ("PARTIAL", 319, "src/engine/registerKinds.json incident · src/pages/Register360.tsx · src/pages/Asset360.tsx · tests/ops.test.ts 'a missing asset raises a factual alert and changes nothing in the books', 'disposal removes cost and accumulated depreciation and records the loss' · src/pages/StockDocEditor.tsx · src/pages/Inventory.tsx · src/engine/stock.ts lossExposure, postedLoss · src/api/demoInventory.ts · supabase/migrations/0014_inventory.sql · tests/sql/phase3_inventory.sql T174 T175 T176 · tests/p3.test.ts 'an adjustment says what happened; a condition noted on stock is exposure until a loss is approved'",
     "Built: damage, theft and loss are recorded as incidents with estimated loss and recovery; separately, an asset found missing at verification raises an alert, and an asset can be written off through a proposed entry that needs approval. Phase 3 adds inventory: stock that is damaged, expired, obsolete or missing is noted as a condition on the stock and shown as exposure, which changes no value (T175); a loss of stock is recorded by an adjustment whose every line states what happened — damage, expiry, theft, breakage, obsolescence, shrinkage — and reaches the books only when its entry is approved by a second person (T174, T176); the loss posted in a period is shown by reason. Not built: a link between the incident and the asset, the stock adjustment or the write-off entry; damage in transit as a reason of its own (a stock location of the kind 'in transit' exists; the reason recorded is damage); one register that lists damage and loss of inventory, equipment, vehicles and property together; the listed kinds of damage as separate choices on an incident."),
]

# Looked at; Phase 3 changed nothing these requirements ask for.
UNCHANGED = [
    1, 3, 8, 9, 17, 18, 23, 32, 46, 52, 59, 64, 75, 78, 81, 95, 99, 105, 115, 116, 119, 125, 126, 131, 136, 139,
    141, 152, 161, 175, 176, 182, 190, 193, 198, 203, 209, 211, 213, 219, 221, 222, 224, 229, 231, 239, 240, 242, 248,
    249, 250, 255, 256, 258, 266, 267, 270, 272, 281, 284, 285, 291, 293, 295, 300, 306, 310, 311,
]
